package mlsidecar

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"net/url"
	"regexp"
	"strings"

	"github.com/kameas-ai/kenaz-harness/core/bundle/manifest"
)

// This file is the build-time engine pin's generator half
// (engine-publication-01ENPUB01 WP-H3, owner decision 2026-10-03 #3:
// "harness release.yml bakes version/URL/sha256/size/KeyID into the
// build (generated Go file)"). `go run ./cmd/kenaz-ml-sign pin-gen …`
// calls NewHTTPMirrorPin + RenderPinnedReleaseSource to rewrite
// pinned_release_gen.go; TestPinnedReleaseGen_NoDrift re-renders the
// checked-in pin and catches shape/format drift — it cannot catch a
// well-formed value swap (a different but valid sha256 or version).

// PinnedReleaseGenFile is the checked-in generated file pin-gen writes.
const PinnedReleaseGenFile = "core/mlsidecar/pinned_release_gen.go"

// EngineSignatureKind/Algorithm are the only signature scheme the engine
// channel publishes (raw 64-byte detached ed25519, kenaz-ml-sign).
const (
	EngineSignatureKind      = "ed25519_detached"
	EngineSignatureAlgorithm = "ed25519"
)

var (
	pinVersionRe = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+(?:[-+][0-9A-Za-z.+-]+)?$`)
	pinSHA256Re  = regexp.MustCompile(`^sha256:[0-9a-f]{64}$`)
	pinKeyIDRe   = regexp.MustCompile(`^[0-9a-f]{64}$`)
)

// ErrInvalidPin reports a pin-gen input that would produce a release the
// install path cannot use.
var ErrInvalidPin = errors.New("mlsidecar: invalid engine release pin")

// NewHTTPMirrorPin builds the canonical EngineRelease for one engine
// published to the kameas release channel — the shape the kenaz-ml
// publish job produces (channel dir https://<env downloads>/kenaz-ml/<ver>,
// artifact + "<artifact>.sig" side by side as bare filenames). It
// validates every field the install path relies on, so a bad release.yml
// input fails the BUILD, not a user's install.
func NewHTTPMirrorPin(version, channelURL, artifactPath, sha256Digest string, sizeBytes int64, keyID string) (EngineRelease, error) {
	bad := func(format string, a ...any) (EngineRelease, error) {
		return EngineRelease{}, fmt.Errorf("%w: %s", ErrInvalidPin, fmt.Sprintf(format, a...))
	}
	if !pinVersionRe.MatchString(version) {
		return bad("version %q is not X.Y.Z[-pre]", version)
	}
	u, err := url.Parse(channelURL)
	if err != nil || u.Scheme != "https" || u.Host == "" || u.User != nil || u.RawQuery != "" || u.Fragment != "" {
		return bad("channel URL %q must be a plain https://host/path URL", channelURL)
	}
	channelURL = strings.TrimRight(channelURL, "/")
	if artifactPath == "" || strings.ContainsAny(artifactPath, `/\`) || strings.HasPrefix(artifactPath, ".") {
		return bad("artifact path %q must be a bare filename in the channel directory", artifactPath)
	}
	if !isDMGArtifact(artifactPath) {
		return bad("artifact path %q must be the notarized .dmg (the only published engine artifact)", artifactPath)
	}
	if !pinSHA256Re.MatchString(sha256Digest) {
		return bad("sha256 %q must be sha256:<64 lowercase hex>", sha256Digest)
	}
	if sizeBytes <= 0 {
		return bad("size %d must be the positive artifact byte count (disclosed before download)", sizeBytes)
	}
	if !pinKeyIDRe.MatchString(keyID) {
		return bad("key id %q must be 64 lowercase hex (sha256 of the raw ed25519 public key)", keyID)
	}
	return EngineRelease{
		Version:        version,
		ChannelKind:    "http_mirror",
		ChannelURL:     channelURL,
		ArtifactPath:   artifactPath,
		ExpectedSHA256: sha256Digest,
		Signature: &manifest.SignatureRef{
			Kind:      EngineSignatureKind,
			Locator:   artifactPath + ".sig",
			Algorithm: EngineSignatureAlgorithm,
			KeyID:     keyID,
		},
		SizeBytes: sizeBytes,
		Source:    "http_mirror:" + channelURL + "/" + artifactPath,
	}, nil
}

const pinnedReleaseHeader = `// Code generated by ` + "`go run ./cmd/kenaz-ml-sign pin-gen`" + `; DO NOT EDIT.
//
// The harness's build-time Kameas ML engine pin (engine-publication-
// 01ENPUB01 WP-H3). The zero value means "no engine release pinned in
// this build": PinnedEngineRelease then reports ErrNoPublishedRelease and
// Settings honestly offers no install. Release builds regenerate this
// file from the published engine (see the engine-pin step in
// .github/workflows/release.yml); TestPinnedReleaseGen_NoDrift catches
// shape/format drift (not a well-formed value swap).

package mlsidecar
`

// RenderPinnedReleaseSource renders the gofmt'd contents of
// pinned_release_gen.go for r. The zero EngineRelease renders the
// "nothing pinned" file. Only fields NewHTTPMirrorPin sets are rendered
// (ChannelPath is local_path-only and never pinned).
func RenderPinnedReleaseSource(r EngineRelease) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(pinnedReleaseHeader)
	if r.Version == "" {
		if r != (EngineRelease{}) {
			return nil, fmt.Errorf("%w: a pin without a version must be entirely zero", ErrInvalidPin)
		}
		b.WriteString("\nvar pinnedRelease = EngineRelease{}\n")
		return format.Source(b.Bytes())
	}
	if r.ChannelPath != "" {
		return nil, fmt.Errorf("%w: ChannelPath is not part of a published pin", ErrInvalidPin)
	}
	b.WriteString("\nimport \"github.com/kameas-ai/kenaz-harness/core/bundle/manifest\"\n\n")
	b.WriteString("var pinnedRelease = EngineRelease{\n")
	fmt.Fprintf(&b, "\tVersion: %q,\n", r.Version)
	fmt.Fprintf(&b, "\tChannelKind: %q,\n", r.ChannelKind)
	fmt.Fprintf(&b, "\tChannelURL: %q,\n", r.ChannelURL)
	fmt.Fprintf(&b, "\tArtifactPath: %q,\n", r.ArtifactPath)
	fmt.Fprintf(&b, "\tExpectedSHA256: %q,\n", r.ExpectedSHA256)
	if r.Signature != nil {
		s := r.Signature
		fmt.Fprintf(&b, "\tSignature: &manifest.SignatureRef{\n\t\tKind: %q,\n\t\tLocator: %q,\n\t\tAlgorithm: %q,\n\t\tKeyID: %q,\n\t},\n",
			s.Kind, s.Locator, s.Algorithm, s.KeyID)
	}
	fmt.Fprintf(&b, "\tSizeBytes: %d,\n", r.SizeBytes)
	fmt.Fprintf(&b, "\tSource: %q,\n", r.Source)
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
