// Code generated by `go run ./cmd/kenaz-ml-sign pin-gen`; DO NOT EDIT.
//
// The harness's build-time Kameas ML engine pin (engine-publication-
// 01ENPUB01 WP-H3). The zero value means "no engine release pinned in
// this build": PinnedEngineRelease then reports ErrNoPublishedRelease and
// Settings honestly offers no install. Release builds regenerate this
// file from the published engine (see the engine-pin step in
// .github/workflows/release.yml); TestPinnedReleaseGen_NoDrift fails on
// any hand edit.

package mlsidecar

var pinnedRelease = EngineRelease{}
