// Command gen-capability-keys emits frontend/src/lib/capability-keys.ts
// from the canonical Go Capability constants defined in core/fleet.
//
// It is invoked via:
//
//	go generate ./core/fleet/...
//
// which is declared in core/fleet/capability_gen.go. The generator is
// byte-equal idempotent — running it twice produces the same output.
//
// The emitted file carries a "Code generated … DO NOT EDIT." header so
// editors and CI tools skip it. The CI parity gate in
// scripts/ci/check-codegen.sh re-runs the generator and fails if the
// committed capability-keys.ts deviates from the freshly-generated one.
//
// Mission: fleet-capability-surface-01NDFSEX09, WP07.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sigil-tech/kaneaz-harness/core/fleet"
)

const generatedHeader = "// Code generated by core/fleet/cmd/gen-capability-keys; DO NOT EDIT."

func main() {
	out := flag.String("out", "frontend/src/lib/capability-keys.ts", "output file path (relative to repo root or absolute)")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintf(os.Stderr, "gen-capability-keys: %v\n", err)
		os.Exit(1)
	}
}

func run(outPath string) error {
	caps := fleet.AllCapabilities()
	if len(caps) == 0 {
		return fmt.Errorf("AllCapabilities() returned empty slice — check core/fleet/capability.go")
	}

	content := generate(caps)

	// Resolve the output path. When invoked via go generate the working
	// directory is core/fleet/ (the package directory), so relative paths
	// must walk two levels up to reach the repo root.
	if !filepath.IsAbs(outPath) {
		// go generate sets $GOFILE and runs from the package directory.
		// Walk up to find the repo root by looking for go.mod.
		repoRoot, err := findRepoRoot()
		if err != nil {
			// Fall back: two levels up from core/fleet/ → repo root.
			repoRoot = filepath.Join("..", "..")
		}
		outPath = filepath.Join(repoRoot, outPath)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(outPath), err)
	}

	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("gen-capability-keys: wrote %s (%d capabilities)\n", outPath, len(caps))
	return nil
}

// generate builds the TypeScript file content from the capability list.
func generate(caps []fleet.Capability) string {
	var b bytes.Buffer

	fmt.Fprintf(&b, "%s\n", generatedHeader)
	fmt.Fprintf(&b, "// Source: core/fleet/capability.go AllCapabilities()\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// To regenerate:\n")
	fmt.Fprintf(&b, "//   go generate ./core/fleet/...\n")
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "export const CAPABILITY_KEYS = [\n")

	for _, c := range caps {
		fmt.Fprintf(&b, "  %s,\n", quote(string(c)))
	}

	fmt.Fprintf(&b, "] as const;\n")
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "export type Capability = (typeof CAPABILITY_KEYS)[number];\n")

	return b.String()
}

// quote wraps s in single quotes, escaping any embedded single quotes.
func quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "\\'") + "'"
}

// findRepoRoot walks the directory tree upwards from the current working
// directory looking for a go.mod file. Returns the directory that contains
// go.mod, or an error if not found within 10 levels.
func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for i := 0; i < 10; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("go.mod not found in any parent directory")
}
