package fleet

import (
	"crypto/ed25519"
	"fmt"
)

// fleetSigningPublicKeyBytes holds the raw 32-byte ed25519 public key used
// to verify signed config bundles distributed by the fleet server.
//
// This variable is intentionally left as an empty string at source time.
// At release time the build pipeline populates it via:
//
//	-ldflags "-X github.com/kameas-ai/kenaz-harness/core/fleet.fleetSigningPublicKeyBytes=<hex>"
//
// The secret FLEET_SIGNING_PUBKEY in the kameas-ai org holds the 64-character
// lowercase hex encoding of the 32 raw bytes of the ed25519 public key
// generated by the ops team. It is referenced in release.yml as:
//
//	-X …core/fleet.fleetSigningPublicKeyBytes=${{ secrets.FLEET_SIGNING_PUBKEY }}
//
// During development / CI without the ldflags the variable remains empty and
// FleetSigningKey() returns nil, causing all bundle verification to fail with
// ErrSigningKeyNotConfigured. This is the intended secure-default: no
// verification → no config applied.
//
// Key format: 64 lowercase hex characters (32 raw ed25519 public key bytes).
// Example generation:
//
//	# Generate a keypair (do NOT commit the private key):
//	openssl genpkey -algorithm ed25519 -out fleet-signing-key.pem
//	openssl pkey -in fleet-signing-key.pem -pubout -outform DER | tail -c 32 | xxd -p | tr -d '\n'
//	# The output is the 64-char hex string to set in FLEET_SIGNING_PUBKEY.
var fleetSigningPublicKeyBytes string

// FleetSigningKey returns the embedded ed25519 public key, or nil when the
// key has not been populated at build time (ldflags absent or dev build).
//
// Callers MUST treat a nil return as a hard-reject: do not apply any config
// bundle when the key is unavailable.
//
// Deprecated in favour of FleetSigningKeys() for multi-key accept-set support;
// kept as a shim for callers that only need the primary key.
func FleetSigningKey() ed25519.PublicKey {
	keys := FleetSigningKeys()
	if len(keys) == 0 {
		return nil
	}
	return keys[0]
}

// FleetSigningKeys returns the accept-set of ed25519 public keys used to
// verify fleet config bundles. Currently the accept-set contains only the
// single key injected at build time, but the slice shape enables key rotation
// without a binary rebuild (ops can publish a bundle signed by the new key
// while the old key is still accepted during the rollover window).
//
// Returns an empty slice when no key has been injected (dev/CI build).
// Callers MUST reject bundle verification when the slice is empty.
func FleetSigningKeys() []ed25519.PublicKey {
	if len(fleetSigningPublicKeyBytes) == 0 {
		return nil
	}
	b, err := hexDecodeString(fleetSigningPublicKeyBytes)
	if err != nil || len(b) != ed25519.PublicKeySize {
		return nil
	}
	return []ed25519.PublicKey{ed25519.PublicKey(b)}
}

// ConfigDistributionEnabled reports whether a fleet signing key is configured
// in this binary. When false, all config-bundle distribution is disabled:
// every Verify call returns ErrSigningKeyNotConfigured and no bundle is applied.
//
// Used by boot assertions (FR-002) and the fleet-health surface (WP02/WP10).
func ConfigDistributionEnabled() bool {
	return len(FleetSigningKeys()) > 0
}

// hexDecodeString decodes a lowercase hex string without importing
// encoding/hex to keep the dependency footprint minimal.
func hexDecodeString(s string) ([]byte, error) {
	if len(s)%2 != 0 {
		return nil, fmt.Errorf("%w: odd-length hex string", ErrSigningKeyNotConfigured)
	}
	b := make([]byte, len(s)/2)
	for i := range b {
		hi, ok1 := hexNibble(s[i*2])
		lo, ok2 := hexNibble(s[i*2+1])
		if !ok1 || !ok2 {
			return nil, fmt.Errorf("%w: invalid hex character", ErrSigningKeyNotConfigured)
		}
		b[i] = hi<<4 | lo
	}
	return b, nil
}

func hexNibble(c byte) (byte, bool) {
	switch {
	case c >= '0' && c <= '9':
		return c - '0', true
	case c >= 'a' && c <= 'f':
		return c - 'a' + 10, true
	case c >= 'A' && c <= 'F':
		return c - 'A' + 10, true
	}
	return 0, false
}
