// Code generated by agentgraph/nodes/cmd/gen; DO NOT EDIT.

// This file is auto-generated by core/agentgraph/nodes/cmd/gen.
// Do not hand-edit; run `go generate ./...` from the repo
// root to refresh.

package agentgraph

// No callable kinds in the catalog yet; the generator emitted no
// per-kind structs. WP04 lands the kind manifests and this file
// populates with one struct per callable kind. Until then the
// hand-written attrs.go remains the source of truth for typed payloads.
