// Code generated by agentgraph/nodes/cmd/gen; DO NOT EDIT.

// This file is auto-generated by core/agentgraph/nodes/cmd/gen.
// Do not hand-edit; run `go generate ./...` from the repo
// root to refresh.
//
// Per-kind manifest versioning constants (mission manifest-versioning-01NDFSEX02).
// ManifestVersion is the semver from the manifest's `manifest_version:` field.
// ManifestFingerprint is the sha256 hex of the behavior-affecting subset
// (ports + attr names/types/defaults + budget); it is recomputed each time
// the manifest or generator changes and baked in at codegen time.
//
// The CI check in scripts/ci/check-manifest-version-bump.sh fails when a
// fingerprint changes without a corresponding ManifestVersion bump.

package agentgraph

// Manifest versioning constants.
// Generated from the resolved manifests in core/agentgraph/nodes/manifests/.
const (
	// ActivityManifestVersion is the behavior-contract semver for `kind: activity`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ActivityManifestVersion = "1.0.0"

	// ActivityManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: activity` at the time of last codegen.
	ActivityManifestFingerprint = "158d28a229936b2aaf002a5f0a422974b4bafc5ec3cedfb85eec8a7812c6717f"

	// ApprovalManifestVersion is the behavior-contract semver for `kind: approval`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ApprovalManifestVersion = "1.0.0"

	// ApprovalManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: approval` at the time of last codegen.
	ApprovalManifestFingerprint = "ae78dfaa2a14aa95bd96d9e12653e7f0bddf816eb278052c4da8d7cd7b25cd05"

	// ArtifactManifestVersion is the behavior-contract semver for `kind: artifact`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ArtifactManifestVersion = "1.0.0"

	// ArtifactManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: artifact` at the time of last codegen.
	ArtifactManifestFingerprint = "c5022aa4743f9ce8a5fe572ecf108bf091ef22a4e4a3c5b2d2c7b591ee4db445"

	// AskManifestVersion is the behavior-contract semver for `kind: ask`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	AskManifestVersion = "1.0.0"

	// AskManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: ask` at the time of last codegen.
	AskManifestFingerprint = "1ab658ef402aa19e09cf14c50b56b23c4fa586c66c89e9688c1aabae6870baf8"

	// AttachmentManifestVersion is the behavior-contract semver for `kind: attachment`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	AttachmentManifestVersion = "1.0.0"

	// AttachmentManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: attachment` at the time of last codegen.
	AttachmentManifestFingerprint = "da47c9f9780af1ad9e54bbeb411893880647d880de9758140880bf509a179119"

	// BranchManifestVersion is the behavior-contract semver for `kind: branch`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	BranchManifestVersion = "1.0.0"

	// BranchManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: branch` at the time of last codegen.
	BranchManifestFingerprint = "c3a7430c6427bc413af770a36ce69c36e4030d4aca99e8457e17c6101e1d8611"

	// CheckpointManifestVersion is the behavior-contract semver for `kind: checkpoint`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	CheckpointManifestVersion = "1.0.0"

	// CheckpointManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: checkpoint` at the time of last codegen.
	CheckpointManifestFingerprint = "07c68b5d94ee5debf002e9ee70a5d795dd865b2fa430d32ab8ffa5caffcdafc4"

	// CompactManifestVersion is the behavior-contract semver for `kind: compact`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	CompactManifestVersion = "1.0.0"

	// CompactManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: compact` at the time of last codegen.
	CompactManifestFingerprint = "7debd5a38105f903defe6081862dc2fa49b8fb6d605300f5844aca21c44bfff3"

	// CorpusReadManifestVersion is the behavior-contract semver for `kind: corpus_read`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	CorpusReadManifestVersion = "1.0.0"

	// CorpusReadManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: corpus_read` at the time of last codegen.
	CorpusReadManifestFingerprint = "8a0ffb39dfcdc60e38e2eaf94276842e8b2fa65da2aaf728817f1c9afc7a5993"

	// CorpusWriteManifestVersion is the behavior-contract semver for `kind: corpus_write`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	CorpusWriteManifestVersion = "1.0.0"

	// CorpusWriteManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: corpus_write` at the time of last codegen.
	CorpusWriteManifestFingerprint = "9351822f153b6e3f99d352bc2b3a2a3e525d9408e996bfba7725ee320627fdcc"

	// DecisionManifestVersion is the behavior-contract semver for `kind: decision`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	DecisionManifestVersion = "1.0.0"

	// DecisionManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: decision` at the time of last codegen.
	DecisionManifestFingerprint = "053994e517971985af90d81140a5ea7e2791b956a7f468d40cac67be81e6ed34"

	// EscalateManifestVersion is the behavior-contract semver for `kind: escalate`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	EscalateManifestVersion = "1.0.0"

	// EscalateManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: escalate` at the time of last codegen.
	EscalateManifestFingerprint = "6c641de5adcafd4bf2a4cfee067a96b2e1a2293de7157aaf4972cffad6add9c8"

	// HistoryReadManifestVersion is the behavior-contract semver for `kind: history_read`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	HistoryReadManifestVersion = "1.0.0"

	// HistoryReadManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: history_read` at the time of last codegen.
	HistoryReadManifestFingerprint = "3c3a9d0bad80ac44da9e7639bb4c7c8589aa779d648e2946819ebdd8a4f50004"

	// JoinManifestVersion is the behavior-contract semver for `kind: join`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	JoinManifestVersion = "1.0.0"

	// JoinManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: join` at the time of last codegen.
	JoinManifestFingerprint = "dadcd3738532457c8a34571388373569cbcaf0989d7e26a98a34eeb53d67e773"

	// LoopManifestVersion is the behavior-contract semver for `kind: loop`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	LoopManifestVersion = "1.0.0"

	// LoopManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: loop` at the time of last codegen.
	LoopManifestFingerprint = "f987be67064127fd52a93302b1a1b1250c5cbaa75cc40c256dd363de185da0e2"

	// MemoryManifestVersion is the behavior-contract semver for `kind: memory`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	MemoryManifestVersion = "1.0.0"

	// MemoryManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: memory` at the time of last codegen.
	MemoryManifestFingerprint = "4875a9183ad5811254027b2c2cffa0f73efe05f62f4abffdc37c9e69113d6e6b"

	// MergeManifestVersion is the behavior-contract semver for `kind: merge`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	MergeManifestVersion = "1.0.0"

	// MergeManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: merge` at the time of last codegen.
	MergeManifestFingerprint = "3ee604efb932ae72a4632aac964f61394036f05d63ca086b19189374efdc0a24"

	// ModelManifestVersion is the behavior-contract semver for `kind: model`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ModelManifestVersion = "1.0.0"

	// ModelManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: model` at the time of last codegen.
	ModelManifestFingerprint = "ac16f050dab4de976de8a75e606a8db369d34ec5676ad1a43a1b3e2caf01c5ac"

	// ParallelManifestVersion is the behavior-contract semver for `kind: parallel`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ParallelManifestVersion = "1.0.0"

	// ParallelManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: parallel` at the time of last codegen.
	ParallelManifestFingerprint = "78376f2cd31addba7a6ce837040488e6030074b3d59bcfba5de6721b28b06dfe"

	// PlannerManifestVersion is the behavior-contract semver for `kind: planner`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	PlannerManifestVersion = "1.0.0"

	// PlannerManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: planner` at the time of last codegen.
	PlannerManifestFingerprint = "a84c0fbfade841b79814d2cf011066e8f6c3487cdc7790857058b2f3b5de514e"

	// ReadBashOutputManifestVersion is the behavior-contract semver for `kind: read_bash_output`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ReadBashOutputManifestVersion = "1.0.0"

	// ReadBashOutputManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: read_bash_output` at the time of last codegen.
	ReadBashOutputManifestFingerprint = "e16ef0994538b1133f19c72231db0a93cb230d0f258199a2ba02c42da0274411"

	// ReadFileManifestVersion is the behavior-contract semver for `kind: read_file`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ReadFileManifestVersion = "1.0.0"

	// ReadFileManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: read_file` at the time of last codegen.
	ReadFileManifestFingerprint = "642e0808e608ffbcb91b68c424d61306d1d69e3f6ba0ed115e590a03b815bc38"

	// ReflectManifestVersion is the behavior-contract semver for `kind: reflect`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ReflectManifestVersion = "1.0.0"

	// ReflectManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: reflect` at the time of last codegen.
	ReflectManifestFingerprint = "d3f1e614fb5433f998909d894f3549f3511b4b656a952a3432e2c2c785ff1eaf"

	// RetryManifestVersion is the behavior-contract semver for `kind: retry`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	RetryManifestVersion = "1.0.0"

	// RetryManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: retry` at the time of last codegen.
	RetryManifestFingerprint = "47bfdb7d14a458c8395089e1cedcffd0ca7ca9013cfd24d7c44b20ceef9db20b"

	// ReviewManifestVersion is the behavior-contract semver for `kind: review`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ReviewManifestVersion = "1.0.0"

	// ReviewManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: review` at the time of last codegen.
	ReviewManifestFingerprint = "732156a7122bfb0053eadb055ec583230f9f2489e7af09de8dedaebfcbac6f59"

	// SessionWriteManifestVersion is the behavior-contract semver for `kind: session_write`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	SessionWriteManifestVersion = "1.0.0"

	// SessionWriteManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: session_write` at the time of last codegen.
	SessionWriteManifestFingerprint = "7baeee65fb5f3c5fd03f59ad418cd07981e440f539f67908e4818593a2564b92"

	// SleepManifestVersion is the behavior-contract semver for `kind: sleep`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	SleepManifestVersion = "1.0.0"

	// SleepManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: sleep` at the time of last codegen.
	SleepManifestFingerprint = "25bdeda8fedd3f09762bd08000e79e7f3ce7779095e0e9bbfdd5a230d4594668"

	// SubagentDispatchManifestVersion is the behavior-contract semver for `kind: subagent_dispatch`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	SubagentDispatchManifestVersion = "1.0.0"

	// SubagentDispatchManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: subagent_dispatch` at the time of last codegen.
	SubagentDispatchManifestFingerprint = "9fe5268825a7e13803c67ae41fed8c8772ab24ff3b77b375afc32dbe905dba54"

	// ToolManifestVersion is the behavior-contract semver for `kind: tool`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ToolManifestVersion = "1.0.0"

	// ToolManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: tool` at the time of last codegen.
	ToolManifestFingerprint = "6f9afff3678d82e94df4d153ecc89e5013618c3982e1d21cb1345737fc5771a1"

	// ToolDispatchManifestVersion is the behavior-contract semver for `kind: tool_dispatch`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	ToolDispatchManifestVersion = "1.0.0"

	// ToolDispatchManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: tool_dispatch` at the time of last codegen.
	ToolDispatchManifestFingerprint = "96f930e3d83024600dea2135bbe86bfb420f93f71ac4444fc9bced20aebaa4a2"

	// TraceWriteManifestVersion is the behavior-contract semver for `kind: trace_write`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	TraceWriteManifestVersion = "1.0.0"

	// TraceWriteManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: trace_write` at the time of last codegen.
	TraceWriteManifestFingerprint = "aec377e60bf6c2af721edeaa53a9affe8c0c95ae368c55b597bb13189342ecd9"

	// TransformManifestVersion is the behavior-contract semver for `kind: transform`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	TransformManifestVersion = "1.0.0"

	// TransformManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: transform` at the time of last codegen.
	TransformManifestFingerprint = "305066e444747f884601026ec5ff42aac80ff1622ede63bcd1eae9407b290c5f"

	// WriteFileManifestVersion is the behavior-contract semver for `kind: write_file`.
	// Bump this in the manifest's `manifest_version:` field when any
	// behavior-affecting field changes (ports, attrs, budget).
	WriteFileManifestVersion = "1.0.0"

	// WriteFileManifestFingerprint is the sha256 of the behavior-affecting
	// subset of `kind: write_file` at the time of last codegen.
	WriteFileManifestFingerprint = "e030b2fc61b4d92966b7d1c142412e7663fc54445a0770da48c3f2ee2399971f"
)

// allGeneratedManifestVersions maps the on-the-wire kind string to the
// manifest version baked in at codegen time. Used by CheckManifestDrift
// to look up the live version without a switch statement.
var allGeneratedManifestVersions = map[string]string{
	"activity":          ActivityManifestVersion,
	"approval":          ApprovalManifestVersion,
	"artifact":          ArtifactManifestVersion,
	"ask":               AskManifestVersion,
	"attachment":        AttachmentManifestVersion,
	"branch":            BranchManifestVersion,
	"checkpoint":        CheckpointManifestVersion,
	"compact":           CompactManifestVersion,
	"corpus_read":       CorpusReadManifestVersion,
	"corpus_write":      CorpusWriteManifestVersion,
	"decision":          DecisionManifestVersion,
	"escalate":          EscalateManifestVersion,
	"history_read":      HistoryReadManifestVersion,
	"join":              JoinManifestVersion,
	"loop":              LoopManifestVersion,
	"memory":            MemoryManifestVersion,
	"merge":             MergeManifestVersion,
	"model":             ModelManifestVersion,
	"parallel":          ParallelManifestVersion,
	"planner":           PlannerManifestVersion,
	"read_bash_output":  ReadBashOutputManifestVersion,
	"read_file":         ReadFileManifestVersion,
	"reflect":           ReflectManifestVersion,
	"retry":             RetryManifestVersion,
	"review":            ReviewManifestVersion,
	"session_write":     SessionWriteManifestVersion,
	"sleep":             SleepManifestVersion,
	"subagent_dispatch": SubagentDispatchManifestVersion,
	"tool":              ToolManifestVersion,
	"tool_dispatch":     ToolDispatchManifestVersion,
	"trace_write":       TraceWriteManifestVersion,
	"transform":         TransformManifestVersion,
	"write_file":        WriteFileManifestVersion,
}
