// Code generated by agentgraph/nodes/cmd/gen; DO NOT EDIT.

// This file is auto-generated by core/agentgraph/nodes/cmd/gen.
// Do not hand-edit; run `go generate ./...` from the repo
// root to refresh.

package agentgraph

// No callable kinds in the catalog yet. Once WP04 lands the kind
// manifests, this file will declare:
//   - NodeKind<X> constants (one per callable kind)
//   - AllNodeKindsGen slice
//   - decodeAttrsGen / defaultAttrsForGen dispatchers
//   - ResolvedManifests registry populated at init
//
// The empty-catalog state is intentional: WP02 ships the codegen
// tool + CI gate; WP04 ships the kind manifests that populate the
// generated output.
