// Command gen-served-topics emits frontend/src/lib/servedStreamTopics.gen.ts
// from the canonical passthroughTopics slice defined in
// core/serve/wsstream.go (read via the exported serve.PassthroughTopics()
// accessor).
//
// It is invoked via:
//
//	go generate ./core/serve/...
//
// which is declared in core/serve/topics_gen.go. The generator is
// byte-equal idempotent — running it twice produces the same output.
//
// # Why this exists (findings #63 / #62)
//
// Before this generator, the set of topics forwarded to served-mode
// clients was maintained BY HAND in three places: passthroughTopics
// (here), SERVED_STREAM_TOPICS (frontend/src/lib/harnessClient.ts) and a
// third hand-copied mirror in a frontend test
// (harnessClient.wp06Overlay.test.ts's EXPECTED_GO_PASSTHROUGH_TOPICS).
// mcp:health-changed went missing from all three at once and stayed
// missing because the only cross-check (wsstream_topics_parity_test.go)
// compared the Go list to the TS list — both of which were wrong the
// same way. This generator collapses the count to one authored copy:
// passthroughTopics in wsstream.go. Everything else is derived.
//
// The emitted file carries a "Code generated … DO NOT EDIT." header so
// editors and CI tools skip it. The CI parity gate in
// scripts/ci/check-codegen.sh re-runs the generator and fails if the
// committed servedStreamTopics.gen.ts deviates from the freshly-generated
// one.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kameas-ai/kenaz-harness/core/serve"
)

const generatedHeader = "// Code generated by core/serve/cmd/gen-served-topics; DO NOT EDIT."

func main() {
	out := flag.String("out", "frontend/src/lib/servedStreamTopics.gen.ts", "output file path (relative to repo root or absolute)")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintf(os.Stderr, "gen-served-topics: %v\n", err)
		os.Exit(1)
	}
}

func run(outPath string) error {
	topics := serve.PassthroughTopics()
	if len(topics) == 0 {
		return fmt.Errorf("serve.PassthroughTopics() returned empty slice — check core/serve/wsstream.go's passthroughTopics")
	}

	content := generate(topics)

	// Resolve the output path. When invoked via go generate the working
	// directory is core/serve/ (the package directory), so relative paths
	// must walk up to reach the repo root.
	if !filepath.IsAbs(outPath) {
		repoRoot, err := findRepoRoot()
		if err != nil {
			// Fall back: two levels up from core/serve/ → repo root.
			repoRoot = filepath.Join("..", "..")
		}
		outPath = filepath.Join(repoRoot, outPath)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(outPath), err)
	}

	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("gen-served-topics: wrote %s (%d topics)\n", outPath, len(topics))
	return nil
}

// generate builds the TypeScript file content from the topic list. Order
// is preserved from passthroughTopics (not sorted) so the generated
// file's diff mirrors the Go source's diff when a topic is added.
func generate(topics []string) string {
	var b bytes.Buffer

	fmt.Fprintf(&b, "%s\n", generatedHeader)
	fmt.Fprintf(&b, "// Source: core/serve/wsstream.go passthroughTopics (via serve.PassthroughTopics())\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// This is the single source of truth for which bus topics core/serve\n")
	fmt.Fprintf(&b, "// forwards to a served-mode (workbench) client verbatim. See\n")
	fmt.Fprintf(&b, "// core/serve/wsstream.go's PassthroughTopics() doc comment for the full\n")
	fmt.Fprintf(&b, "// history (findings #63 / #62 — this file used to be a hand-maintained\n")
	fmt.Fprintf(&b, "// copy that drifted).\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// To regenerate:\n")
	fmt.Fprintf(&b, "//   go generate ./core/serve/...\n")
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "export const SERVED_STREAM_TOPICS = [\n")

	for _, t := range topics {
		fmt.Fprintf(&b, "  %s,\n", quote(t))
	}

	fmt.Fprintf(&b, "] as const;\n")

	return b.String()
}

// quote wraps s in single quotes, escaping any embedded single quotes.
func quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "\\'") + "'"
}

// findRepoRoot walks the directory tree upwards from the current working
// directory looking for a go.mod file. Returns the directory that contains
// go.mod, or an error if not found within 10 levels.
func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for i := 0; i < 10; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("go.mod not found in any parent directory")
}
