#!/usr/bin/env bash
# wire-golden-drift-report.sh — emit the markdown drift report (WP08)
#
# Called by .github/workflows/wire-golden-live.yml after the refresh step.
# Writes docs/wire-golden-drift.md and pushes it to the rolling
# wire-golden-drift branch so the report is always reachable via git.
#
# Environment variables consumed:
#   DRIFT_OUTCOME     — one of: no-drift | response-drift | request-regression | skipped
#   AUTO_PR_URL       — set when drift_outcome=response-drift
#   REGRESSION_PR_URL — set when drift_outcome=request-regression
#   DRY_RUN           — when "true", write the file but do not push
#   GH_TOKEN          — GitHub token (for git push)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_FILE="$REPO_ROOT/docs/wire-golden-drift.md"
DRIFT_BRANCH="wire-golden-drift"
DATE_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
DATE_SHORT="$(date -u +%Y-%m-%d)"

OUTCOME="${DRIFT_OUTCOME:-unknown}"
AUTO_PR="${AUTO_PR_URL:-}"
REG_PR="${REGRESSION_PR_URL:-}"

# ---- build per-adapter summary table ---------------------------------------

# Determine which adapters ran (keys were set).
ALL_ADAPTERS=(anthropic openai openrouter bedrock)
declare -a ADAPTER_ROWS=()

for adapter in "${ALL_ADAPTERS[@]}"; do
  upper="${adapter^^}"
  key_var="TEST_${upper}_KEY"
  key_val="${!key_var:-}"

  if [ -z "$key_val" ]; then
    ADAPTER_ROWS+=("| \`$adapter\` | skipped (no key) | — |")
  else
    # Check if this adapter's fixture changed.
    adapter_golden="$REPO_ROOT/testdata/wire_golden/$adapter"
    changed="$(git diff HEAD --name-only -- "$adapter_golden" 2>/dev/null || true)"
    staged="$(git diff --cached --name-only -- "$adapter_golden" 2>/dev/null || true)"
    all_changed="$(printf '%s\n%s' "$changed" "$staged" | sort -u | grep -v '^$' || true)"

    if [ -z "$all_changed" ]; then
      ADAPTER_ROWS+=("| \`$adapter\` | no drift | — |")
    else
      req_changed="$(echo "$all_changed" | grep 'request\.json' || true)"
      resp_changed="$(echo "$all_changed" | grep 'response\.sse' || true)"
      changed_count="$(echo "$all_changed" | wc -l | tr -d ' ')"

      if [ -n "$req_changed" ]; then
        ADAPTER_ROWS+=("| \`$adapter\` | **request-side regression** | $changed_count file(s) changed |")
      elif [ -n "$resp_changed" ]; then
        ADAPTER_ROWS+=("| \`$adapter\` | response drift | $changed_count fixture(s) updated |")
      else
        ADAPTER_ROWS+=("| \`$adapter\` | unexpected changes | $changed_count file(s) |")
      fi
    fi
  fi
done

# ---- compose the report -----------------------------------------------------

{
  echo "# Wire-golden live-tier drift report"
  echo ""
  echo "> Auto-generated by \`wire-golden-live.yml\`. Do not edit by hand."
  echo "> Last updated: $DATE_UTC"
  echo ""
  echo "## Run outcome: \`$OUTCOME\`"
  echo ""

  case "$OUTCOME" in
    no-drift)
      echo "No fixture drift detected. All locked-tier goldens match real upstream APIs."
      ;;
    response-drift)
      echo "Provider-side fields drifted (finish-reason vocabulary, metadata fields, etc.)."
      echo "Response fixtures were refreshed and an auto-PR was opened."
      if [ -n "$AUTO_PR" ]; then
        echo ""
        echo "**Auto-PR**: $AUTO_PR"
      fi
      ;;
    request-regression)
      echo "> **Action required:** one or more provider APIs rejected our request body."
      echo "> This is a hard regression. See the regression PR for details."
      if [ -n "$REG_PR" ]; then
        echo ""
        echo "**Regression PR**: $REG_PR"
      fi
      ;;
    skipped)
      echo "No provider keys were set. Configure \`WIRE_GOLDEN_*_KEY\` Actions secrets"
      echo "to enable live-tier fixture refresh."
      ;;
    *)
      echo "Unknown outcome: \`$OUTCOME\`. Check the workflow run for details."
      ;;
  esac

  echo ""
  echo "## Per-adapter summary"
  echo ""
  echo "| Adapter | Status | Notes |"
  echo "|---------|--------|-------|"
  for row in "${ADAPTER_ROWS[@]}"; do
    echo "$row"
  done

  echo ""
  echo "## How to read this report"
  echo ""
  echo "| Status | Meaning | Action |"
  echo "|--------|---------|--------|"
  echo "| no drift | Locked-tier fixtures match upstream | None |"
  echo "| response drift | Provider changed a response field | Auto-PR refreshes \`response.sse\` |"
  echo "| request-side regression | Provider rejected our request | See regression PR, fix serialisation |"
  echo "| skipped (no key) | Secret not configured | Set \`WIRE_GOLDEN_<ADAPTER>_KEY\` |"
  echo ""
  echo "See [docs/test-coverage-policy.md](test-coverage-policy.md) for the full"
  echo "two-tier fixture model and contributor rules."
  echo ""
  echo "---"
  echo "_Updated automatically on each nightly \`wire-golden-live\` run._"
} > "$REPORT_FILE"

echo "[drift-report] wrote $REPORT_FILE"

# ---- push to rolling branch -------------------------------------------------

if [ "${DRY_RUN:-false}" = "true" ]; then
  echo "[drift-report] DRY_RUN=true — report written but not pushed."
  exit 0
fi

git config user.email "wire-golden-bot@kameas.ai"
git config user.name  "wire-golden-bot"

# Use the drift-only branch so this commit does not pollute the main or
# the auto-PR branch.
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

# Stash the report file, switch to the drift branch, apply, push, return.
git stash push --include-untracked -- "$REPORT_FILE" 2>/dev/null || true

git checkout -B "$DRIFT_BRANCH" origin/main 2>/dev/null || git checkout -B "$DRIFT_BRANCH"

git stash pop 2>/dev/null || true

# Only push if there's actually a change.
if git diff --quiet -- "$REPORT_FILE" && git diff --cached --quiet -- "$REPORT_FILE"; then
  echo "[drift-report] report unchanged — no push needed."
else
  git add -- "$REPORT_FILE"
  git commit -m "docs(wire-golden): drift report $DATE_SHORT ($OUTCOME)"
  git push --force origin "$DRIFT_BRANCH"
  echo "[drift-report] pushed to $DRIFT_BRANCH."
fi

# Return to the original branch so subsequent steps work.
git checkout "$CURRENT_BRANCH" 2>/dev/null || true
