/**
 * sanitize — DOMPurify wrapper with per-renderer profiles.
 *
 * Usage:
 *   sanitize(html)                  // default profile (GFM)
 *   sanitize(html, 'katex')         // allows KaTeX class names + MathML
 *   sanitize(html, 'mermaid-svg')   // allows SVG, forbids <foreignObject>
 *
 * Security boundary: every path through MarkdownBlock.vue must call
 * sanitize before inserting into v-html. DOMPurify is the load-bearing
 * XSS guard — never bypass it.
 */
import DOMPurify from 'dompurify';

export type SanitizeProfile = 'default' | 'katex' | 'mermaid-svg';

type DomPurifyConfig = Parameters<typeof DOMPurify.sanitize>[1];

/** Tags DOMPurify allows in its default set that we always keep. */
const BASE_CONFIG: DomPurifyConfig = {
  ADD_ATTR: [
    'target',
    'rel',
    'class',
    'data-md-block',
    'data-md-mention',
    'data-lang',
    'data-source-b64',
  ],
  // F-005 (v0.17.0 security audit): block inline style attributes on all
  // sanitized HTML. DOMPurify's default allowlist includes `style` on
  // standard elements (<span>, <p>, …); leaving it allowed lets LLM-
  // controlled CSS inject phishing overlays / exfil via background-image.
  // FORBID_ATTR overrides ADD_ATTR so SVG profiles that add `style` back
  // (mermaid output) are also blocked here — accept the trade-off; the
  // safe rendering path is class names from tokens.css, not inline CSS.
  FORBID_ATTR: ['style'],
};

/**
 * KaTeX profile: extend the base config to allow MathML elements and
 * the CSS class names KaTeX emits. This is the curated allowlist
 * published in https://katex.org/docs/security.html — key tags are
 * <math>, <mrow>, <mi>, <mo>, <mtext>, <msup>, <msub>, <mfrac>,
 * <munder>, <mover>, <mspace>, <mtable>, <mtr>, <mtd>  etc, all
 * wrapped in <span class="katex*"> containers.
 */
const KATEX_EXTRA_TAGS = [
  'math',
  'maction',
  'maligngroup',
  'malignmark',
  'menclose',
  'merror',
  'mfenced',
  'mfrac',
  'mi',
  'mlongdiv',
  'mmultiscripts',
  'mo',
  'mover',
  'mpadded',
  'mphantom',
  'mroot',
  'mrow',
  'ms',
  'mscarries',
  'mscarry',
  'msgroup',
  'msline',
  'mspace',
  'msqrt',
  'msrow',
  'mstack',
  'mstyle',
  'msub',
  'msup',
  'msubsup',
  'mtable',
  'mtd',
  'mtext',
  'mtr',
  'munder',
  'munderover',
  'semantics',
  'annotation',
];

const KATEX_EXTRA_ATTRS = [
  'columnalign',
  'columnlines',
  'columnspacing',
  'displaystyle',
  'fence',
  'linebreak',
  'lspace',
  'mathvariant',
  'maxsize',
  'minsize',
  'movablelimits',
  'rspace',
  'rowlines',
  'rowspacing',
  'scriptlevel',
  'separator',
  'stretchy',
  'symmetric',
  'width',
  'xmlns',
];

/** Mermaid-SVG profile: allow SVG elements; forbid <foreignObject>. */
const SVG_EXTRA_TAGS = [
  'svg',
  'animate',
  'animatetransform',
  'circle',
  'clippath',
  'defs',
  'desc',
  'ellipse',
  'feblend',
  'fecolormatrix',
  'fecomponenttransfer',
  'fecomposite',
  'feconvolvematrix',
  'fediffuselighting',
  'fedisplacementmap',
  'feflood',
  'fegaussianblur',
  'feimage',
  'femerge',
  'femergenode',
  'femorphology',
  'feoffset',
  'fepointlight',
  'fespecularlighting',
  'fespotlight',
  'fetile',
  'feturbulence',
  'filter',
  'g',
  'image',
  'line',
  'lineargradient',
  'marker',
  'mask',
  'metadata',
  'path',
  'pattern',
  'polygon',
  'polyline',
  'radialgradient',
  'rect',
  'stop',
  'style',
  'switch',
  'symbol',
  'text',
  'textpath',
  'title',
  'tspan',
  'use',
  'view',
];

const SVG_EXTRA_ATTRS = [
  'accent-height',
  'accumulate',
  'additive',
  'alignment-baseline',
  'ascent',
  'attributename',
  'attributetype',
  'azimuth',
  'basefrequency',
  'baseline-shift',
  'begin',
  'bias',
  'by',
  'calcmode',
  'clip',
  'clip-path',
  'clip-rule',
  'color',
  'color-interpolation',
  'color-interpolation-filters',
  'color-rendering',
  'cx',
  'cy',
  'd',
  'dx',
  'dy',
  'diffuseconstant',
  'direction',
  'display',
  'divisor',
  'dur',
  'edgemode',
  'elevation',
  'end',
  'fill',
  'fill-opacity',
  'fill-rule',
  'filter',
  'filterres',
  'filterunits',
  'flood-color',
  'flood-opacity',
  'font-family',
  'font-size',
  'font-size-adjust',
  'font-stretch',
  'font-style',
  'font-variant',
  'font-weight',
  'fx',
  'fy',
  'g1',
  'g2',
  'glyph-name',
  'glyphref',
  'gradientunits',
  'gradienttransform',
  'height',
  'href',
  'id',
  'image-rendering',
  'in',
  'in2',
  'k',
  'k1',
  'k2',
  'k3',
  'k4',
  'kerning',
  'keypoints',
  'keysplines',
  'keytimes',
  'lang',
  'lengthadjust',
  'letter-spacing',
  'kernelmatrix',
  'kernelunitlength',
  'lighting-color',
  'limitingconeangle',
  'local',
  'marker-end',
  'marker-mid',
  'marker-start',
  'markerheight',
  'markerunits',
  'markerwidth',
  'maskcontentunits',
  'maskunits',
  'max',
  'mask',
  'media',
  'method',
  'mode',
  'min',
  'name',
  'numoctaves',
  'offset',
  'operator',
  'opacity',
  'order',
  'orient',
  'orientation',
  'origin',
  'overflow',
  'paint-order',
  'path',
  'pathlength',
  'patterncontentunits',
  'patterntransform',
  'patternunits',
  'points',
  'pointsatx',
  'pointsaty',
  'pointsatz',
  'preservealpha',
  'preserveaspectratio',
  'primitiveunits',
  'r',
  'rx',
  'ry',
  'radius',
  'refx',
  'refy',
  'repeatcount',
  'repeatdur',
  'restart',
  'result',
  'rotate',
  'scale',
  'seed',
  'shape-rendering',
  'specularconstant',
  'specularexponent',
  'spreadmethod',
  'startoffset',
  'stddeviation',
  'stitchtiles',
  'stop-color',
  'stop-opacity',
  'stroke',
  'stroke-dasharray',
  'stroke-dashoffset',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-miterlimit',
  'stroke-opacity',
  'stroke-width',
  'style',
  'surfacescale',
  'systemlanguage',
  'tabindex',
  'targetx',
  'targety',
  'transform',
  'transform-origin',
  'text-anchor',
  'text-decoration',
  'text-rendering',
  'textlength',
  'type',
  'u1',
  'u2',
  'unicode',
  'values',
  'viewbox',
  'visibility',
  'version',
  'vert-adv-y',
  'vert-origin-x',
  'vert-origin-y',
  'width',
  'word-spacing',
  'wrap',
  'writing-mode',
  'xchannelselector',
  'ychannelselector',
  'x',
  'x1',
  'x2',
  'xmlns',
  'y',
  'y1',
  'y2',
  'z',
];

export function sanitize(html: string, profile: SanitizeProfile = 'default'): string {
  if (profile === 'katex') {
    return DOMPurify.sanitize(html, {
      ...BASE_CONFIG,
      ADD_TAGS: KATEX_EXTRA_TAGS,
      ADD_ATTR: [...(BASE_CONFIG!.ADD_ATTR as string[]), ...KATEX_EXTRA_ATTRS],
      RETURN_DOM_FRAGMENT: false,
      RETURN_DOM: false,
    }) as string;
  }

  if (profile === 'mermaid-svg') {
    return DOMPurify.sanitize(html, {
      ...BASE_CONFIG,
      ADD_TAGS: SVG_EXTRA_TAGS,
      ADD_ATTR: [...(BASE_CONFIG!.ADD_ATTR as string[]), ...SVG_EXTRA_ATTRS],
      FORBID_TAGS: ['foreignObject', 'script', 'iframe'],
      RETURN_DOM_FRAGMENT: false,
      RETURN_DOM: false,
    }) as string;
  }

  // default — GFM HTML only
  return DOMPurify.sanitize(html, {
    ...BASE_CONFIG,
    RETURN_DOM_FRAGMENT: false,
    RETURN_DOM: false,
  }) as string;
}
