// Package upgradesnap implements the normalised text dump / materialise
// helpers behind the per-tag upgrade snapshot chain
// (upgrade-path-coverage-01PMUG01, spec.md §5).
//
// Both directions run entirely over database/sql + modernc.org/sqlite —
// no shelling out to sqlite3(1) (spec §4, "self-hosted runner rules
// bind": the CI image does not guarantee that binary exists).
//
// Dump produces a deterministic, diffable SQL text: schema DDL grouped
// in a dependency-safe write order and sorted by (type, name) within
// each group, then INSERT statements for every real table's data, rows
// sorted by primary key. harness_meta.install_id and every applied_at
// column are replaced with fixed literals so two runs against
// differently-timed databases produce byte-identical text; content_hash
// is kept verbatim because VerifyLedger compares it against the
// registered migration's hash (spec §4) and a snapshot that silently
// rewrote it would hide a real hash mismatch instead of catching one.
//
// Materialize replays that text into a fresh database. Schema
// statements are grouped and re-ordered internally (tables, then
// virtual tables, then indexes, then triggers) regardless of the order
// they appear in the dump text, because SQLite requires an index's or
// trigger's target table to already exist — CREATE TABLE's own forward
// FK references do not have that restriction, which is what makes the
// (type, name) write order (index < table < trigger, alphabetically)
// safe to use for the FILE without being safe to REPLAY literally.
// Data INSERTs run inside one write transaction with
// PRAGMA defer_foreign_keys=ON, so the insertion order within that
// transaction does not have to be topological — only the deferred
// check at COMMIT has to pass, and it does because every row dumped
// came from a database that already satisfied its own FKs.
package upgradesnap

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// FixedInstallID and FixedTimestamp are the literals every normalised
// dump carries in place of the real install_id / applied_at / (for
// harness_meta only) created_at values, which are stamped fresh on
// every Open() and would otherwise make two dumps of an
// otherwise-identical database differ byte-for-byte.
const (
	FixedInstallID = "upgrade-snapshot-fixed-install-id"
	FixedTimestamp = "1970-01-01T00:00:00Z"
)

// ftsShadowPrefixes lists the fts5 virtual tables in the schema. Their
// shadow tables (<name>_data, _idx, _docsize, _config) are SQLite-
// managed storage for the index, not source-of-truth data — excluded
// entirely from the dump. The virtual table itself IS included in the
// schema section (so Materialize recreates it) but never in the data
// section: repopulating session_messages replays the AFTER INSERT
// triggers, which repopulate the FTS index as a side effect.
var ftsVirtualTables = map[string]bool{
	"messages_fts": true,
}

func isFTSShadow(name string) bool {
	for v := range ftsVirtualTables {
		if name != v && strings.HasPrefix(name, v+"_") {
			return true
		}
	}
	return false
}

type schemaObject struct {
	typ  string // "table" | "index" | "trigger"
	name string
	sql  string
}

func (o schemaObject) isVirtualTable() bool {
	return o.typ == "table" && strings.Contains(strings.ToUpper(o.sql), "VIRTUAL TABLE")
}

// Dump reads every schema object and every table's row data from db and
// returns the normalised text form described in the package doc.
func Dump(ctx context.Context, db *sql.DB) (string, error) {
	objs, err := readSchema(ctx, db)
	if err != nil {
		return "", fmt.Errorf("upgradesnap: read schema: %w", err)
	}

	var b strings.Builder
	b.WriteString("-- upgrade-snapshot dump. Generated by core/storage/sqlite/upgradesnap.\n")
	b.WriteString("-- Normalised: install_id and every applied_at are fixed literals;\n")
	b.WriteString("-- content_hash is verbatim (load-bearing, see VerifyLedger).\n")
	b.WriteString("-- DO NOT HAND-EDIT. Regenerate with scripts/ci/upgrade-snapshot.sh.\n\n")

	b.WriteString("-- === SCHEMA (sorted by type, name) ===\n\n")
	for _, o := range objs {
		if o.typ == "table" && isFTSShadow(o.name) {
			continue
		}
		stmt := strings.TrimSpace(o.sql)
		if !strings.HasSuffix(stmt, ";") {
			stmt += ";"
		}
		b.WriteString(stmt)
		b.WriteString("\n\n")
	}

	b.WriteString("-- === DATA (sorted by table name, rows sorted by primary key) ===\n\n")
	for _, o := range objs {
		if o.typ != "table" || o.isVirtualTable() || isFTSShadow(o.name) {
			continue
		}
		if o.name == "sqlite_sequence" {
			continue
		}
		stmts, err := dumpTableData(ctx, db, o.name)
		if err != nil {
			return "", fmt.Errorf("upgradesnap: dump data for %s: %w", o.name, err)
		}
		for _, s := range stmts {
			b.WriteString(s)
			b.WriteString("\n")
		}
		if len(stmts) > 0 {
			b.WriteString("\n")
		}
	}

	return b.String(), nil
}

func readSchema(ctx context.Context, db *sql.DB) ([]schemaObject, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT type, name, sql FROM sqlite_master
		WHERE sql IS NOT NULL AND type IN ('table','index','trigger')
		  AND name NOT LIKE 'sqlite_%'
		ORDER BY type, name
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []schemaObject
	for rows.Next() {
		var o schemaObject
		if err := rows.Scan(&o.typ, &o.name, &o.sql); err != nil {
			return nil, err
		}
		out = append(out, o)
	}
	return out, rows.Err()
}

// primaryKeyColumns returns the table's PK columns in declared order, or
// nil if the table has no explicit PK (INTEGER PRIMARY KEY / composite
// PRIMARY KEY both surface via pragma_table_info.pk > 0).
func primaryKeyColumns(ctx context.Context, db *sql.DB, table string) ([]string, error) {
	rows, err := db.QueryContext(ctx, `SELECT name, pk FROM pragma_table_info(?) WHERE pk > 0 ORDER BY pk`, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var cols []string
	for rows.Next() {
		var name string
		var pk int
		if err := rows.Scan(&name, &pk); err != nil {
			return nil, err
		}
		cols = append(cols, name)
	}
	return cols, rows.Err()
}

func allColumns(ctx context.Context, db *sql.DB, table string) ([]string, error) {
	rows, err := db.QueryContext(ctx, `SELECT name FROM pragma_table_info(?)`, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var cols []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		cols = append(cols, name)
	}
	return cols, rows.Err()
}

func dumpTableData(ctx context.Context, db *sql.DB, table string) ([]string, error) {
	cols, err := allColumns(ctx, db, table)
	if err != nil {
		return nil, err
	}
	if len(cols) == 0 {
		return nil, nil
	}
	pk, err := primaryKeyColumns(ctx, db, table)
	if err != nil {
		return nil, err
	}
	orderBy := "rowid"
	if len(pk) > 0 {
		orderBy = strings.Join(quoteIdents(pk), ", ")
	}

	query := fmt.Sprintf("SELECT %s FROM %s ORDER BY %s", strings.Join(quoteIdents(cols), ", "), quoteIdent(table), orderBy)
	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var stmts []string
	for rows.Next() {
		vals := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return nil, err
		}
		normalizeRow(table, cols, vals)
		stmts = append(stmts, buildInsert(table, cols, vals))
	}
	return stmts, rows.Err()
}

// normalizeRow replaces install_id / applied_at (any table) and
// harness_meta.created_at with fixed literals in place.
func normalizeRow(table string, cols []string, vals []any) {
	for i, c := range cols {
		switch {
		case c == "install_id", c == "applied_at":
			vals[i] = FixedInstallID
			if c == "applied_at" {
				vals[i] = FixedTimestamp
			}
		case table == "harness_meta" && c == "created_at":
			vals[i] = FixedTimestamp
		}
	}
}

func buildInsert(table string, cols []string, vals []any) string {
	var b strings.Builder
	fmt.Fprintf(&b, "INSERT INTO %s (%s) VALUES (", quoteIdent(table), strings.Join(quoteIdents(cols), ", "))
	for i, v := range vals {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(sqlLiteral(v))
	}
	b.WriteString(");")
	return b.String()
}

func sqlLiteral(v any) string {
	if v == nil {
		return "NULL"
	}
	switch t := v.(type) {
	case int64:
		return strconv.FormatInt(t, 10)
	case float64:
		return strconv.FormatFloat(t, 'g', -1, 64)
	case []byte:
		return quoteString(string(t))
	case string:
		return quoteString(t)
	case bool:
		if t {
			return "1"
		}
		return "0"
	default:
		return quoteString(fmt.Sprint(t))
	}
}

func quoteString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func quoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

func quoteIdents(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = quoteIdent(s)
	}
	return out
}

var beginWordRe = regexp.MustCompile(`(?i)\bBEGIN\b`)
var endWordRe = regexp.MustCompile(`(?i)\bEND\b`)

// splitStatements splits a SQL script on top-level semicolons that end
// a statement, tolerant of statements already terminated with '\n'
// after ';'. It does not understand quoted strings containing ';' —
// dumps produced by this package never emit one (SQL string literals
// here are the values Dump encodes, none of which are re-embedded with
// a raw, unescaped ';' followed by more SQL on the same logical
// statement), and the schema DDL this repo's migrations register is
// verified (by hash.go's own splitter, used elsewhere) not to need it.
//
// TRIGGER BODIES ARE THE ONE EXCEPTION. `CREATE TRIGGER ... BEGIN ...
// END` bodies contain their own internal, statement-ending semicolons
// (this repo's FTS trigger bodies run 1-2 INSERT statements each — see
// core/session/migrations_search_fts.go /
// migrations_search_fts_tool_rows.go). A naive per-line ';'-terminator
// would cut a single CREATE TRIGGER statement into fragments and choke
// on a lone "END;". BEGIN/END are tracked as a depth counter (word-
// boundary matched, case-insensitive) and a ';' only closes a
// statement when depth is back to zero.
func splitStatements(script string) []string {
	var out []string
	var cur strings.Builder
	depth := 0
	for _, line := range strings.Split(script, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "--") {
			if depth == 0 {
				continue
			}
		}
		cur.WriteString(line)
		cur.WriteByte('\n')
		depth += len(beginWordRe.FindAllString(trimmed, -1)) - len(endWordRe.FindAllString(trimmed, -1))
		if depth < 0 {
			depth = 0
		}
		if depth == 0 && strings.HasSuffix(trimmed, ";") {
			out = append(out, strings.TrimSpace(cur.String()))
			cur.Reset()
		}
	}
	if strings.TrimSpace(cur.String()) != "" {
		out = append(out, strings.TrimSpace(cur.String()))
	}
	return out
}

// Materialize replays dumpText (or a raw seed.sql — same statement
// shape) into db. Schema statements are grouped and reordered so
// indexes/triggers always run after their target table exists; data
// statements all run inside one transaction with
// PRAGMA defer_foreign_keys=ON so their file order does not have to be
// topological (see package doc).
func Materialize(ctx context.Context, db *sql.DB, dumpText string) error {
	stmts := splitStatements(dumpText)

	var tables, virtualTables, indexes, triggers, data []string
	for _, s := range stmts {
		upper := strings.ToUpper(strings.TrimSpace(s))
		switch {
		case strings.HasPrefix(upper, "CREATE VIRTUAL TABLE"):
			virtualTables = append(virtualTables, s)
		case strings.HasPrefix(upper, "CREATE TABLE"):
			tables = append(tables, s)
		case strings.HasPrefix(upper, "CREATE INDEX"), strings.HasPrefix(upper, "CREATE UNIQUE INDEX"):
			indexes = append(indexes, s)
		case strings.HasPrefix(upper, "CREATE TRIGGER"):
			triggers = append(triggers, s)
		case strings.HasPrefix(upper, "INSERT INTO"):
			data = append(data, s)
		default:
			return fmt.Errorf("upgradesnap: materialize: unrecognised statement kind: %s", firstLine(s))
		}
	}

	for _, group := range [][]string{tables, virtualTables, indexes, triggers} {
		for _, s := range group {
			if _, err := db.ExecContext(ctx, s); err != nil {
				return fmt.Errorf("upgradesnap: materialize schema %q: %w", firstLine(s), err)
			}
		}
	}

	if len(data) == 0 {
		return nil
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("upgradesnap: materialize: begin data tx: %w", err)
	}
	if _, err := tx.ExecContext(ctx, "PRAGMA defer_foreign_keys=ON"); err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("upgradesnap: materialize: defer_foreign_keys: %w", err)
	}
	for _, s := range data {
		if _, err := tx.ExecContext(ctx, s); err != nil {
			_ = tx.Rollback()
			return fmt.Errorf("upgradesnap: materialize data %q: %w", firstLine(s), err)
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("upgradesnap: materialize: commit data: %w", err)
	}
	return nil
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	if len(s) > 120 {
		s = s[:120] + "..."
	}
	return s
}

// TableSnapshot is a row count plus a content digest for one table,
// PK-sorted so the digest is independent of physical insertion or
// storage order (a DROP/RENAME rebuild like migrations 0304/0327/0332
// must not change it even though it recreates the table underneath).
type TableSnapshot struct {
	RowCount int
	Digest   string // sha256 of the same normalised INSERT text Dump would emit for this table
}

// ListDataTables returns every real, non-shadow, non-virtual table name
// in db, sorted — the same population Dump's data section iterates.
// Used by callers (upgrade_path_test.go, the WP03 populated-table
// tests) that need to snapshot "every table" generically rather than
// hardcode a list that will drift from the schema.
func ListDataTables(ctx context.Context, db *sql.DB) ([]string, error) {
	objs, err := readSchema(ctx, db)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, o := range objs {
		if o.typ != "table" || o.isVirtualTable() || isFTSShadow(o.name) || o.name == "sqlite_sequence" {
			continue
		}
		out = append(out, o.name)
	}
	sort.Strings(out)
	return out, nil
}

// Snapshot computes a TableSnapshot for table.
func Snapshot(ctx context.Context, db *sql.DB, table string) (TableSnapshot, error) {
	stmts, err := dumpTableData(ctx, db, table)
	if err != nil {
		return TableSnapshot{}, err
	}
	h := sha256.New()
	for _, s := range stmts {
		h.Write([]byte(s))
		h.Write([]byte{'\n'})
	}
	return TableSnapshot{RowCount: len(stmts), Digest: hex.EncodeToString(h.Sum(nil))}, nil
}

// SnapshotAll computes a TableSnapshot for every table ListDataTables
// returns.
func SnapshotAll(ctx context.Context, db *sql.DB) (map[string]TableSnapshot, error) {
	tables, err := ListDataTables(ctx, db)
	if err != nil {
		return nil, err
	}
	out := make(map[string]TableSnapshot, len(tables))
	for _, t := range tables {
		s, err := Snapshot(ctx, db, t)
		if err != nil {
			return nil, fmt.Errorf("snapshot %s: %w", t, err)
		}
		out[t] = s
	}
	return out, nil
}

// SortedSnapshotTags returns tag directory names sorted by semantic
// version ascending. Used by the table-driven test to enumerate
// testdata/upgrade/* deterministically and by the generator to find the
// latest committed snapshot to replay from.
func SortedSnapshotTags(tags []string) []string {
	out := append([]string(nil), tags...)
	sort.Slice(out, func(i, j int) bool { return semverLess(out[i], out[j]) })
	return out
}

// IsSnapshotTag reports whether name is a well-formed "vX.Y.Z" snapshot
// directory name. scripts/ci/upgrade-snapshot.sh also accepts the literal
// "HEAD" to preview an unreleased tree, and that output is a scratch
// artefact — the table-driven upgrade-path test uses this to refuse to
// treat a leftover preview directory as a real chain entry.
func IsSnapshotTag(name string) bool {
	_, ok := parseSemver(name)
	return ok
}

// semverLess compares "vX.Y.Z" tags numerically. Falls back to a
// lexical compare for anything that doesn't parse (defensive; every
// directory under testdata/upgrade/ is expected to be a plain vX.Y.Z
// tag name).
func semverLess(a, b string) bool {
	pa, oka := parseSemver(a)
	pb, okb := parseSemver(b)
	if !oka || !okb {
		return a < b
	}
	for i := 0; i < 3; i++ {
		if pa[i] != pb[i] {
			return pa[i] < pb[i]
		}
	}
	return false
}

func parseSemver(s string) ([3]int, bool) {
	var out [3]int
	s = strings.TrimPrefix(s, "v")
	parts := strings.SplitN(s, ".", 3)
	if len(parts) != 3 {
		return out, false
	}
	for i, p := range parts {
		n, err := strconv.Atoi(p)
		if err != nil {
			return out, false
		}
		out[i] = n
	}
	return out, true
}
