// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function A2A_ListCards() {
  return window['go']['rpc']['Bindings']['A2A_ListCards']();
}

export function A2A_StartStream() {
  return window['go']['rpc']['Bindings']['A2A_StartStream']();
}

export function A2A_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['A2A_StopStream'](arg1);
}

export function AppInfo() {
  return window['go']['rpc']['Bindings']['AppInfo']();
}

export function Attachments_Add(arg1) {
  return window['go']['rpc']['Bindings']['Attachments_Add'](arg1);
}

export function Attachments_List(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Attachments_List'](arg1, arg2);
}

export function Attachments_ListResolved(arg1) {
  return window['go']['rpc']['Bindings']['Attachments_ListResolved'](arg1);
}

export function Attachments_Refresh(arg1) {
  return window['go']['rpc']['Bindings']['Attachments_Refresh'](arg1);
}

export function Attachments_Remove(arg1) {
  return window['go']['rpc']['Bindings']['Attachments_Remove'](arg1);
}

export function Attachments_Reorder(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Attachments_Reorder'](arg1, arg2, arg3);
}

export function Audit_ListEntries(arg1) {
  return window['go']['rpc']['Bindings']['Audit_ListEntries'](arg1);
}

export function Audit_StartStream(arg1) {
  return window['go']['rpc']['Bindings']['Audit_StartStream'](arg1);
}

export function Audit_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Audit_StopStream'](arg1);
}

export function Audit_VerifyEntry(arg1) {
  return window['go']['rpc']['Bindings']['Audit_VerifyEntry'](arg1);
}

export function Bundle_Get(arg1) {
  return window['go']['rpc']['Bindings']['Bundle_Get'](arg1);
}

export function Bundle_List() {
  return window['go']['rpc']['Bindings']['Bundle_List']();
}

export function Context_List() {
  return window['go']['rpc']['Bindings']['Context_List']();
}

export function Context_StartStream() {
  return window['go']['rpc']['Bindings']['Context_StartStream']();
}

export function Context_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Context_StopStream'](arg1);
}

export function Contexts_CreateFolder(arg1) {
  return window['go']['rpc']['Bindings']['Contexts_CreateFolder'](arg1);
}

export function Contexts_Delete(arg1) {
  return window['go']['rpc']['Bindings']['Contexts_Delete'](arg1);
}

export function Contexts_Get(arg1) {
  return window['go']['rpc']['Bindings']['Contexts_Get'](arg1);
}

export function Contexts_List() {
  return window['go']['rpc']['Bindings']['Contexts_List']();
}

export function Contexts_ListAll() {
  return window['go']['rpc']['Bindings']['Contexts_ListAll']();
}

export function Contexts_RecentlyApplied(arg1) {
  return window['go']['rpc']['Bindings']['Contexts_RecentlyApplied'](arg1);
}

export function Contexts_Rename(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Contexts_Rename'](arg1, arg2);
}

export function Contexts_RootPath() {
  return window['go']['rpc']['Bindings']['Contexts_RootPath']();
}

export function Contexts_Save(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Contexts_Save'](arg1, arg2);
}

export function Diag_LogClientEvent(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Diag_LogClientEvent'](arg1, arg2, arg3);
}

export function Diag_LogPath() {
  return window['go']['rpc']['Bindings']['Diag_LogPath']();
}

export function Hooks_Add(arg1) {
  return window['go']['rpc']['Bindings']['Hooks_Add'](arg1);
}

export function Hooks_AvailableBuiltins() {
  return window['go']['rpc']['Bindings']['Hooks_AvailableBuiltins']();
}

export function Hooks_Get(arg1) {
  return window['go']['rpc']['Bindings']['Hooks_Get'](arg1);
}

export function Hooks_InstallStarterMemory() {
  return window['go']['rpc']['Bindings']['Hooks_InstallStarterMemory']();
}

export function Hooks_List() {
  return window['go']['rpc']['Bindings']['Hooks_List']();
}

export function Hooks_Remove(arg1) {
  return window['go']['rpc']['Bindings']['Hooks_Remove'](arg1);
}

export function Hooks_RemoveStarterMemory() {
  return window['go']['rpc']['Bindings']['Hooks_RemoveStarterMemory']();
}

export function Hooks_Update(arg1) {
  return window['go']['rpc']['Bindings']['Hooks_Update'](arg1);
}

export function LLM_AddProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_AddProvider'](arg1);
}

export function LLM_ListModels(arg1, arg2) {
  return window['go']['rpc']['Bindings']['LLM_ListModels'](arg1, arg2);
}

export function LLM_ListProviders() {
  return window['go']['rpc']['Bindings']['LLM_ListProviders']();
}

export function LLM_RemoveProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_RemoveProvider'](arg1);
}

export function LLM_ResolveConfirm(arg1, arg2) {
  return window['go']['rpc']['Bindings']['LLM_ResolveConfirm'](arg1, arg2);
}

export function LLM_StartStream(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['LLM_StartStream'](arg1, arg2, arg3);
}

export function LLM_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['LLM_StopStream'](arg1);
}

export function LLM_TestProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_TestProvider'](arg1);
}

export function LLM_UpdateProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_UpdateProvider'](arg1);
}

export function LoadRoute() {
  return window['go']['rpc']['Bindings']['LoadRoute']();
}

export function LoadTheme() {
  return window['go']['rpc']['Bindings']['LoadTheme']();
}

export function LogRouteChange(arg1, arg2) {
  return window['go']['rpc']['Bindings']['LogRouteChange'](arg1, arg2);
}

export function MCP_ListServers() {
  return window['go']['rpc']['Bindings']['MCP_ListServers']();
}

export function MCP_StartStream(arg1) {
  return window['go']['rpc']['Bindings']['MCP_StartStream'](arg1);
}

export function MCP_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['MCP_StopStream'](arg1);
}

export function Memory_Forget(arg1) {
  return window['go']['rpc']['Bindings']['Memory_Forget'](arg1);
}

export function Memory_ListChunks(arg1) {
  return window['go']['rpc']['Bindings']['Memory_ListChunks'](arg1);
}

export function Memory_PromoteScope(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Memory_PromoteScope'](arg1, arg2, arg3);
}

export function Memory_RememberMessage(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Memory_RememberMessage'](arg1, arg2, arg3);
}

export function Policy_Explain(arg1) {
  return window['go']['rpc']['Bindings']['Policy_Explain'](arg1);
}

export function Policy_StartStream() {
  return window['go']['rpc']['Bindings']['Policy_StartStream']();
}

export function Policy_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Policy_StopStream'](arg1);
}

export function Projects_AddSession(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_AddSession'](arg1, arg2);
}

export function Projects_Create(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_Create'](arg1, arg2);
}

export function Projects_Delete(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_Delete'](arg1, arg2);
}

export function Projects_Get(arg1) {
  return window['go']['rpc']['Bindings']['Projects_Get'](arg1);
}

export function Projects_List() {
  return window['go']['rpc']['Bindings']['Projects_List']();
}

export function Projects_ListSessions(arg1) {
  return window['go']['rpc']['Bindings']['Projects_ListSessions'](arg1);
}

export function Projects_RemoveSession(arg1) {
  return window['go']['rpc']['Bindings']['Projects_RemoveSession'](arg1);
}

export function Projects_Rename(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_Rename'](arg1, arg2);
}

export function Projects_UpdateDescription(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_UpdateDescription'](arg1, arg2);
}

export function SaveRoute(arg1) {
  return window['go']['rpc']['Bindings']['SaveRoute'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['rpc']['Bindings']['SaveTheme'](arg1);
}

export function Sessions_AppendMessage(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Sessions_AppendMessage'](arg1, arg2, arg3);
}

export function Sessions_Create(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Create'](arg1);
}

export function Sessions_Delete(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Delete'](arg1);
}

export function Sessions_Get(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Get'](arg1);
}

export function Sessions_List() {
  return window['go']['rpc']['Bindings']['Sessions_List']();
}

export function Sessions_ListMessages(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_ListMessages'](arg1);
}

export function Sessions_LoadDraft(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_LoadDraft'](arg1);
}

export function Sessions_MoveToProject(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_MoveToProject'](arg1, arg2);
}

export function Sessions_Rename(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_Rename'](arg1, arg2);
}

export function Sessions_Reorder(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Reorder'](arg1);
}

export function Sessions_SaveDraft(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_SaveDraft'](arg1, arg2);
}

export function Sessions_SetSystemPrompt(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Sessions_SetSystemPrompt'](arg1, arg2, arg3);
}

export function Sessions_StartStream(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_StartStream'](arg1);
}

export function Sessions_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_StopStream'](arg1);
}

export function SetContext(arg1) {
  return window['go']['rpc']['Bindings']['SetContext'](arg1);
}

export function SetSettingsStore(arg1) {
  return window['go']['rpc']['Bindings']['SetSettingsStore'](arg1);
}

export function Settings_Get() {
  return window['go']['rpc']['Bindings']['Settings_Get']();
}

export function Settings_GetConfirmEach() {
  return window['go']['rpc']['Bindings']['Settings_GetConfirmEach']();
}

export function Settings_GetMemory() {
  return window['go']['rpc']['Bindings']['Settings_GetMemory']();
}

export function Settings_Set(arg1) {
  return window['go']['rpc']['Bindings']['Settings_Set'](arg1);
}

export function Settings_SetConfirmEach(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetConfirmEach'](arg1);
}

export function Settings_SetMemory(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetMemory'](arg1);
}

export function Shell_OpenInOSBrowser(arg1) {
  return window['go']['rpc']['Bindings']['Shell_OpenInOSBrowser'](arg1);
}

export function ShellStatus() {
  return window['go']['rpc']['Bindings']['ShellStatus']();
}

export function Tools_ForgetRecipeKey(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Tools_ForgetRecipeKey'](arg1, arg2);
}

export function Tools_InstallRecipe(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Tools_InstallRecipe'](arg1, arg2, arg3);
}

export function Tools_ListRecipes() {
  return window['go']['rpc']['Bindings']['Tools_ListRecipes']();
}

export function Tools_RecipeConfig(arg1) {
  return window['go']['rpc']['Bindings']['Tools_RecipeConfig'](arg1);
}

export function Tools_RecipeStatus(arg1) {
  return window['go']['rpc']['Bindings']['Tools_RecipeStatus'](arg1);
}

export function Tools_UninstallRecipe(arg1) {
  return window['go']['rpc']['Bindings']['Tools_UninstallRecipe'](arg1);
}

export function Trust_GetSecretReference(arg1) {
  return window['go']['rpc']['Bindings']['Trust_GetSecretReference'](arg1);
}

export function Trust_ListSecretReferences() {
  return window['go']['rpc']['Bindings']['Trust_ListSecretReferences']();
}

export function Workflow_ListJobs() {
  return window['go']['rpc']['Bindings']['Workflow_ListJobs']();
}

export function Workflow_StartStream() {
  return window['go']['rpc']['Bindings']['Workflow_StartStream']();
}

export function Workflow_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Workflow_StopStream'](arg1);
}
