// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function A2A_ListCards() {
  return window['go']['rpc']['Bindings']['A2A_ListCards']();
}

export function A2A_StartStream() {
  return window['go']['rpc']['Bindings']['A2A_StartStream']();
}

export function A2A_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['A2A_StopStream'](arg1);
}

export function ACP_Dispatch(arg1, arg2) {
  return window['go']['rpc']['Bindings']['ACP_Dispatch'](arg1, arg2);
}

export function ACP_GetTrace(arg1) {
  return window['go']['rpc']['Bindings']['ACP_GetTrace'](arg1);
}

export function ACP_ListPeers() {
  return window['go']['rpc']['Bindings']['ACP_ListPeers']();
}

export function ACP_ListTraces(arg1) {
  return window['go']['rpc']['Bindings']['ACP_ListTraces'](arg1);
}

export function ACP_RevokePeer(arg1) {
  return window['go']['rpc']['Bindings']['ACP_RevokePeer'](arg1);
}

export function ACP_TrustPeer(arg1) {
  return window['go']['rpc']['Bindings']['ACP_TrustPeer'](arg1);
}

export function Agents_DeleteProfile(arg1) {
  return window['go']['rpc']['Bindings']['Agents_DeleteProfile'](arg1);
}

export function Agents_ListProfiles() {
  return window['go']['rpc']['Bindings']['Agents_ListProfiles']();
}

export function Agents_LoadProfile(arg1) {
  return window['go']['rpc']['Bindings']['Agents_LoadProfile'](arg1);
}

export function Agents_SaveProfile(arg1) {
  return window['go']['rpc']['Bindings']['Agents_SaveProfile'](arg1);
}

export function AppInfo() {
  return window['go']['rpc']['Bindings']['AppInfo']();
}

export function Artifacts_Delete(arg1) {
  return window['go']['rpc']['Bindings']['Artifacts_Delete'](arg1);
}

export function Artifacts_Get(arg1) {
  return window['go']['rpc']['Bindings']['Artifacts_Get'](arg1);
}

export function Artifacts_List(arg1) {
  return window['go']['rpc']['Bindings']['Artifacts_List'](arg1);
}

export function Artifacts_Promote(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Artifacts_Promote'](arg1, arg2, arg3);
}

export function Artifacts_SaveAs(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Artifacts_SaveAs'](arg1, arg2);
}

export function Attachments_Add(arg1) {
  return window['go']['rpc']['Bindings']['Attachments_Add'](arg1);
}

export function Attachments_AddMedia(arg1) {
  return window['go']['rpc']['Bindings']['Attachments_AddMedia'](arg1);
}

export function Attachments_List(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Attachments_List'](arg1, arg2);
}

export function Attachments_ListResolved(arg1) {
  return window['go']['rpc']['Bindings']['Attachments_ListResolved'](arg1);
}

export function Attachments_Refresh(arg1) {
  return window['go']['rpc']['Bindings']['Attachments_Refresh'](arg1);
}

export function Attachments_Remove(arg1) {
  return window['go']['rpc']['Bindings']['Attachments_Remove'](arg1);
}

export function Attachments_Reorder(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Attachments_Reorder'](arg1, arg2, arg3);
}

export function Audit_BulkPurge(arg1) {
  return window['go']['rpc']['Bindings']['Audit_BulkPurge'](arg1);
}

export function Audit_DeleteQuery(arg1) {
  return window['go']['rpc']['Bindings']['Audit_DeleteQuery'](arg1);
}

export function Audit_Export(arg1) {
  return window['go']['rpc']['Bindings']['Audit_Export'](arg1);
}

export function Audit_Filter(arg1) {
  return window['go']['rpc']['Bindings']['Audit_Filter'](arg1);
}

export function Audit_ListEntries(arg1) {
  return window['go']['rpc']['Bindings']['Audit_ListEntries'](arg1);
}

export function Audit_ListSavedQueries() {
  return window['go']['rpc']['Bindings']['Audit_ListSavedQueries']();
}

export function Audit_SaveQuery(arg1) {
  return window['go']['rpc']['Bindings']['Audit_SaveQuery'](arg1);
}

export function Audit_StartStream(arg1) {
  return window['go']['rpc']['Bindings']['Audit_StartStream'](arg1);
}

export function Audit_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Audit_StopStream'](arg1);
}

export function Audit_VerifyChain(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Audit_VerifyChain'](arg1, arg2);
}

export function Audit_VerifyEntry(arg1) {
  return window['go']['rpc']['Bindings']['Audit_VerifyEntry'](arg1);
}

export function Bash_Exec(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Bash_Exec'](arg1, arg2);
}

export function BootHealth_Get() {
  return window['go']['rpc']['Bindings']['BootHealth_Get']();
}

export function Branches_Abandon(arg1) {
  return window['go']['rpc']['Bindings']['Branches_Abandon'](arg1);
}

export function Branches_CommitReintegration(arg1) {
  return window['go']['rpc']['Bindings']['Branches_CommitReintegration'](arg1);
}

export function Branches_Create(arg1) {
  return window['go']['rpc']['Bindings']['Branches_Create'](arg1);
}

export function Branches_GetStatus(arg1) {
  return window['go']['rpc']['Bindings']['Branches_GetStatus'](arg1);
}

export function Branches_List(arg1) {
  return window['go']['rpc']['Bindings']['Branches_List'](arg1);
}

export function Branches_ListWithBranchTree(arg1) {
  return window['go']['rpc']['Bindings']['Branches_ListWithBranchTree'](arg1);
}

export function Branches_Merge(arg1) {
  return window['go']['rpc']['Bindings']['Branches_Merge'](arg1);
}

export function Branches_ProposeReintegrationSummary(arg1) {
  return window['go']['rpc']['Bindings']['Branches_ProposeReintegrationSummary'](arg1);
}

export function Branches_RecommendModel(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Branches_RecommendModel'](arg1, arg2, arg3);
}

export function Branches_SetAdvisorDismissed(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Branches_SetAdvisorDismissed'](arg1, arg2);
}

export function Bundle_Get(arg1) {
  return window['go']['rpc']['Bindings']['Bundle_Get'](arg1);
}

export function Bundle_Install(arg1) {
  return window['go']['rpc']['Bindings']['Bundle_Install'](arg1);
}

export function Bundle_List() {
  return window['go']['rpc']['Bindings']['Bundle_List']();
}

export function Bundle_Remove(arg1) {
  return window['go']['rpc']['Bindings']['Bundle_Remove'](arg1);
}

export function Catalog_Install(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Catalog_Install'](arg1, arg2);
}

export function Catalog_Installed() {
  return window['go']['rpc']['Bindings']['Catalog_Installed']();
}

export function Catalog_List(arg1) {
  return window['go']['rpc']['Bindings']['Catalog_List'](arg1);
}

export function Catalog_Publish(arg1) {
  return window['go']['rpc']['Bindings']['Catalog_Publish'](arg1);
}

export function Catalog_Uninstall(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Catalog_Uninstall'](arg1, arg2, arg3);
}

export function CedarPolicy_Delete(arg1) {
  return window['go']['rpc']['Bindings']['CedarPolicy_Delete'](arg1);
}

export function CedarPolicy_Get(arg1) {
  return window['go']['rpc']['Bindings']['CedarPolicy_Get'](arg1);
}

export function CedarPolicy_InstallTemplate(arg1, arg2) {
  return window['go']['rpc']['Bindings']['CedarPolicy_InstallTemplate'](arg1, arg2);
}

export function CedarPolicy_ListPlanModeActions() {
  return window['go']['rpc']['Bindings']['CedarPolicy_ListPlanModeActions']();
}

export function CedarPolicy_ListPolicies() {
  return window['go']['rpc']['Bindings']['CedarPolicy_ListPolicies']();
}

export function CedarPolicy_RecentDecisions(arg1) {
  return window['go']['rpc']['Bindings']['CedarPolicy_RecentDecisions'](arg1);
}

export function CedarPolicy_ReloadPolicies() {
  return window['go']['rpc']['Bindings']['CedarPolicy_ReloadPolicies']();
}

export function CedarPolicy_ResolvePropose(arg1, arg2) {
  return window['go']['rpc']['Bindings']['CedarPolicy_ResolvePropose'](arg1, arg2);
}

export function CedarPolicy_RevokeSnippet(arg1) {
  return window['go']['rpc']['Bindings']['CedarPolicy_RevokeSnippet'](arg1);
}

export function CedarPolicy_Save(arg1, arg2) {
  return window['go']['rpc']['Bindings']['CedarPolicy_Save'](arg1, arg2);
}

export function CedarPolicy_Validate(arg1) {
  return window['go']['rpc']['Bindings']['CedarPolicy_Validate'](arg1);
}

export function CedarPolicy_WriteSnippet(arg1, arg2) {
  return window['go']['rpc']['Bindings']['CedarPolicy_WriteSnippet'](arg1, arg2);
}

export function Cedar_PublishToTeam(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Cedar_PublishToTeam'](arg1, arg2);
}

export function Compaction_GetConfig(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Compaction_GetConfig'](arg1, arg2);
}

export function Compaction_GetEffective(arg1) {
  return window['go']['rpc']['Bindings']['Compaction_GetEffective'](arg1);
}

export function Compaction_GetTierExplain() {
  return window['go']['rpc']['Bindings']['Compaction_GetTierExplain']();
}

export function Compaction_ListCustomStrategies() {
  return window['go']['rpc']['Bindings']['Compaction_ListCustomStrategies']();
}

export function Compaction_SetConfig(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Compaction_SetConfig'](arg1, arg2, arg3);
}

export function Compaction_TriggerManual(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Compaction_TriggerManual'](arg1, arg2);
}

export function Compliance_ArchiveNow() {
  return window['go']['rpc']['Bindings']['Compliance_ArchiveNow']();
}

export function Compliance_SetRetention(arg1) {
  return window['go']['rpc']['Bindings']['Compliance_SetRetention'](arg1);
}

export function Compliance_Status() {
  return window['go']['rpc']['Bindings']['Compliance_Status']();
}

export function Config_GetFlags() {
  return window['go']['rpc']['Bindings']['Config_GetFlags']();
}

export function ContextBootstrap_Health() {
  return window['go']['rpc']['Bindings']['ContextBootstrap_Health']();
}

export function ContextBootstrap_Resume(arg1) {
  return window['go']['rpc']['Bindings']['ContextBootstrap_Resume'](arg1);
}

export function ContextBootstrap_Start(arg1) {
  return window['go']['rpc']['Bindings']['ContextBootstrap_Start'](arg1);
}

export function ContextBootstrap_Status() {
  return window['go']['rpc']['Bindings']['ContextBootstrap_Status']();
}

export function ContextSync_ApplyRecoveryCode(arg1) {
  return window['go']['rpc']['Bindings']['ContextSync_ApplyRecoveryCode'](arg1);
}

export function ContextSync_GenerateRecoveryCode() {
  return window['go']['rpc']['Bindings']['ContextSync_GenerateRecoveryCode']();
}

export function Context_List() {
  return window['go']['rpc']['Bindings']['Context_List']();
}

export function Context_StartStream() {
  return window['go']['rpc']['Bindings']['Context_StartStream']();
}

export function Context_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Context_StopStream'](arg1);
}

export function Contexts_AttachModule(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Contexts_AttachModule'](arg1, arg2, arg3);
}

export function Contexts_ContextExport(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Contexts_ContextExport'](arg1, arg2);
}

export function Contexts_ContextPromote(arg1) {
  return window['go']['rpc']['Bindings']['Contexts_ContextPromote'](arg1);
}

export function Contexts_ContextPublish(arg1) {
  return window['go']['rpc']['Bindings']['Contexts_ContextPublish'](arg1);
}

export function Contexts_ContextSearch(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Contexts_ContextSearch'](arg1, arg2, arg3);
}

export function Contexts_ContextSyncStatus() {
  return window['go']['rpc']['Bindings']['Contexts_ContextSyncStatus']();
}

export function Contexts_CreateFolder(arg1) {
  return window['go']['rpc']['Bindings']['Contexts_CreateFolder'](arg1);
}

export function Contexts_Delete(arg1) {
  return window['go']['rpc']['Bindings']['Contexts_Delete'](arg1);
}

export function Contexts_Get(arg1) {
  return window['go']['rpc']['Bindings']['Contexts_Get'](arg1);
}

export function Contexts_List() {
  return window['go']['rpc']['Bindings']['Contexts_List']();
}

export function Contexts_ListAll() {
  return window['go']['rpc']['Bindings']['Contexts_ListAll']();
}

export function Contexts_RecentlyApplied(arg1) {
  return window['go']['rpc']['Bindings']['Contexts_RecentlyApplied'](arg1);
}

export function Contexts_Rename(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Contexts_Rename'](arg1, arg2);
}

export function Contexts_RootPath() {
  return window['go']['rpc']['Bindings']['Contexts_RootPath']();
}

export function Contexts_Save(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Contexts_Save'](arg1, arg2);
}

export function Corpus_CreateCorpus(arg1) {
  return window['go']['rpc']['Bindings']['Corpus_CreateCorpus'](arg1);
}

export function Corpus_DeleteCorpus(arg1) {
  return window['go']['rpc']['Bindings']['Corpus_DeleteCorpus'](arg1);
}

export function Corpus_GetCorpus(arg1) {
  return window['go']['rpc']['Bindings']['Corpus_GetCorpus'](arg1);
}

export function Corpus_IngestPath(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Corpus_IngestPath'](arg1, arg2, arg3);
}

export function Corpus_JobStatus(arg1) {
  return window['go']['rpc']['Bindings']['Corpus_JobStatus'](arg1);
}

export function Corpus_ListChunks(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Corpus_ListChunks'](arg1, arg2);
}

export function Corpus_ListCorpora(arg1) {
  return window['go']['rpc']['Bindings']['Corpus_ListCorpora'](arg1);
}

export function Corpus_ListFiles(arg1) {
  return window['go']['rpc']['Bindings']['Corpus_ListFiles'](arg1);
}

export function Corpus_Retrieve(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Corpus_Retrieve'](arg1, arg2);
}

export function Diag_LogClientEvent(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Diag_LogClientEvent'](arg1, arg2, arg3);
}

export function Diag_LogPath() {
  return window['go']['rpc']['Bindings']['Diag_LogPath']();
}

export function Dials_BumpAndResume(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Dials_BumpAndResume'](arg1, arg2);
}

export function Dials_Get(arg1) {
  return window['go']['rpc']['Bindings']['Dials_Get'](arg1);
}

export function Dials_GetEffective(arg1, arg2, arg3, arg4) {
  return window['go']['rpc']['Bindings']['Dials_GetEffective'](arg1, arg2, arg3, arg4);
}

export function Dials_Set(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Dials_Set'](arg1, arg2);
}

export function Elicit_AnswerDeferred(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Elicit_AnswerDeferred'](arg1, arg2);
}

export function Elicit_ListPending() {
  return window['go']['rpc']['Bindings']['Elicit_ListPending']();
}

export function Elicit_RegisterDeferred(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Elicit_RegisterDeferred'](arg1, arg2);
}

export function Elicit_SubmitAnswer(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Elicit_SubmitAnswer'](arg1, arg2, arg3);
}

export function Elicit_SubmitWizardStep(arg1, arg2, arg3, arg4) {
  return window['go']['rpc']['Bindings']['Elicit_SubmitWizardStep'](arg1, arg2, arg3, arg4);
}

export function Fleet_GetTelemetryConsent() {
  return window['go']['rpc']['Bindings']['Fleet_GetTelemetryConsent']();
}

export function Fleet_SetTelemetryConsent(arg1) {
  return window['go']['rpc']['Bindings']['Fleet_SetTelemetryConsent'](arg1);
}

export function Graph_CancelRun(arg1) {
  return window['go']['rpc']['Bindings']['Graph_CancelRun'](arg1);
}

export function Graph_DeleteGraph(arg1) {
  return window['go']['rpc']['Bindings']['Graph_DeleteGraph'](arg1);
}

export function Graph_GetRunStatus(arg1) {
  return window['go']['rpc']['Bindings']['Graph_GetRunStatus'](arg1);
}

export function Graph_GetRunTrace(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Graph_GetRunTrace'](arg1, arg2);
}

export function Graph_ListGraphs(arg1) {
  return window['go']['rpc']['Bindings']['Graph_ListGraphs'](arg1);
}

export function Graph_LoadGraph(arg1) {
  return window['go']['rpc']['Bindings']['Graph_LoadGraph'](arg1);
}

export function Graph_Resume(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Graph_Resume'](arg1, arg2);
}

export function Graph_SaveGraph(arg1) {
  return window['go']['rpc']['Bindings']['Graph_SaveGraph'](arg1);
}

export function Graph_StartRun(arg1) {
  return window['go']['rpc']['Bindings']['Graph_StartRun'](arg1);
}

export function Graph_Validate(arg1) {
  return window['go']['rpc']['Bindings']['Graph_Validate'](arg1);
}

export function Handoff_Accept(arg1) {
  return window['go']['rpc']['Bindings']['Handoff_Accept'](arg1);
}

export function Handoff_Inbox() {
  return window['go']['rpc']['Bindings']['Handoff_Inbox']();
}

export function Handoff_ListTeam() {
  return window['go']['rpc']['Bindings']['Handoff_ListTeam']();
}

export function Handoff_Share(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Handoff_Share'](arg1, arg2);
}

export function Hooks_Add(arg1) {
  return window['go']['rpc']['Bindings']['Hooks_Add'](arg1);
}

export function Hooks_AvailableBuiltins() {
  return window['go']['rpc']['Bindings']['Hooks_AvailableBuiltins']();
}

export function Hooks_DryRun(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Hooks_DryRun'](arg1, arg2);
}

export function Hooks_Get(arg1) {
  return window['go']['rpc']['Bindings']['Hooks_Get'](arg1);
}

export function Hooks_InstallStarterMemory() {
  return window['go']['rpc']['Bindings']['Hooks_InstallStarterMemory']();
}

export function Hooks_List() {
  return window['go']['rpc']['Bindings']['Hooks_List']();
}

export function Hooks_Remove(arg1) {
  return window['go']['rpc']['Bindings']['Hooks_Remove'](arg1);
}

export function Hooks_RemoveStarterMemory() {
  return window['go']['rpc']['Bindings']['Hooks_RemoveStarterMemory']();
}

export function Hooks_Update(arg1) {
  return window['go']['rpc']['Bindings']['Hooks_Update'](arg1);
}

export function LLM_AddProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_AddProvider'](arg1);
}

export function LLM_AutoConfigureLocalRuntime(arg1) {
  return window['go']['rpc']['Bindings']['LLM_AutoConfigureLocalRuntime'](arg1);
}

export function LLM_DeleteChain(arg1) {
  return window['go']['rpc']['Bindings']['LLM_DeleteChain'](arg1);
}

export function LLM_GetAttachmentLimits(arg1, arg2) {
  return window['go']['rpc']['Bindings']['LLM_GetAttachmentLimits'](arg1, arg2);
}

export function LLM_ListCustomTemplates() {
  return window['go']['rpc']['Bindings']['LLM_ListCustomTemplates']();
}

export function LLM_ListDetectedLocalRuntimes() {
  return window['go']['rpc']['Bindings']['LLM_ListDetectedLocalRuntimes']();
}

export function LLM_ListFallbackChains() {
  return window['go']['rpc']['Bindings']['LLM_ListFallbackChains']();
}

export function LLM_ListModels(arg1, arg2) {
  return window['go']['rpc']['Bindings']['LLM_ListModels'](arg1, arg2);
}

export function LLM_ListProviders() {
  return window['go']['rpc']['Bindings']['LLM_ListProviders']();
}

export function LLM_LoadChain(arg1) {
  return window['go']['rpc']['Bindings']['LLM_LoadChain'](arg1);
}

export function LLM_ProbeCustomEndpoint(arg1) {
  return window['go']['rpc']['Bindings']['LLM_ProbeCustomEndpoint'](arg1);
}

export function LLM_RecognizeTemplate(arg1) {
  return window['go']['rpc']['Bindings']['LLM_RecognizeTemplate'](arg1);
}

export function LLM_RemoveProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_RemoveProvider'](arg1);
}

export function LLM_RescanLocalRuntimes() {
  return window['go']['rpc']['Bindings']['LLM_RescanLocalRuntimes']();
}

export function LLM_ResolveConfirm(arg1, arg2) {
  return window['go']['rpc']['Bindings']['LLM_ResolveConfirm'](arg1, arg2);
}

export function LLM_ResumeAfterKeyRotation(arg1) {
  return window['go']['rpc']['Bindings']['LLM_ResumeAfterKeyRotation'](arg1);
}

export function LLM_SaveChain(arg1) {
  return window['go']['rpc']['Bindings']['LLM_SaveChain'](arg1);
}

export function LLM_StartStream(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['LLM_StartStream'](arg1, arg2, arg3);
}

export function LLM_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['LLM_StopStream'](arg1);
}

export function LLM_TestAndRotateKey(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['LLM_TestAndRotateKey'](arg1, arg2, arg3);
}

export function LLM_TestProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_TestProvider'](arg1);
}

export function LLM_TestProviderKey(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['LLM_TestProviderKey'](arg1, arg2, arg3);
}

export function LLM_UpdateProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_UpdateProvider'](arg1);
}

export function LLM_UpdateProviderCredential(arg1, arg2) {
  return window['go']['rpc']['Bindings']['LLM_UpdateProviderCredential'](arg1, arg2);
}

export function LoadRoute() {
  return window['go']['rpc']['Bindings']['LoadRoute']();
}

export function LoadTheme() {
  return window['go']['rpc']['Bindings']['LoadTheme']();
}

export function LogRouteChange(arg1, arg2) {
  return window['go']['rpc']['Bindings']['LogRouteChange'](arg1, arg2);
}

export function Logs_Tail(arg1) {
  return window['go']['rpc']['Bindings']['Logs_Tail'](arg1);
}

export function MCP_HealthSnapshot() {
  return window['go']['rpc']['Bindings']['MCP_HealthSnapshot']();
}

export function MCP_ImportClaudeDesktopConfig(arg1) {
  return window['go']['rpc']['Bindings']['MCP_ImportClaudeDesktopConfig'](arg1);
}

export function MCP_ListServers() {
  return window['go']['rpc']['Bindings']['MCP_ListServers']();
}

export function MCP_StartStream(arg1) {
  return window['go']['rpc']['Bindings']['MCP_StartStream'](arg1);
}

export function MCP_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['MCP_StopStream'](arg1);
}

export function MCP_SubscribeHealthChanges() {
  return window['go']['rpc']['Bindings']['MCP_SubscribeHealthChanges']();
}

export function MCP_TestRecipe(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['MCP_TestRecipe'](arg1, arg2, arg3);
}

export function Memory_CaptureRate() {
  return window['go']['rpc']['Bindings']['Memory_CaptureRate']();
}

export function Memory_EmbedderEligibility() {
  return window['go']['rpc']['Bindings']['Memory_EmbedderEligibility']();
}

export function Memory_EmbeddingProbe(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Memory_EmbeddingProbe'](arg1, arg2);
}

export function Memory_Forget(arg1) {
  return window['go']['rpc']['Bindings']['Memory_Forget'](arg1);
}

export function Memory_GetChunkProvenance(arg1) {
  return window['go']['rpc']['Bindings']['Memory_GetChunkProvenance'](arg1);
}

export function Memory_HealthSnapshot() {
  return window['go']['rpc']['Bindings']['Memory_HealthSnapshot']();
}

export function Memory_JournalTail(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Memory_JournalTail'](arg1, arg2, arg3);
}

export function Memory_LastRetrieval(arg1) {
  return window['go']['rpc']['Bindings']['Memory_LastRetrieval'](arg1);
}

export function Memory_ListChunks(arg1) {
  return window['go']['rpc']['Bindings']['Memory_ListChunks'](arg1);
}

export function Memory_MarkImportant(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Memory_MarkImportant'](arg1, arg2);
}

export function Memory_NarrativeFailedCount() {
  return window['go']['rpc']['Bindings']['Memory_NarrativeFailedCount']();
}

export function Memory_NarrativeFailedList() {
  return window['go']['rpc']['Bindings']['Memory_NarrativeFailedList']();
}

export function Memory_NarrativeMetricsForChunk(arg1) {
  return window['go']['rpc']['Bindings']['Memory_NarrativeMetricsForChunk'](arg1);
}

export function Memory_Pin(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Memory_Pin'](arg1, arg2);
}

export function Memory_PromoteScope(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Memory_PromoteScope'](arg1, arg2, arg3);
}

export function Memory_PrunePreview(arg1) {
  return window['go']['rpc']['Bindings']['Memory_PrunePreview'](arg1);
}

export function Memory_RememberMessage(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Memory_RememberMessage'](arg1, arg2, arg3);
}

export function Memory_ResummarizeChunk(arg1) {
  return window['go']['rpc']['Bindings']['Memory_ResummarizeChunk'](arg1);
}

export function Memory_RetryFailedNarrative(arg1) {
  return window['go']['rpc']['Bindings']['Memory_RetryFailedNarrative'](arg1);
}

export function Memory_RunPruneNow(arg1) {
  return window['go']['rpc']['Bindings']['Memory_RunPruneNow'](arg1);
}

export function Memory_TestEmbedder() {
  return window['go']['rpc']['Bindings']['Memory_TestEmbedder']();
}

export function Nodes_Catalog() {
  return window['go']['rpc']['Bindings']['Nodes_Catalog']();
}

export function Nodes_Doctor() {
  return window['go']['rpc']['Bindings']['Nodes_Doctor']();
}

export function Nodes_Get(arg1) {
  return window['go']['rpc']['Bindings']['Nodes_Get'](arg1);
}

export function Nodes_ListUserOverrides() {
  return window['go']['rpc']['Bindings']['Nodes_ListUserOverrides']();
}

export function Nodes_ReloadOverrides() {
  return window['go']['rpc']['Bindings']['Nodes_ReloadOverrides']();
}

export function Onboarding_AcceptHandoffHint(arg1) {
  return window['go']['rpc']['Bindings']['Onboarding_AcceptHandoffHint'](arg1);
}

export function Onboarding_Begin() {
  return window['go']['rpc']['Bindings']['Onboarding_Begin']();
}

export function Onboarding_Dismiss() {
  return window['go']['rpc']['Bindings']['Onboarding_Dismiss']();
}

export function Onboarding_GetHandoffHint() {
  return window['go']['rpc']['Bindings']['Onboarding_GetHandoffHint']();
}

export function Onboarding_ListStarters() {
  return window['go']['rpc']['Bindings']['Onboarding_ListStarters']();
}

export function Onboarding_RecordProgress(arg1) {
  return window['go']['rpc']['Bindings']['Onboarding_RecordProgress'](arg1);
}

export function Onboarding_RestartPhase2(arg1) {
  return window['go']['rpc']['Bindings']['Onboarding_RestartPhase2'](arg1);
}

export function Onboarding_RunBootstrap(arg1) {
  return window['go']['rpc']['Bindings']['Onboarding_RunBootstrap'](arg1);
}

export function Onboarding_State() {
  return window['go']['rpc']['Bindings']['Onboarding_State']();
}

export function Onboarding_Step(arg1) {
  return window['go']['rpc']['Bindings']['Onboarding_Step'](arg1);
}

export function Permissions_ListGrants(arg1) {
  return window['go']['rpc']['Bindings']['Permissions_ListGrants'](arg1);
}

export function Permissions_ListPending() {
  return window['go']['rpc']['Bindings']['Permissions_ListPending']();
}

export function Permissions_Resolve(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Permissions_Resolve'](arg1, arg2);
}

export function Permissions_RevokeGrant(arg1) {
  return window['go']['rpc']['Bindings']['Permissions_RevokeGrant'](arg1);
}

export function Planmode_Approve(arg1) {
  return window['go']['rpc']['Bindings']['Planmode_Approve'](arg1);
}

export function Planmode_Discard(arg1) {
  return window['go']['rpc']['Bindings']['Planmode_Discard'](arg1);
}

export function Planmode_Edit(arg1) {
  return window['go']['rpc']['Bindings']['Planmode_Edit'](arg1);
}

export function Policy_Explain(arg1) {
  return window['go']['rpc']['Bindings']['Policy_Explain'](arg1);
}

export function Policy_StartStream() {
  return window['go']['rpc']['Bindings']['Policy_StartStream']();
}

export function Policy_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Policy_StopStream'](arg1);
}

export function ProjectSync_DeleteRemote(arg1) {
  return window['go']['rpc']['Bindings']['ProjectSync_DeleteRemote'](arg1);
}

export function ProjectSync_SetArtifactClass(arg1, arg2) {
  return window['go']['rpc']['Bindings']['ProjectSync_SetArtifactClass'](arg1, arg2);
}

export function ProjectSync_Toggle(arg1, arg2) {
  return window['go']['rpc']['Bindings']['ProjectSync_Toggle'](arg1, arg2);
}

export function Projects_AddSession(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_AddSession'](arg1, arg2);
}

export function Projects_Create(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_Create'](arg1, arg2);
}

export function Projects_Delete(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_Delete'](arg1, arg2);
}

export function Projects_Get(arg1) {
  return window['go']['rpc']['Bindings']['Projects_Get'](arg1);
}

export function Projects_GetAutonomy(arg1) {
  return window['go']['rpc']['Bindings']['Projects_GetAutonomy'](arg1);
}

export function Projects_List() {
  return window['go']['rpc']['Bindings']['Projects_List']();
}

export function Projects_ListSessions(arg1) {
  return window['go']['rpc']['Bindings']['Projects_ListSessions'](arg1);
}

export function Projects_RemoveSession(arg1) {
  return window['go']['rpc']['Bindings']['Projects_RemoveSession'](arg1);
}

export function Projects_Rename(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_Rename'](arg1, arg2);
}

export function Projects_SetAutonomy(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_SetAutonomy'](arg1, arg2);
}

export function Projects_UpdateDescription(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Projects_UpdateDescription'](arg1, arg2);
}

export function SaveRoute(arg1) {
  return window['go']['rpc']['Bindings']['SaveRoute'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['rpc']['Bindings']['SaveTheme'](arg1);
}

export function ScheduledChat_Create(arg1) {
  return window['go']['rpc']['Bindings']['ScheduledChat_Create'](arg1);
}

export function ScheduledChat_Delete(arg1) {
  return window['go']['rpc']['Bindings']['ScheduledChat_Delete'](arg1);
}

export function ScheduledChat_Get(arg1) {
  return window['go']['rpc']['Bindings']['ScheduledChat_Get'](arg1);
}

export function ScheduledChat_History(arg1, arg2) {
  return window['go']['rpc']['Bindings']['ScheduledChat_History'](arg1, arg2);
}

export function ScheduledChat_List() {
  return window['go']['rpc']['Bindings']['ScheduledChat_List']();
}

export function ScheduledChat_RunNow(arg1) {
  return window['go']['rpc']['Bindings']['ScheduledChat_RunNow'](arg1);
}

export function ScheduledChat_SetEnabled(arg1, arg2) {
  return window['go']['rpc']['Bindings']['ScheduledChat_SetEnabled'](arg1, arg2);
}

export function ScheduledChat_Update(arg1) {
  return window['go']['rpc']['Bindings']['ScheduledChat_Update'](arg1);
}

export function Search_Sessions(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Search_Sessions'](arg1, arg2);
}

export function Search_Unified(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Search_Unified'](arg1, arg2);
}

export function Secrets_Expose(arg1) {
  return window['go']['rpc']['Bindings']['Secrets_Expose'](arg1);
}

export function Secrets_List() {
  return window['go']['rpc']['Bindings']['Secrets_List']();
}

export function Secrets_Revoke(arg1) {
  return window['go']['rpc']['Bindings']['Secrets_Revoke'](arg1);
}

export function Sentry_GenerateLocalReport() {
  return window['go']['rpc']['Bindings']['Sentry_GenerateLocalReport']();
}

export function Sentry_GetLastFive() {
  return window['go']['rpc']['Bindings']['Sentry_GetLastFive']();
}

export function Sentry_TestDSN(arg1) {
  return window['go']['rpc']['Bindings']['Sentry_TestDSN'](arg1);
}

export function SessionSync_DeleteRemote(arg1) {
  return window['go']['rpc']['Bindings']['SessionSync_DeleteRemote'](arg1);
}

export function SessionSync_ResumeFrom(arg1, arg2) {
  return window['go']['rpc']['Bindings']['SessionSync_ResumeFrom'](arg1, arg2);
}

export function SessionSync_Toggle(arg1, arg2) {
  return window['go']['rpc']['Bindings']['SessionSync_Toggle'](arg1, arg2);
}

export function Sessions_AppendMessage(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Sessions_AppendMessage'](arg1, arg2, arg3);
}

export function Sessions_ClearTitle(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_ClearTitle'](arg1);
}

export function Sessions_Create(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Create'](arg1);
}

export function Sessions_Delete(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Delete'](arg1);
}

export function Sessions_DeleteWithOptions(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_DeleteWithOptions'](arg1, arg2);
}

export function Sessions_Export(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_Export'](arg1, arg2);
}

export function Sessions_Get(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Get'](arg1);
}

export function Sessions_GetAutonomy(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_GetAutonomy'](arg1);
}

export function Sessions_GetUsage(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_GetUsage'](arg1);
}

export function Sessions_List() {
  return window['go']['rpc']['Bindings']['Sessions_List']();
}

export function Sessions_ListMessages(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_ListMessages'](arg1);
}

export function Sessions_ListMessagesActive(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_ListMessagesActive'](arg1);
}

export function Sessions_ListMessagesAll(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_ListMessagesAll'](arg1);
}

export function Sessions_LoadDraft(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_LoadDraft'](arg1);
}

export function Sessions_MoveToProject(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_MoveToProject'](arg1, arg2);
}

export function Sessions_Rename(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_Rename'](arg1, arg2);
}

export function Sessions_Reorder(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Reorder'](arg1);
}

export function Sessions_ResolveAutonomy(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_ResolveAutonomy'](arg1);
}

export function Sessions_ResumeMessage(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_ResumeMessage'](arg1, arg2);
}

export function Sessions_SaveAsArtifact(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['rpc']['Bindings']['Sessions_SaveAsArtifact'](arg1, arg2, arg3, arg4, arg5);
}

export function Sessions_SaveDraft(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_SaveDraft'](arg1, arg2);
}

export function Sessions_SendMessageWithBlocks(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_SendMessageWithBlocks'](arg1, arg2);
}

export function Sessions_SetAutonomy(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_SetAutonomy'](arg1, arg2);
}

export function Sessions_SetSystemPrompt(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Sessions_SetSystemPrompt'](arg1, arg2, arg3);
}

export function Sessions_StartCapture(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_StartCapture'](arg1);
}

export function Sessions_StartStream(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_StartStream'](arg1);
}

export function Sessions_StopCapture(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_StopCapture'](arg1);
}

export function Sessions_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_StopStream'](arg1);
}

export function Sessions_SuggestTitle(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_SuggestTitle'](arg1);
}

export function SetContext(arg1) {
  return window['go']['rpc']['Bindings']['SetContext'](arg1);
}

export function SetSettingsStore(arg1) {
  return window['go']['rpc']['Bindings']['SetSettingsStore'](arg1);
}

export function Settings_FleetCapabilities() {
  return window['go']['rpc']['Bindings']['Settings_FleetCapabilities']();
}

export function Settings_FleetConfigPullStatus() {
  return window['go']['rpc']['Bindings']['Settings_FleetConfigPullStatus']();
}

export function Settings_FleetHealth() {
  return window['go']['rpc']['Bindings']['Settings_FleetHealth']();
}

export function Settings_FleetLockdownStatus() {
  return window['go']['rpc']['Bindings']['Settings_FleetLockdownStatus']();
}

export function Settings_FleetProfile() {
  return window['go']['rpc']['Bindings']['Settings_FleetProfile']();
}

export function Settings_FleetRefreshCapabilities() {
  return window['go']['rpc']['Bindings']['Settings_FleetRefreshCapabilities']();
}

export function Settings_FleetRefreshIdentity() {
  return window['go']['rpc']['Bindings']['Settings_FleetRefreshIdentity']();
}

export function Settings_FleetSetTelemetryOptIn(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Settings_FleetSetTelemetryOptIn'](arg1, arg2);
}

export function Settings_FleetSignIn() {
  return window['go']['rpc']['Bindings']['Settings_FleetSignIn']();
}

export function Settings_FleetSignOut() {
  return window['go']['rpc']['Bindings']['Settings_FleetSignOut']();
}

export function Settings_FleetSignedIn() {
  return window['go']['rpc']['Bindings']['Settings_FleetSignedIn']();
}

export function Settings_FleetTelemetryOptIns() {
  return window['go']['rpc']['Bindings']['Settings_FleetTelemetryOptIns']();
}

export function Settings_Get() {
  return window['go']['rpc']['Bindings']['Settings_Get']();
}

export function Settings_GetArtifactPreview() {
  return window['go']['rpc']['Bindings']['Settings_GetArtifactPreview']();
}

export function Settings_GetAuditSettings() {
  return window['go']['rpc']['Bindings']['Settings_GetAuditSettings']();
}

export function Settings_GetAutoCaptureGeneratedImages() {
  return window['go']['rpc']['Bindings']['Settings_GetAutoCaptureGeneratedImages']();
}

export function Settings_GetAutoResumeOnKeyRotation() {
  return window['go']['rpc']['Bindings']['Settings_GetAutoResumeOnKeyRotation']();
}

export function Settings_GetAutoTitleEnabled() {
  return window['go']['rpc']['Bindings']['Settings_GetAutoTitleEnabled']();
}

export function Settings_GetAutonomy() {
  return window['go']['rpc']['Bindings']['Settings_GetAutonomy']();
}

export function Settings_GetBash() {
  return window['go']['rpc']['Bindings']['Settings_GetBash']();
}

export function Settings_GetBashAllowlistMigrated() {
  return window['go']['rpc']['Bindings']['Settings_GetBashAllowlistMigrated']();
}

export function Settings_GetCedarStrictCredentialMode() {
  return window['go']['rpc']['Bindings']['Settings_GetCedarStrictCredentialMode']();
}

export function Settings_GetEmbedderConfig() {
  return window['go']['rpc']['Bindings']['Settings_GetEmbedderConfig']();
}

export function Settings_GetFSReadEnabled() {
  return window['go']['rpc']['Bindings']['Settings_GetFSReadEnabled']();
}

export function Settings_GetFSRequestAccessEnabled() {
  return window['go']['rpc']['Bindings']['Settings_GetFSRequestAccessEnabled']();
}

export function Settings_GetFSWriteEnabled() {
  return window['go']['rpc']['Bindings']['Settings_GetFSWriteEnabled']();
}

export function Settings_GetLocalRuntimeRAMOverrideGB() {
  return window['go']['rpc']['Bindings']['Settings_GetLocalRuntimeRAMOverrideGB']();
}

export function Settings_GetMCPAutoRestart() {
  return window['go']['rpc']['Bindings']['Settings_GetMCPAutoRestart']();
}

export function Settings_GetMaxAgentTurns() {
  return window['go']['rpc']['Bindings']['Settings_GetMaxAgentTurns']();
}

export function Settings_GetMaxGeneratedImageBytes() {
  return window['go']['rpc']['Bindings']['Settings_GetMaxGeneratedImageBytes']();
}

export function Settings_GetMemory() {
  return window['go']['rpc']['Bindings']['Settings_GetMemory']();
}

export function Settings_GetMonthlyCostNotifyUSD() {
  return window['go']['rpc']['Bindings']['Settings_GetMonthlyCostNotifyUSD']();
}

export function Settings_GetMultimodalInput() {
  return window['go']['rpc']['Bindings']['Settings_GetMultimodalInput']();
}

export function Settings_GetPermissionCacheDangerousOps() {
  return window['go']['rpc']['Bindings']['Settings_GetPermissionCacheDangerousOps']();
}

export function Settings_GetPermissionMode() {
  return window['go']['rpc']['Bindings']['Settings_GetPermissionMode']();
}

export function Settings_GetPermissionsMigrationToastShown() {
  return window['go']['rpc']['Bindings']['Settings_GetPermissionsMigrationToastShown']();
}

export function Settings_GetSaveArtifactEnabled() {
  return window['go']['rpc']['Bindings']['Settings_GetSaveArtifactEnabled']();
}

export function Settings_GetShortcuts() {
  return window['go']['rpc']['Bindings']['Settings_GetShortcuts']();
}

export function Settings_GetShowPerMessageTokenMeter() {
  return window['go']['rpc']['Bindings']['Settings_GetShowPerMessageTokenMeter']();
}

export function Settings_GetTodoEnabled() {
  return window['go']['rpc']['Bindings']['Settings_GetTodoEnabled']();
}

export function Settings_GetWebFetchEnabled() {
  return window['go']['rpc']['Bindings']['Settings_GetWebFetchEnabled']();
}

export function Settings_GetWebSearch() {
  return window['go']['rpc']['Bindings']['Settings_GetWebSearch']();
}

export function Settings_Set(arg1) {
  return window['go']['rpc']['Bindings']['Settings_Set'](arg1);
}

export function Settings_SetAuditSettings(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetAuditSettings'](arg1);
}

export function Settings_SetAutoCaptureGeneratedImages(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetAutoCaptureGeneratedImages'](arg1);
}

export function Settings_SetAutoResumeOnKeyRotation(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetAutoResumeOnKeyRotation'](arg1);
}

export function Settings_SetAutoTitleEnabled(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetAutoTitleEnabled'](arg1);
}

export function Settings_SetAutonomy(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetAutonomy'](arg1);
}

export function Settings_SetBash(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetBash'](arg1);
}

export function Settings_SetBashAllowlistMigrated(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetBashAllowlistMigrated'](arg1);
}

export function Settings_SetCedarStrictCredentialMode(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetCedarStrictCredentialMode'](arg1);
}

export function Settings_SetEmbedderConfig(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Settings_SetEmbedderConfig'](arg1, arg2);
}

export function Settings_SetFSReadEnabled(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetFSReadEnabled'](arg1);
}

export function Settings_SetFSRequestAccessEnabled(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetFSRequestAccessEnabled'](arg1);
}

export function Settings_SetFSWriteEnabled(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetFSWriteEnabled'](arg1);
}

export function Settings_SetLocalRuntimeRAMOverrideGB(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetLocalRuntimeRAMOverrideGB'](arg1);
}

export function Settings_SetMCPAutoRestart(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetMCPAutoRestart'](arg1);
}

export function Settings_SetMaxAgentTurns(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetMaxAgentTurns'](arg1);
}

export function Settings_SetMaxGeneratedImageBytes(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetMaxGeneratedImageBytes'](arg1);
}

export function Settings_SetMemory(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetMemory'](arg1);
}

export function Settings_SetMonthlyCostNotifyUSD(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetMonthlyCostNotifyUSD'](arg1);
}

export function Settings_SetMultimodalInput(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetMultimodalInput'](arg1);
}

export function Settings_SetPermissionCacheDangerousOps(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetPermissionCacheDangerousOps'](arg1);
}

export function Settings_SetPermissionMode(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetPermissionMode'](arg1);
}

export function Settings_SetPermissionsMigrationToastShown(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetPermissionsMigrationToastShown'](arg1);
}

export function Settings_SetSaveArtifactEnabled(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetSaveArtifactEnabled'](arg1);
}

export function Settings_SetShortcut(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Settings_SetShortcut'](arg1, arg2);
}

export function Settings_SetShortcuts(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetShortcuts'](arg1);
}

export function Settings_SetShowPerMessageTokenMeter(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetShowPerMessageTokenMeter'](arg1);
}

export function Settings_SetTodoEnabled(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetTodoEnabled'](arg1);
}

export function Settings_SetWebFetchEnabled(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetWebFetchEnabled'](arg1);
}

export function Settings_SetWebSearch(arg1) {
  return window['go']['rpc']['Bindings']['Settings_SetWebSearch'](arg1);
}

export function ShellStatus() {
  return window['go']['rpc']['Bindings']['ShellStatus']();
}

export function Shell_OpenInOSBrowser(arg1) {
  return window['go']['rpc']['Bindings']['Shell_OpenInOSBrowser'](arg1);
}

export function Shell_PathComplete(arg1) {
  return window['go']['rpc']['Bindings']['Shell_PathComplete'](arg1);
}

export function Shell_PickFile(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Shell_PickFile'](arg1, arg2, arg3);
}

export function Shell_ReadFile(arg1) {
  return window['go']['rpc']['Bindings']['Shell_ReadFile'](arg1);
}

export function Sites_Delete(arg1) {
  return window['go']['rpc']['Bindings']['Sites_Delete'](arg1);
}

export function Sites_Deploy(arg1) {
  return window['go']['rpc']['Bindings']['Sites_Deploy'](arg1);
}

export function Sites_List() {
  return window['go']['rpc']['Bindings']['Sites_List']();
}

export function Sites_Logs(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sites_Logs'](arg1, arg2);
}

export function Sites_Status(arg1) {
  return window['go']['rpc']['Bindings']['Sites_Status'](arg1);
}

export function Slash_Execute(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Slash_Execute'](arg1, arg2);
}

export function Slash_List() {
  return window['go']['rpc']['Bindings']['Slash_List']();
}

export function Slashcmd_Delete(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Slashcmd_Delete'](arg1, arg2);
}

export function Slashcmd_Get(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Slashcmd_Get'](arg1, arg2);
}

export function Slashcmd_List(arg1) {
  return window['go']['rpc']['Bindings']['Slashcmd_List'](arg1);
}

export function Slashcmd_Run(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['rpc']['Bindings']['Slashcmd_Run'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Slashcmd_Save(arg1) {
  return window['go']['rpc']['Bindings']['Slashcmd_Save'](arg1);
}

export function Slashcmd_SkillInstall(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Slashcmd_SkillInstall'](arg1, arg2);
}

export function Slashcmd_SkillList() {
  return window['go']['rpc']['Bindings']['Slashcmd_SkillList']();
}

export function Slashcmd_SkillPublish(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Slashcmd_SkillPublish'](arg1, arg2, arg3);
}

export function Slashcmd_SkillRenameLocalTrigger(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Slashcmd_SkillRenameLocalTrigger'](arg1, arg2);
}

export function Slashcmd_SkillUninstall(arg1) {
  return window['go']['rpc']['Bindings']['Slashcmd_SkillUninstall'](arg1);
}

export function Storage_ApplyDriftFix(arg1) {
  return window['go']['rpc']['Bindings']['Storage_ApplyDriftFix'](arg1);
}

export function Storage_GetMigrationDriftReport() {
  return window['go']['rpc']['Bindings']['Storage_GetMigrationDriftReport']();
}

export function Sync_ForcePull(arg1) {
  return window['go']['rpc']['Bindings']['Sync_ForcePull'](arg1);
}

export function Sync_ForcePush(arg1) {
  return window['go']['rpc']['Bindings']['Sync_ForcePush'](arg1);
}

export function Sync_PendingMCPSecrets() {
  return window['go']['rpc']['Bindings']['Sync_PendingMCPSecrets']();
}

export function Sync_Status() {
  return window['go']['rpc']['Bindings']['Sync_Status']();
}

export function Sync_Toggle(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sync_Toggle'](arg1, arg2);
}

export function Tasks_Abort(arg1) {
  return window['go']['rpc']['Bindings']['Tasks_Abort'](arg1);
}

export function Tasks_AbortBySession(arg1) {
  return window['go']['rpc']['Bindings']['Tasks_AbortBySession'](arg1);
}

export function Tasks_Get(arg1) {
  return window['go']['rpc']['Bindings']['Tasks_Get'](arg1);
}

export function Tasks_List() {
  return window['go']['rpc']['Bindings']['Tasks_List']();
}

export function Tasks_ListBySession(arg1) {
  return window['go']['rpc']['Bindings']['Tasks_ListBySession'](arg1);
}

export function Tasks_Tail(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Tasks_Tail'](arg1, arg2);
}

export function Tools_BeginDeviceAuth(arg1) {
  return window['go']['rpc']['Bindings']['Tools_BeginDeviceAuth'](arg1);
}

export function Tools_CheckRecipePrereqs(arg1) {
  return window['go']['rpc']['Bindings']['Tools_CheckRecipePrereqs'](arg1);
}

export function Tools_ForgetRecipeKey(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Tools_ForgetRecipeKey'](arg1, arg2);
}

export function Tools_InstallRecipe(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Tools_InstallRecipe'](arg1, arg2, arg3);
}

export function Tools_ListRecipes() {
  return window['go']['rpc']['Bindings']['Tools_ListRecipes']();
}

export function Tools_PickDirectory(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Tools_PickDirectory'](arg1, arg2);
}

export function Tools_PollDeviceAuth(arg1) {
  return window['go']['rpc']['Bindings']['Tools_PollDeviceAuth'](arg1);
}

export function Tools_RecipeConfig(arg1) {
  return window['go']['rpc']['Bindings']['Tools_RecipeConfig'](arg1);
}

export function Tools_RecipeStatus(arg1) {
  return window['go']['rpc']['Bindings']['Tools_RecipeStatus'](arg1);
}

export function Tools_RequestAdditionalAllowedDir(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Tools_RequestAdditionalAllowedDir'](arg1, arg2, arg3);
}

export function Tools_SignInRecipe(arg1) {
  return window['go']['rpc']['Bindings']['Tools_SignInRecipe'](arg1);
}

export function Tools_UninstallRecipe(arg1) {
  return window['go']['rpc']['Bindings']['Tools_UninstallRecipe'](arg1);
}

export function Trust_GetSecretReference(arg1) {
  return window['go']['rpc']['Bindings']['Trust_GetSecretReference'](arg1);
}

export function Trust_ListSecretReferences() {
  return window['go']['rpc']['Bindings']['Trust_ListSecretReferences']();
}

export function Unit_ListConflicts() {
  return window['go']['rpc']['Bindings']['Unit_ListConflicts']();
}

export function Unit_PromoteAsMergeRequest(arg1, arg2, arg3, arg4) {
  return window['go']['rpc']['Bindings']['Unit_PromoteAsMergeRequest'](arg1, arg2, arg3, arg4);
}

export function Unit_ResolveEnshrine(arg1, arg2, arg3, arg4) {
  return window['go']['rpc']['Bindings']['Unit_ResolveEnshrine'](arg1, arg2, arg3, arg4);
}

export function Unit_ResolveLoadable(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Unit_ResolveLoadable'](arg1, arg2);
}

export function Unit_ResolveMerge(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Unit_ResolveMerge'](arg1, arg2);
}

export function Unit_SyncStatus() {
  return window['go']['rpc']['Bindings']['Unit_SyncStatus']();
}

export function Update_Apply() {
  return window['go']['rpc']['Bindings']['Update_Apply']();
}

export function Update_ListSkippedVersions() {
  return window['go']['rpc']['Bindings']['Update_ListSkippedVersions']();
}

export function Update_SkipVersion(arg1) {
  return window['go']['rpc']['Bindings']['Update_SkipVersion'](arg1);
}

export function Update_StartCheck() {
  return window['go']['rpc']['Bindings']['Update_StartCheck']();
}

export function Update_StartDownload() {
  return window['go']['rpc']['Bindings']['Update_StartDownload']();
}

export function Update_Status() {
  return window['go']['rpc']['Bindings']['Update_Status']();
}

export function Update_UnskipVersion(arg1) {
  return window['go']['rpc']['Bindings']['Update_UnskipVersion'](arg1);
}

export function Workflow_ListJobs() {
  return window['go']['rpc']['Bindings']['Workflow_ListJobs']();
}

export function Workflow_StartStream() {
  return window['go']['rpc']['Bindings']['Workflow_StartStream']();
}

export function Workflow_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Workflow_StopStream'](arg1);
}

export function Workflows_CancelRun(arg1) {
  return window['go']['rpc']['Bindings']['Workflows_CancelRun'](arg1);
}

export function Workflows_CatalogGet(arg1) {
  return window['go']['rpc']['Bindings']['Workflows_CatalogGet'](arg1);
}

export function Workflows_CatalogInstall(arg1) {
  return window['go']['rpc']['Bindings']['Workflows_CatalogInstall'](arg1);
}

export function Workflows_CatalogList() {
  return window['go']['rpc']['Bindings']['Workflows_CatalogList']();
}

export function Workflows_Delete(arg1) {
  return window['go']['rpc']['Bindings']['Workflows_Delete'](arg1);
}

export function Workflows_Get(arg1) {
  return window['go']['rpc']['Bindings']['Workflows_Get'](arg1);
}

export function Workflows_List() {
  return window['go']['rpc']['Bindings']['Workflows_List']();
}

export function Workflows_Run(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Workflows_Run'](arg1, arg2);
}

export function Workflows_RunNow(arg1) {
  return window['go']['rpc']['Bindings']['Workflows_RunNow'](arg1);
}

export function Workflows_Save(arg1) {
  return window['go']['rpc']['Bindings']['Workflows_Save'](arg1);
}

export function Workflows_ScheduleClear(arg1) {
  return window['go']['rpc']['Bindings']['Workflows_ScheduleClear'](arg1);
}

export function Workflows_ScheduleList() {
  return window['go']['rpc']['Bindings']['Workflows_ScheduleList']();
}

export function Workflows_ScheduleNextFire(arg1) {
  return window['go']['rpc']['Bindings']['Workflows_ScheduleNextFire'](arg1);
}

export function Workflows_ScheduleRunHistory(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Workflows_ScheduleRunHistory'](arg1, arg2);
}

export function Workflows_ScheduleSet(arg1) {
  return window['go']['rpc']['Bindings']['Workflows_ScheduleSet'](arg1);
}
