// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {acp} from '../models';
import {a2a} from '../models';
import {agents} from '../models';
import {rpc} from '../models';
import {artifacts} from '../models';
import {attachments} from '../models';
import {log} from '../models';
import {audit} from '../models';
import {branches} from '../models';
import {bundle} from '../models';
import {catalog} from '../models';
import {cedarpolicy} from '../models';
import {cedar} from '../models';
import {compliance} from '../models';
import {compaction} from '../models';
import {contextview} from '../models';
import {contexts} from '../models';
import {corpus} from '../models';
import {dials} from '../models';
import {elicit} from '../models';
import {json} from '../models';
import {agentgraph} from '../models';
import {hooks} from '../models';
import {llm} from '../models';
import {mcp} from '../models';
import {memory} from '../models';
import {nodes} from '../models';
import {onboarding} from '../models';
import {permissions} from '../models';
import {planmode} from '../models';
import {policy} from '../models';
import {projects} from '../models';
import {autonomy} from '../models';
import {scheduledchat} from '../models';
import {search} from '../models';
import {secrets} from '../models';
import {sentry} from '../models';
import {sessions} from '../models';
import {context} from '../models';
import {settings} from '../models';
import {sites} from '../models';
import {slashcmd} from '../models';
import {storage} from '../models';
import {sync} from '../models';
import {tasks} from '../models';
import {transport} from '../models';
import {tools} from '../models';
import {trust} from '../models';
import {fleet} from '../models';
import {update} from '../models';
import {workflow} from '../models';
import {workflows} from '../models';

export function A2A_ListCards():Promise<Array<a2a.Card>>;

export function A2A_StartStream():Promise<string>;

export function A2A_StopStream(arg1:string):Promise<void>;

export function ACP_Dispatch(arg1:string,arg2:string):Promise<acp.DispatchResult>;

export function ACP_GetTrace(arg1:string):Promise<acp.EnvelopeTrace>;

export function ACP_ListTraces(arg1:string):Promise<Array<acp.EnvelopeTrace>>;

export function ACP_ListPeers():Promise<Array<acp.Peer>>;

export function ACP_RevokePeer(arg1:string):Promise<void>;

export function ACP_TrustPeer(arg1:string):Promise<acp.TrustResult>;

export function Agents_DeleteProfile(arg1:string):Promise<void>;

export function Agents_ListProfiles():Promise<Array<agents.ProfileSummaryWire>>;

export function Agents_LoadProfile(arg1:string):Promise<agents.ProfileWire>;

export function Agents_SaveProfile(arg1:agents.ProfileWire):Promise<void>;

export function AppInfo():Promise<rpc.AppInfo>;

export function Artifacts_Delete(arg1:string):Promise<void>;

export function Artifacts_Get(arg1:string):Promise<artifacts.ArtifactWithBytes>;

export function Artifacts_List(arg1:artifacts.ArtifactFilter):Promise<Array<artifacts.Artifact>>;

export function Artifacts_Promote(arg1:string,arg2:string,arg3:string):Promise<artifacts.Artifact>;

export function Artifacts_SaveAs(arg1:string,arg2:string):Promise<string>;

export function Attachments_Add(arg1:attachments.AddInput):Promise<attachments.Attachment>;

export function Attachments_AddMedia(arg1:attachments.AddMediaInput):Promise<attachments.Attachment>;

export function Attachments_List(arg1:string,arg2:string):Promise<Array<attachments.Attachment>>;

export function Attachments_ListResolved(arg1:string):Promise<Array<attachments.Attachment>>;

export function Attachments_Refresh(arg1:string):Promise<attachments.Attachment>;

export function Attachments_Remove(arg1:string):Promise<void>;

export function Attachments_Reorder(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function Audit_BulkPurge(arg1:Array<string>):Promise<void>;

export function Audit_DeleteQuery(arg1:string):Promise<void>;

export function Audit_Export(arg1:log.ExportOptions):Promise<string>;

export function Audit_Filter(arg1:log.FilterQuery):Promise<Array<audit.Entry>>;

export function Audit_ListEntries(arg1:audit.Filter):Promise<Array<audit.Entry>>;

export function Audit_ListSavedQueries():Promise<Array<log.SavedQuery>>;

export function Audit_SaveQuery(arg1:log.SavedQuery):Promise<void>;

export function Audit_StartStream(arg1:audit.Filter):Promise<string>;

export function Audit_StopStream(arg1:string):Promise<void>;

export function Audit_VerifyChain(arg1:string,arg2:string):Promise<audit.VerifyChainResult>;

export function Audit_VerifyEntry(arg1:string):Promise<boolean>;

export function Bash_Exec(arg1:string,arg2:string):Promise<rpc.BashExecResult>;

export function BootHealth_Get():Promise<rpc.BootHealthReport>;

export function Branches_Abandon(arg1:string):Promise<void>;

export function Branches_CommitReintegration(arg1:branches.CommitReintegrationOptions):Promise<void>;

export function Branches_Create(arg1:branches.CreateBranchOptions):Promise<branches.Branch>;

export function Branches_GetStatus(arg1:string):Promise<branches.BranchStatus>;

export function Branches_List(arg1:string):Promise<Array<branches.Branch>>;

export function Branches_ListWithBranchTree(arg1:string):Promise<Array<branches.SessionWithBranchPointer>>;

export function Branches_Merge(arg1:string):Promise<void>;

export function Branches_ProposeReintegrationSummary(arg1:string):Promise<branches.ReintegrationProposal>;

export function Branches_RecommendModel(arg1:string,arg2:string,arg3:string):Promise<branches.RecommendedModel>;

export function Branches_SetAdvisorDismissed(arg1:string,arg2:boolean):Promise<void>;

export function Bundle_Get(arg1:string):Promise<bundle.Bundle>;

export function Bundle_Install(arg1:bundle.InstallRequest):Promise<bundle.Bundle>;

export function Bundle_List():Promise<Array<bundle.Bundle>>;

export function Bundle_Remove(arg1:string):Promise<void>;

export function Catalog_Install(arg1:string,arg2:string):Promise<void>;

export function Catalog_Installed():Promise<Array<catalog.CatalogItemView>>;

export function Compliance_ArchiveNow():Promise<void>;

export function Compliance_SetRetention(arg1:number):Promise<void>;

export function Compliance_Status():Promise<compliance.ComplianceStatus>;

export function Catalog_List(arg1:catalog.CatalogFilter):Promise<Array<catalog.CatalogItemView>>;

export function Catalog_Publish(arg1:catalog.PublishInput):Promise<catalog.CatalogItemView>;

export function Catalog_Uninstall(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CedarPolicy_Delete(arg1:string):Promise<void>;

export function CedarPolicy_Get(arg1:string):Promise<cedarpolicy.PolicyFileDetail>;

export function CedarPolicy_InstallTemplate(arg1:string,arg2:string):Promise<cedarpolicy.PolicyFileDetail>;

export function CedarPolicy_ListPlanModeActions():Promise<Array<string>>;

export function CedarPolicy_ListPolicies():Promise<Array<cedar.PolicyFile>>;

export function CedarPolicy_RecentDecisions(arg1:number):Promise<Array<cedar.Decision>>;

export function CedarPolicy_ReloadPolicies():Promise<void>;

export function CedarPolicy_ResolvePropose(arg1:string,arg2:string):Promise<void>;

export function CedarPolicy_RevokeSnippet(arg1:string):Promise<void>;

export function CedarPolicy_Save(arg1:string,arg2:string):Promise<cedarpolicy.ParseResult>;

export function CedarPolicy_Validate(arg1:string):Promise<cedarpolicy.ParseResult>;

export function CedarPolicy_WriteSnippet(arg1:string,arg2:string):Promise<void>;

export function Cedar_PublishToTeam(arg1:string,arg2:string):Promise<void>;

export function Compaction_GetConfig(arg1:compaction.Layer,arg2:string):Promise<compaction.Config>;

export function Compaction_GetEffective(arg1:compaction.ScopeKey):Promise<compaction.EffectiveConfig>;

export function Compaction_GetTierExplain():Promise<Array<compaction.TierExplain>>;

export function Compaction_ListCustomStrategies():Promise<Array<compaction.CustomStrategy>>;

export function Compaction_SetConfig(arg1:compaction.Layer,arg2:string,arg3:compaction.Config):Promise<void>;

export function Compaction_TriggerManual(arg1:string,arg2:compaction.ManualOpts):Promise<compaction.ManualResult>;

export function Config_GetFlags():Promise<Array<rpc.FeatureFlagInfo>>;

export function Context_List():Promise<Array<contextview.ContextEntry>>;

export function Context_StartStream():Promise<string>;

export function Context_StopStream(arg1:string):Promise<void>;

export function Contexts_AttachModule(arg1:string,arg2:string,arg3:string):Promise<contexts.ModuleAttachment>;

export function Contexts_ContextExport(arg1:string,arg2:string):Promise<contexts.ContextExportView>;

export function Contexts_ContextPromote(arg1:string):Promise<contexts.ContextPromoteResult>;

export function Contexts_ContextPublish(arg1:contexts.ContextPublishRequest):Promise<contexts.ContextPublishResult>;

export function Contexts_ContextSearch(arg1:string,arg2:string,arg3:number):Promise<Array<contexts.ContextSearchHitView>>;

export function Contexts_ContextSyncStatus():Promise<contexts.ContextSyncStatusView>;

export function Contexts_CreateFolder(arg1:string):Promise<void>;

export function Contexts_Delete(arg1:string):Promise<void>;

export function Contexts_Get(arg1:string):Promise<string>;

export function Contexts_List():Promise<contexts.Node>;

export function Contexts_ListAll():Promise<contexts.Node>;

export function Contexts_RecentlyApplied(arg1:number):Promise<Array<string>>;

export function Contexts_Rename(arg1:string,arg2:string):Promise<void>;

export function Contexts_RootPath():Promise<string>;

export function Contexts_Save(arg1:string,arg2:string):Promise<void>;

export function Corpus_CreateCorpus(arg1:corpus.CreateRequest):Promise<corpus.Corpus>;

export function Corpus_DeleteCorpus(arg1:string):Promise<void>;

export function Corpus_GetCorpus(arg1:string):Promise<corpus.Corpus>;

export function Corpus_IngestPath(arg1:string,arg2:string,arg3:corpus.IngestOptions):Promise<corpus.IngestStatus>;

export function Corpus_JobStatus(arg1:string):Promise<corpus.IngestStatus>;

export function Corpus_ListChunks(arg1:string,arg2:string):Promise<Array<corpus.Chunk>>;

export function Corpus_ListCorpora(arg1:string):Promise<Array<corpus.Corpus>>;

export function Corpus_ListFiles(arg1:string):Promise<Array<corpus.CorpusFile>>;

export function Corpus_Retrieve(arg1:string,arg2:corpus.RetrieveRequest):Promise<corpus.RetrieveResponse>;

export function Diag_LogClientEvent(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function Diag_LogPath():Promise<string>;

export function Dials_BumpAndResume(arg1:string,arg2:dials.DialDelta):Promise<void>;

export function Dials_Get(arg1:dials.ScopeKey):Promise<dials.DialConfig>;

export function Dials_GetEffective(arg1:string,arg2:string,arg3:string,arg4:string):Promise<dials.EffectiveDials>;

export function Dials_Set(arg1:dials.ScopeKey,arg2:dials.DialConfig):Promise<void>;

export function Elicit_AnswerDeferred(arg1:string,arg2:any):Promise<string>;

export function Elicit_ListPending():Promise<Array<elicit.ElicitRequest>>;

export function Elicit_RegisterDeferred(arg1:string,arg2:elicit.ElicitRequest):Promise<elicit.DeferredResult>;

export function Elicit_SubmitAnswer(arg1:string,arg2:json.RawMessage,arg3:boolean):Promise<void>;

export function Elicit_SubmitWizardStep(arg1:string,arg2:string,arg3:json.RawMessage,arg4:boolean):Promise<void>;

export function Fleet_GetTelemetryConsent():Promise<string>;

export function Fleet_SetTelemetryConsent(arg1:string):Promise<void>;

export function Graph_CancelRun(arg1:string):Promise<void>;

export function Graph_DeleteGraph(arg1:string):Promise<void>;

export function Graph_GetRunStatus(arg1:string):Promise<agentgraph.RunStatus>;

export function Graph_GetRunTrace(arg1:string,arg2:number):Promise<Array<agentgraph.RunTraceEvent>>;

export function Graph_ListGraphs(arg1:string):Promise<Array<agentgraph.GraphInfo>>;

export function Graph_LoadGraph(arg1:string):Promise<agentgraph.GraphSpec>;

export function Graph_Resume(arg1:string,arg2:string):Promise<void>;

export function Graph_SaveGraph(arg1:agentgraph.GraphSpec):Promise<void>;

export function Graph_StartRun(arg1:agentgraph.StartRunRequest):Promise<agentgraph.StartRunResponse>;

export function Graph_Validate(arg1:string):Promise<agentgraph.ValidationResult>;

export function Hooks_Add(arg1:hooks.Hook):Promise<hooks.Hook>;

export function Hooks_AvailableBuiltins():Promise<Array<hooks.BuiltinDescriptor>>;

export function Hooks_DryRun(arg1:string,arg2:string):Promise<hooks.DryRunResult>;

export function Hooks_Get(arg1:string):Promise<hooks.Hook>;

export function Hooks_InstallStarterMemory():Promise<void>;

export function Hooks_List():Promise<Array<hooks.Hook>>;

export function Hooks_Remove(arg1:string):Promise<void>;

export function Hooks_RemoveStarterMemory():Promise<void>;

export function Hooks_Update(arg1:hooks.Hook):Promise<void>;

export function LLM_AddProvider(arg1:llm.AddProviderInput):Promise<void>;

export function LLM_AutoConfigureLocalRuntime(arg1:string):Promise<llm.LocalRuntimeConfigResult>;

export function LLM_DeleteChain(arg1:string):Promise<void>;

export function LLM_GetAttachmentLimits(arg1:string,arg2:string):Promise<llm.AttachmentLimitsView>;

export function LLM_ListCustomTemplates():Promise<Array<llm.CustomTemplateSummary>>;

export function LLM_ListDetectedLocalRuntimes():Promise<Array<llm.LocalRuntimeInfo>>;

export function LLM_ListFallbackChains():Promise<Array<llm.FallbackChainSummary>>;

export function LLM_ListModels(arg1:string,arg2:string):Promise<Array<llm.ModelInfo>>;

export function LLM_ListProviders():Promise<Array<llm.Provider>>;

export function LLM_LoadChain(arg1:string):Promise<llm.FallbackChainView>;

export function LLM_ProbeCustomEndpoint(arg1:llm.ProbeCustomEndpointInput):Promise<llm.ProbeCustomEndpointResult>;

export function LLM_RecognizeTemplate(arg1:string):Promise<llm.RecognizeTemplateResult>;

export function LLM_RemoveProvider(arg1:string):Promise<void>;

export function LLM_RescanLocalRuntimes():Promise<Array<llm.LocalRuntimeInfo>>;

export function LLM_ResolveConfirm(arg1:string,arg2:string):Promise<void>;

export function LLM_ResumeAfterKeyRotation(arg1:string):Promise<void>;

export function LLM_SaveChain(arg1:llm.FallbackChainView):Promise<void>;

export function LLM_StartStream(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LLM_StopStream(arg1:string):Promise<void>;

export function LLM_TestAndRotateKey(arg1:string,arg2:string,arg3:string):Promise<llm.RotationResult>;

export function LLM_TestProvider(arg1:string):Promise<llm.TestResult>;

export function LLM_TestProviderKey(arg1:string,arg2:string,arg3:string):Promise<llm.ProviderKeyTestResult>;

export function LLM_UpdateProvider(arg1:llm.AddProviderInput):Promise<void>;

export function LLM_UpdateProviderCredential(arg1:string,arg2:string):Promise<void>;

export function LoadRoute():Promise<string>;

export function LoadTheme():Promise<string>;

export function LogRouteChange(arg1:string,arg2:string):Promise<void>;

export function MCP_HealthSnapshot():Promise<Record<string, mcp.HealthEntry>>;

export function MCP_ImportClaudeDesktopConfig(arg1:mcp.ImportRequest):Promise<mcp.ImportResponse>;

export function MCP_ListServers():Promise<Array<mcp.Server>>;

export function MCP_StartStream(arg1:string):Promise<string>;

export function MCP_StopStream(arg1:string):Promise<void>;

export function MCP_SubscribeHealthChanges():Promise<string>;

export function MCP_TestRecipe(arg1:string,arg2:Record<string, string>,arg3:Record<string, any>):Promise<mcp.TestResult>;

export function Memory_CaptureRate():Promise<memory.CaptureRateSnapshot>;

export function Memory_EmbedderEligibility():Promise<memory.EmbedderEligibility>;

export function Memory_EmbeddingProbe(arg1:string,arg2:number):Promise<Array<memory.ScoredChunk>>;

export function Memory_Forget(arg1:string):Promise<void>;

export function Memory_GetChunkProvenance(arg1:string):Promise<memory.ChunkProvenance>;

export function Memory_HealthSnapshot():Promise<memory.HealthSnapshot>;

export function Memory_JournalTail(arg1:string,arg2:number,arg3:number):Promise<Array<memory.JournalEntry>>;

export function Memory_LastRetrieval(arg1:string):Promise<memory.RetrievalReport>;

export function Memory_ListChunks(arg1:memory.ListFilter):Promise<Array<memory.Chunk>>;

export function Memory_MarkImportant(arg1:string,arg2:boolean):Promise<void>;

export function Memory_NarrativeFailedCount():Promise<number>;

export function Memory_NarrativeFailedList():Promise<Array<memory.NarrativeJobStatus>>;

export function Memory_NarrativeMetricsForChunk(arg1:string):Promise<memory.NarrativeMetrics>;

export function Memory_Pin(arg1:string,arg2:boolean):Promise<void>;

export function Memory_PromoteScope(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Memory_PrunePreview(arg1:string):Promise<memory.PrunePreview>;

export function Memory_RememberMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Memory_ResummarizeChunk(arg1:string):Promise<memory.Chunk>;

export function Memory_RetryFailedNarrative(arg1:string):Promise<void>;

export function Memory_RunPruneNow(arg1:string):Promise<memory.PruneStats>;

export function Memory_TestEmbedder():Promise<number>;

export function Nodes_Catalog():Promise<Array<nodes.NodeManifestSummary>>;

export function Nodes_Doctor():Promise<nodes.DoctorReport>;

export function Nodes_Get(arg1:string):Promise<nodes.NodeManifestDetail>;

export function Nodes_ListUserOverrides():Promise<Array<nodes.UserOverrideInfo>>;

export function Nodes_ReloadOverrides():Promise<nodes.ReloadResult>;

export function Onboarding_Begin():Promise<onboarding.StepResponse>;

export function Onboarding_Dismiss():Promise<void>;

export function Onboarding_ListStarters():Promise<Array<onboarding.StarterSummary>>;

export function Onboarding_RestartPhase2(arg1:onboarding.RestartPhase2Request):Promise<onboarding.RestartPhase2Response>;

export function Onboarding_State():Promise<onboarding.OnboardingState>;

export function Onboarding_Step(arg1:onboarding.StepRequest):Promise<onboarding.StepResponse>;

export function Permissions_ListGrants(arg1:string):Promise<Array<permissions.Grant>>;

export function Permissions_ListPending():Promise<Array<cedar.PendingRequest>>;

export function Permissions_Resolve(arg1:string,arg2:string):Promise<void>;

export function Permissions_RevokeGrant(arg1:string):Promise<void>;

export function Planmode_Approve(arg1:planmode.ApproveRequest):Promise<planmode.ApproveResponse>;

export function Planmode_Discard(arg1:planmode.DiscardRequest):Promise<planmode.DiscardResponse>;

export function Planmode_Edit(arg1:planmode.EditRequest):Promise<planmode.EditResponse>;

export function Policy_Explain(arg1:Record<string, any>):Promise<policy.Denial>;

export function Policy_StartStream():Promise<string>;

export function Policy_StopStream(arg1:string):Promise<void>;

export function Projects_AddSession(arg1:string,arg2:string):Promise<void>;

export function Projects_Create(arg1:string,arg2:string):Promise<projects.Project>;

export function Projects_Delete(arg1:string,arg2:boolean):Promise<void>;

export function Projects_Get(arg1:string):Promise<projects.Project>;

export function Projects_GetAutonomy(arg1:string):Promise<autonomy.Layer>;

export function Projects_List():Promise<Array<projects.Project>>;

export function Projects_ListSessions(arg1:string):Promise<Array<projects.Session>>;

export function Projects_RemoveSession(arg1:string):Promise<void>;

export function Projects_Rename(arg1:string,arg2:string):Promise<void>;

export function Projects_SetAutonomy(arg1:string,arg2:autonomy.Layer):Promise<void>;

export function Projects_UpdateDescription(arg1:string,arg2:string):Promise<void>;

export function SaveRoute(arg1:string):Promise<void>;

export function SaveTheme(arg1:string):Promise<void>;

export function ScheduledChat_Create(arg1:scheduledchat.CreateInput):Promise<scheduledchat.ChatRunEntry>;

export function ScheduledChat_Delete(arg1:string):Promise<void>;

export function ScheduledChat_Get(arg1:string):Promise<scheduledchat.ChatRunEntry>;

export function ScheduledChat_History(arg1:string,arg2:number):Promise<Array<scheduledchat.RunSummary>>;

export function ScheduledChat_List():Promise<Array<scheduledchat.ChatRunEntry>>;

export function ScheduledChat_RunNow(arg1:string):Promise<scheduledchat.RunSummary>;

export function ScheduledChat_SetEnabled(arg1:string,arg2:boolean):Promise<void>;

export function ScheduledChat_Update(arg1:scheduledchat.UpdateInput):Promise<scheduledchat.ChatRunEntry>;

export function Search_Sessions(arg1:string,arg2:search.SearchFilters):Promise<Array<search.SearchHit>>;

export function Search_Unified(arg1:string,arg2:search.SearchFilters):Promise<Array<search.SearchHit>>;

export function Secrets_Expose(arg1:secrets.ExposeRequest):Promise<void>;

export function Secrets_List():Promise<Array<secrets.SecretRow>>;

export function Secrets_Revoke(arg1:string):Promise<void>;

export function Sentry_GenerateLocalReport():Promise<sentry.LocalReportResult>;

export function Sentry_GetLastFive():Promise<Array<sentry.CachedEntry>>;

export function Sentry_TestDSN(arg1:string):Promise<sentry.DSNTestResult>;

export function Sessions_AppendMessage(arg1:string,arg2:string,arg3:string):Promise<sessions.Message>;

export function Sessions_ClearTitle(arg1:string):Promise<void>;

export function Sessions_Create(arg1:string):Promise<sessions.Session>;

export function Sessions_Delete(arg1:string):Promise<void>;

export function Sessions_DeleteWithOptions(arg1:string,arg2:sessions.DeleteOptions):Promise<void>;

export function Sessions_Export(arg1:string,arg2:string):Promise<sessions.ExportResult>;

export function Sessions_Get(arg1:string):Promise<sessions.Session>;

export function Sessions_GetAutonomy(arg1:string):Promise<autonomy.Layer>;

export function Sessions_GetUsage(arg1:string):Promise<sessions.SessionUsage>;

export function Sessions_List():Promise<Array<sessions.Session>>;

export function Sessions_ListMessages(arg1:string):Promise<Array<sessions.Message>>;

export function Sessions_ListMessagesActive(arg1:string):Promise<sessions.ListMessagesResult>;

export function Sessions_ListMessagesAll(arg1:string):Promise<sessions.ListMessagesResult>;

export function Sessions_LoadDraft(arg1:string):Promise<string>;

export function Sessions_MoveToProject(arg1:string,arg2:string):Promise<void>;

export function Sessions_Rename(arg1:string,arg2:string):Promise<void>;

export function Sessions_Reorder(arg1:Array<string>):Promise<void>;

export function Sessions_ResolveAutonomy(arg1:string):Promise<sessions.ResolvedAutonomy>;

export function Sessions_ResumeMessage(arg1:string,arg2:string):Promise<sessions.ResumeMessageResult>;

export function Sessions_SaveAsArtifact(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<artifacts.Artifact>;

export function Sessions_SaveDraft(arg1:string,arg2:string):Promise<void>;

export function Sessions_SendMessageWithBlocks(arg1:string,arg2:Array<llm.ContentBlock>):Promise<sessions.Message>;

export function Sessions_SetAutonomy(arg1:string,arg2:autonomy.Layer):Promise<void>;

export function Sessions_SetSystemPrompt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Sessions_StartCapture(arg1:string):Promise<void>;

export function Sessions_StartStream(arg1:string):Promise<string>;

export function Sessions_StopCapture(arg1:string):Promise<void>;

export function Sessions_StopStream(arg1:string):Promise<void>;

export function Sessions_SuggestTitle(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetSettingsStore(arg1:settings.SettingsStore):Promise<void>;

export function Settings_FleetCapabilities():Promise<settings.CapabilitiesView>;

export function Settings_FleetConfigPullStatus():Promise<settings.FleetConfigPullStatusView>;

export function Settings_FleetHealth():Promise<settings.FleetHealthView>;

export function Settings_FleetLockdownStatus():Promise<settings.LockdownStatusView>;

export function Settings_FleetProfile():Promise<settings.FleetProfileInfo>;

export function Settings_FleetRefreshCapabilities():Promise<settings.CapabilitiesView>;

export function Settings_FleetRefreshIdentity():Promise<settings.FleetIdentity>;

export function Settings_FleetSetTelemetryOptIn(arg1:string,arg2:boolean):Promise<void>;

export function Settings_FleetSignIn():Promise<settings.FleetIdentity>;

export function Settings_FleetSignOut():Promise<void>;

export function Settings_FleetSignedIn():Promise<boolean>;

export function Settings_FleetTelemetryOptIns():Promise<Array<settings.TelemetryOptInView>>;

export function Settings_Get():Promise<settings.Settings>;

export function Settings_GetArtifactPreview():Promise<rpc.ArtifactPreviewConfig>;

export function Settings_GetAuditSettings():Promise<settings.AuditSettings>;

export function Settings_GetAutoCaptureGeneratedImages():Promise<boolean>;

export function Settings_GetAutoResumeOnKeyRotation():Promise<boolean>;

export function Settings_GetAutoTitleEnabled():Promise<boolean>;

export function Settings_GetAutonomy():Promise<autonomy.Layer>;

export function Settings_GetBash():Promise<boolean>;

export function Settings_GetBashAllowlistMigrated():Promise<boolean>;

export function Settings_GetCedarStrictCredentialMode():Promise<boolean>;

export function Settings_GetEmbedderConfig():Promise<rpc.EmbedderConfigResult>;

export function Settings_GetFSReadEnabled():Promise<boolean>;

export function Settings_GetFSRequestAccessEnabled():Promise<boolean>;

export function Settings_GetFSWriteEnabled():Promise<boolean>;

export function Settings_GetLocalRuntimeRAMOverrideGB():Promise<number>;

export function Settings_GetMCPAutoRestart():Promise<boolean>;

export function Settings_GetMaxAgentTurns():Promise<number>;

export function Settings_GetMaxGeneratedImageBytes():Promise<number>;

export function Settings_GetMemory():Promise<boolean>;

export function Settings_GetMonthlyCostNotifyUSD():Promise<number>;

export function Settings_GetMultimodalInput():Promise<boolean>;

export function Settings_GetPermissionCacheDangerousOps():Promise<boolean>;

export function Settings_GetPermissionMode():Promise<string>;

export function Settings_GetPermissionsMigrationToastShown():Promise<boolean>;

export function Settings_GetSaveArtifactEnabled():Promise<boolean>;

export function Settings_GetShortcuts():Promise<Record<string, string>>;

export function Settings_GetShowPerMessageTokenMeter():Promise<boolean>;

export function Settings_GetTodoEnabled():Promise<boolean>;

export function Settings_GetWebFetchEnabled():Promise<boolean>;

export function Settings_GetWebSearch():Promise<boolean>;

export function Settings_Set(arg1:settings.Settings):Promise<void>;

export function Settings_SetAuditSettings(arg1:settings.AuditSettings):Promise<void>;

export function Settings_SetAutoCaptureGeneratedImages(arg1:boolean):Promise<void>;

export function Settings_SetAutoResumeOnKeyRotation(arg1:boolean):Promise<void>;

export function Settings_SetAutoTitleEnabled(arg1:boolean):Promise<void>;

export function Settings_SetAutonomy(arg1:autonomy.Layer):Promise<void>;

export function Settings_SetBash(arg1:boolean):Promise<void>;

export function Settings_SetBashAllowlistMigrated(arg1:boolean):Promise<void>;

export function Settings_SetCedarStrictCredentialMode(arg1:boolean):Promise<void>;

export function Settings_SetEmbedderConfig(arg1:string,arg2:string):Promise<void>;

export function Settings_SetFSReadEnabled(arg1:boolean):Promise<void>;

export function Settings_SetFSRequestAccessEnabled(arg1:boolean):Promise<void>;

export function Settings_SetFSWriteEnabled(arg1:boolean):Promise<void>;

export function Settings_SetLocalRuntimeRAMOverrideGB(arg1:number):Promise<void>;

export function Settings_SetMCPAutoRestart(arg1:boolean):Promise<void>;

export function Settings_SetMaxAgentTurns(arg1:number):Promise<void>;

export function Settings_SetMaxGeneratedImageBytes(arg1:number):Promise<void>;

export function Settings_SetMemory(arg1:boolean):Promise<void>;

export function Settings_SetMonthlyCostNotifyUSD(arg1:number):Promise<void>;

export function Settings_SetMultimodalInput(arg1:boolean):Promise<void>;

export function Settings_SetPermissionCacheDangerousOps(arg1:boolean):Promise<void>;

export function Settings_SetPermissionMode(arg1:string):Promise<void>;

export function Settings_SetPermissionsMigrationToastShown(arg1:boolean):Promise<void>;

export function Settings_SetSaveArtifactEnabled(arg1:boolean):Promise<void>;

export function Settings_SetShortcut(arg1:string,arg2:string):Promise<void>;

export function Settings_SetShortcuts(arg1:Record<string, string>):Promise<void>;

export function Settings_SetShowPerMessageTokenMeter(arg1:boolean):Promise<void>;

export function Settings_SetTodoEnabled(arg1:boolean):Promise<void>;

export function Settings_SetWebFetchEnabled(arg1:boolean):Promise<void>;

export function Settings_SetWebSearch(arg1:boolean):Promise<void>;

export function ShellStatus():Promise<rpc.ShellStatus>;

export function Shell_OpenInOSBrowser(arg1:string):Promise<void>;

export function Shell_PathComplete(arg1:string):Promise<Array<string>>;

export function Shell_PickFile(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function Shell_ReadFile(arg1:string):Promise<rpc.ShellReadFileResult>;

export function Sites_Delete(arg1:string):Promise<void>;

export function Sites_Deploy(arg1:string):Promise<sites.SiteSummary>;

export function Sites_List():Promise<Array<sites.SiteSummary>>;

export function Sites_Logs(arg1:string,arg2:number):Promise<string>;

export function Sites_Status(arg1:string):Promise<sites.SiteSummary>;

export function Slash_Execute(arg1:string,arg2:string):Promise<slashcmd.ExecuteResult>;

export function Slash_List():Promise<Array<slashcmd.CommandInfo>>;

export function Slashcmd_Delete(arg1:string,arg2:string):Promise<void>;

export function Slashcmd_Get(arg1:string,arg2:string):Promise<slashcmd.UserCommandWire>;

export function Slashcmd_List(arg1:string):Promise<Array<slashcmd.UserCommandSummaryWire>>;

export function Slashcmd_Run(arg1:string,arg2:Record<string, string>,arg3:string,arg4:string,arg5:string,arg6:string):Promise<slashcmd.RunResultWire>;

export function Slashcmd_Save(arg1:slashcmd.UserCommandWire):Promise<void>;

export function Slashcmd_SkillInstall(arg1:string,arg2:string):Promise<void>;

export function Slashcmd_SkillList():Promise<Array<slashcmd.SkillItemWire>>;

export function Slashcmd_SkillPublish(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Slashcmd_SkillRenameLocalTrigger(arg1:string,arg2:string):Promise<void>;

export function Slashcmd_SkillUninstall(arg1:string):Promise<void>;

export function Storage_ApplyDriftFix(arg1:number):Promise<void>;

export function Storage_GetMigrationDriftReport():Promise<storage.DriftReport>;

export function Sync_ForcePull(arg1:string):Promise<void>;

export function Sync_ForcePush(arg1:string):Promise<void>;

export function Sync_PendingMCPSecrets():Promise<Array<sync.PendingMCPSecret>>;

export function Sync_Status():Promise<Array<sync.SyncStatusView>>;

export function Sync_Toggle(arg1:string,arg2:boolean):Promise<void>;

export function Tasks_Abort(arg1:string):Promise<void>;

export function Tasks_AbortBySession(arg1:string):Promise<void>;

export function Tasks_Get(arg1:string):Promise<tasks.TaskRow>;

export function Tasks_List():Promise<Array<tasks.TaskRow>>;

export function Tasks_ListBySession(arg1:string):Promise<Array<tasks.TaskRow>>;

export function Tasks_Tail(arg1:string,arg2:number):Promise<Array<tasks.LineRow>>;

export function Tools_ForgetRecipeKey(arg1:string,arg2:string):Promise<void>;

export function Tools_InstallRecipe(arg1:string,arg2:Record<string, string>,arg3:Record<string, any>):Promise<transport.RecipeStatus>;

export function Tools_ListRecipes():Promise<Array<tools.RecipeListing>>;

export function Tools_PickDirectory(arg1:string,arg2:string):Promise<string>;

export function Tools_RecipeConfig(arg1:string):Promise<Record<string, any>>;

export function Tools_RecipeStatus(arg1:string):Promise<transport.RecipeStatus>;

export function Tools_RequestAdditionalAllowedDir(arg1:string,arg2:string,arg3:string):Promise<tools.FSAccessResult>;

export function Tools_SignInRecipe(arg1:string):Promise<transport.RecipeStatus>;

export function Tools_UninstallRecipe(arg1:string):Promise<void>;

export function Trust_GetSecretReference(arg1:string):Promise<trust.SecretReference>;

export function Trust_ListSecretReferences():Promise<Array<trust.SecretReference>>;

export function Unit_ListConflicts():Promise<Array<fleet.UnitConflictView>>;

export function Unit_PromoteAsMergeRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<fleet.MergeRequestResult>;

export function Unit_ResolveEnshrine(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Unit_ResolveLoadable(arg1:string,arg2:string):Promise<Array<fleet.ResolvedUnitView>>;

export function Unit_ResolveMerge(arg1:string,arg2:string):Promise<void>;

export function Unit_SyncStatus():Promise<fleet.UnitSyncStatusView>;

export function Update_Apply():Promise<void>;

export function Update_ListSkippedVersions():Promise<Array<string>>;

export function Update_SkipVersion(arg1:string):Promise<void>;

export function Update_StartCheck():Promise<void>;

export function Update_StartDownload():Promise<void>;

export function Update_Status():Promise<update.StatusOutput>;

export function Update_UnskipVersion(arg1:string):Promise<void>;

export function Workflow_ListJobs():Promise<Array<workflow.Job>>;

export function Workflow_StartStream():Promise<string>;

export function Workflow_StopStream(arg1:string):Promise<void>;

export function Workflows_CancelRun(arg1:string):Promise<void>;

export function Workflows_CatalogGet(arg1:string):Promise<workflows.CatalogPreview>;

export function Workflows_CatalogInstall(arg1:string):Promise<workflows.CatalogInstallResult>;

export function Workflows_CatalogList():Promise<Array<workflows.CatalogEntry>>;

export function Workflows_Delete(arg1:string):Promise<void>;

export function Workflows_Get(arg1:string):Promise<workflows.Workflow>;

export function Workflows_List():Promise<Array<workflows.Summary>>;

export function Workflows_Run(arg1:string,arg2:Record<string, string>):Promise<workflows.RunResult>;

export function Workflows_RunNow(arg1:string):Promise<workflows.RunSummary>;

export function Workflows_Save(arg1:workflows.SaveInput):Promise<workflows.SaveOutput>;

export function Workflows_ScheduleClear(arg1:string):Promise<void>;

export function Workflows_ScheduleList():Promise<Array<workflows.ScheduleEntry>>;

export function Workflows_ScheduleNextFire(arg1:string):Promise<string>;

export function Workflows_ScheduleRunHistory(arg1:string,arg2:number):Promise<Array<workflows.RunSummary>>;

export function Workflows_ScheduleSet(arg1:workflows.ScheduleSetInput):Promise<void>;
