// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {a2a} from '../models';
import {rpc} from '../models';
import {attachments} from '../models';
import {audit} from '../models';
import {bundle} from '../models';
import {contextview} from '../models';
import {contexts} from '../models';
import {hooks} from '../models';
import {llm} from '../models';
import {mcp} from '../models';
import {memory} from '../models';
import {policy} from '../models';
import {projects} from '../models';
import {sessions} from '../models';
import {context} from '../models';
import {settings} from '../models';
import {stdio} from '../models';
import {tools} from '../models';
import {trust} from '../models';
import {workflow} from '../models';

export function A2A_ListCards():Promise<Array<a2a.Card>>;

export function A2A_StartStream():Promise<string>;

export function A2A_StopStream(arg1:string):Promise<void>;

export function AppInfo():Promise<rpc.AppInfo>;

export function Attachments_Add(arg1:attachments.AddInput):Promise<attachments.Attachment>;

export function Attachments_List(arg1:string,arg2:string):Promise<Array<attachments.Attachment>>;

export function Attachments_ListResolved(arg1:string):Promise<Array<attachments.Attachment>>;

export function Attachments_Refresh(arg1:string):Promise<attachments.Attachment>;

export function Attachments_Remove(arg1:string):Promise<void>;

export function Attachments_Reorder(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function Audit_ListEntries(arg1:audit.Filter):Promise<Array<audit.Entry>>;

export function Audit_StartStream(arg1:audit.Filter):Promise<string>;

export function Audit_StopStream(arg1:string):Promise<void>;

export function Audit_VerifyEntry(arg1:string):Promise<boolean>;

export function Bundle_Get(arg1:string):Promise<bundle.Bundle>;

export function Bundle_List():Promise<Array<bundle.Bundle>>;

export function Context_List():Promise<Array<contextview.ContextEntry>>;

export function Context_StartStream():Promise<string>;

export function Context_StopStream(arg1:string):Promise<void>;

export function Contexts_CreateFolder(arg1:string):Promise<void>;

export function Contexts_Delete(arg1:string):Promise<void>;

export function Contexts_Get(arg1:string):Promise<string>;

export function Contexts_List():Promise<contexts.Node>;

export function Contexts_ListAll():Promise<contexts.Node>;

export function Contexts_RecentlyApplied(arg1:number):Promise<Array<string>>;

export function Contexts_Rename(arg1:string,arg2:string):Promise<void>;

export function Contexts_RootPath():Promise<string>;

export function Contexts_Save(arg1:string,arg2:string):Promise<void>;

export function Diag_LogClientEvent(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function Diag_LogPath():Promise<string>;

export function Hooks_Add(arg1:hooks.Hook):Promise<hooks.Hook>;

export function Hooks_AvailableBuiltins():Promise<Array<hooks.BuiltinDescriptor>>;

export function Hooks_Get(arg1:string):Promise<hooks.Hook>;

export function Hooks_InstallStarterMemory():Promise<void>;

export function Hooks_List():Promise<Array<hooks.Hook>>;

export function Hooks_Remove(arg1:string):Promise<void>;

export function Hooks_RemoveStarterMemory():Promise<void>;

export function Hooks_Update(arg1:hooks.Hook):Promise<void>;

export function LLM_AddProvider(arg1:llm.AddProviderInput):Promise<void>;

export function LLM_ListModels(arg1:string,arg2:string):Promise<Array<llm.ModelInfo>>;

export function LLM_ListProviders():Promise<Array<llm.Provider>>;

export function LLM_RemoveProvider(arg1:string):Promise<void>;

export function LLM_ResolveConfirm(arg1:string,arg2:string):Promise<void>;

export function LLM_StartStream(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LLM_StopStream(arg1:string):Promise<void>;

export function LLM_TestProvider(arg1:string):Promise<llm.TestResult>;

export function LLM_UpdateProvider(arg1:llm.AddProviderInput):Promise<void>;

export function LoadRoute():Promise<string>;

export function LoadTheme():Promise<string>;

export function LogRouteChange(arg1:string,arg2:string):Promise<void>;

export function MCP_ListServers():Promise<Array<mcp.Server>>;

export function MCP_StartStream(arg1:string):Promise<string>;

export function MCP_StopStream(arg1:string):Promise<void>;

export function Memory_Forget(arg1:string):Promise<void>;

export function Memory_ListChunks(arg1:memory.ListFilter):Promise<Array<memory.Chunk>>;

export function Memory_PromoteScope(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Memory_RememberMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Policy_Explain(arg1:Record<string, any>):Promise<policy.Denial>;

export function Policy_StartStream():Promise<string>;

export function Policy_StopStream(arg1:string):Promise<void>;

export function Projects_AddSession(arg1:string,arg2:string):Promise<void>;

export function Projects_Create(arg1:string,arg2:string):Promise<projects.Project>;

export function Projects_Delete(arg1:string,arg2:boolean):Promise<void>;

export function Projects_Get(arg1:string):Promise<projects.Project>;

export function Projects_List():Promise<Array<projects.Project>>;

export function Projects_ListSessions(arg1:string):Promise<Array<projects.Session>>;

export function Projects_RemoveSession(arg1:string):Promise<void>;

export function Projects_Rename(arg1:string,arg2:string):Promise<void>;

export function Projects_UpdateDescription(arg1:string,arg2:string):Promise<void>;

export function SaveRoute(arg1:string):Promise<void>;

export function SaveTheme(arg1:string):Promise<void>;

export function Sessions_AppendMessage(arg1:string,arg2:string,arg3:string):Promise<sessions.Message>;

export function Sessions_Create(arg1:string):Promise<sessions.Session>;

export function Sessions_Delete(arg1:string):Promise<void>;

export function Sessions_Get(arg1:string):Promise<sessions.Session>;

export function Sessions_List():Promise<Array<sessions.Session>>;

export function Sessions_ListMessages(arg1:string):Promise<Array<sessions.Message>>;

export function Sessions_LoadDraft(arg1:string):Promise<string>;

export function Sessions_MoveToProject(arg1:string,arg2:string):Promise<void>;

export function Sessions_Rename(arg1:string,arg2:string):Promise<void>;

export function Sessions_Reorder(arg1:Array<string>):Promise<void>;

export function Sessions_SaveDraft(arg1:string,arg2:string):Promise<void>;

export function Sessions_SetSystemPrompt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Sessions_StartStream(arg1:string):Promise<string>;

export function Sessions_StopStream(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetSettingsStore(arg1:settings.SettingsStore):Promise<void>;

export function Settings_Get():Promise<settings.Settings>;

export function Settings_GetConfirmEach():Promise<boolean>;

export function Settings_GetMemory():Promise<boolean>;

export function Settings_Set(arg1:settings.Settings):Promise<void>;

export function Settings_SetConfirmEach(arg1:boolean):Promise<void>;

export function Settings_SetMemory(arg1:boolean):Promise<void>;

export function ShellStatus():Promise<rpc.ShellStatus>;

export function Tools_ForgetRecipeKey(arg1:string,arg2:string):Promise<void>;

export function Tools_InstallRecipe(arg1:string,arg2:Record<string, string>):Promise<stdio.RecipeStatus>;

export function Tools_ListRecipes():Promise<Array<tools.RecipeListing>>;

export function Tools_RecipeStatus(arg1:string):Promise<stdio.RecipeStatus>;

export function Tools_UninstallRecipe(arg1:string):Promise<void>;

export function Trust_GetSecretReference(arg1:string):Promise<trust.SecretReference>;

export function Trust_ListSecretReferences():Promise<Array<trust.SecretReference>>;

export function Workflow_ListJobs():Promise<Array<workflow.Job>>;

export function Workflow_StartStream():Promise<string>;

export function Workflow_StopStream(arg1:string):Promise<void>;
