// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function A2A_ListCards() {
  return window['go']['rpc']['Bindings']['A2A_ListCards']();
}

export function A2A_StartStream() {
  return window['go']['rpc']['Bindings']['A2A_StartStream']();
}

export function A2A_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['A2A_StopStream'](arg1);
}

export function AppInfo() {
  return window['go']['rpc']['Bindings']['AppInfo']();
}

export function Audit_ListEntries(arg1) {
  return window['go']['rpc']['Bindings']['Audit_ListEntries'](arg1);
}

export function Audit_StartStream(arg1) {
  return window['go']['rpc']['Bindings']['Audit_StartStream'](arg1);
}

export function Audit_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Audit_StopStream'](arg1);
}

export function Audit_VerifyEntry(arg1) {
  return window['go']['rpc']['Bindings']['Audit_VerifyEntry'](arg1);
}

export function Bundle_Get(arg1) {
  return window['go']['rpc']['Bindings']['Bundle_Get'](arg1);
}

export function Bundle_List() {
  return window['go']['rpc']['Bindings']['Bundle_List']();
}

export function Context_List() {
  return window['go']['rpc']['Bindings']['Context_List']();
}

export function Context_StartStream() {
  return window['go']['rpc']['Bindings']['Context_StartStream']();
}

export function Context_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Context_StopStream'](arg1);
}

export function Diag_LogClientEvent(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Diag_LogClientEvent'](arg1, arg2, arg3);
}

export function Diag_LogPath() {
  return window['go']['rpc']['Bindings']['Diag_LogPath']();
}

export function LLM_AddProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_AddProvider'](arg1);
}

export function LLM_ListModels(arg1, arg2) {
  return window['go']['rpc']['Bindings']['LLM_ListModels'](arg1, arg2);
}

export function LLM_ListProviders() {
  return window['go']['rpc']['Bindings']['LLM_ListProviders']();
}

export function LLM_RemoveProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_RemoveProvider'](arg1);
}

export function LLM_StartStream(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['LLM_StartStream'](arg1, arg2, arg3);
}

export function LLM_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['LLM_StopStream'](arg1);
}

export function LLM_TestProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_TestProvider'](arg1);
}

export function LLM_UpdateProvider(arg1) {
  return window['go']['rpc']['Bindings']['LLM_UpdateProvider'](arg1);
}

export function LoadRoute() {
  return window['go']['rpc']['Bindings']['LoadRoute']();
}

export function LoadTheme() {
  return window['go']['rpc']['Bindings']['LoadTheme']();
}

export function LogRouteChange(arg1, arg2) {
  return window['go']['rpc']['Bindings']['LogRouteChange'](arg1, arg2);
}

export function MCP_ListServers() {
  return window['go']['rpc']['Bindings']['MCP_ListServers']();
}

export function MCP_StartStream(arg1) {
  return window['go']['rpc']['Bindings']['MCP_StartStream'](arg1);
}

export function MCP_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['MCP_StopStream'](arg1);
}

export function Policy_Explain(arg1) {
  return window['go']['rpc']['Bindings']['Policy_Explain'](arg1);
}

export function Policy_StartStream() {
  return window['go']['rpc']['Bindings']['Policy_StartStream']();
}

export function Policy_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Policy_StopStream'](arg1);
}

export function SaveRoute(arg1) {
  return window['go']['rpc']['Bindings']['SaveRoute'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['rpc']['Bindings']['SaveTheme'](arg1);
}

export function Sessions_AppendMessage(arg1, arg2, arg3) {
  return window['go']['rpc']['Bindings']['Sessions_AppendMessage'](arg1, arg2, arg3);
}

export function Sessions_Create(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Create'](arg1);
}

export function Sessions_Delete(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Delete'](arg1);
}

export function Sessions_Get(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Get'](arg1);
}

export function Sessions_List() {
  return window['go']['rpc']['Bindings']['Sessions_List']();
}

export function Sessions_ListMessages(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_ListMessages'](arg1);
}

export function Sessions_LoadDraft(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_LoadDraft'](arg1);
}

export function Sessions_Rename(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_Rename'](arg1, arg2);
}

export function Sessions_Reorder(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_Reorder'](arg1);
}

export function Sessions_SaveDraft(arg1, arg2) {
  return window['go']['rpc']['Bindings']['Sessions_SaveDraft'](arg1, arg2);
}

export function Sessions_StartStream(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_StartStream'](arg1);
}

export function Sessions_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Sessions_StopStream'](arg1);
}

export function SetContext(arg1) {
  return window['go']['rpc']['Bindings']['SetContext'](arg1);
}

export function SetSettingsStore(arg1) {
  return window['go']['rpc']['Bindings']['SetSettingsStore'](arg1);
}

export function Settings_Get() {
  return window['go']['rpc']['Bindings']['Settings_Get']();
}

export function Settings_Set(arg1) {
  return window['go']['rpc']['Bindings']['Settings_Set'](arg1);
}

export function ShellStatus() {
  return window['go']['rpc']['Bindings']['ShellStatus']();
}

export function Trust_GetSecretReference(arg1) {
  return window['go']['rpc']['Bindings']['Trust_GetSecretReference'](arg1);
}

export function Trust_ListSecretReferences() {
  return window['go']['rpc']['Bindings']['Trust_ListSecretReferences']();
}

export function Workflow_ListJobs() {
  return window['go']['rpc']['Bindings']['Workflow_ListJobs']();
}

export function Workflow_StartStream() {
  return window['go']['rpc']['Bindings']['Workflow_StartStream']();
}

export function Workflow_StopStream(arg1) {
  return window['go']['rpc']['Bindings']['Workflow_StopStream'](arg1);
}
