-- upgrade-snapshot dump. Generated by scripts/ci/upgrade-snapshot.
-- Normalised: install_id and every applied_at are fixed literals;
-- content_hash is verbatim (load-bearing, see VerifyLedger).
-- DO NOT HAND-EDIT. Regenerate with scripts/ci/upgrade-snapshot.sh.

-- === SCHEMA (sorted by type, name) ===

CREATE INDEX idx_agent_graph_events_kind
            ON agent_graph_events (kind, ts_ns);

CREATE INDEX idx_agent_graph_events_node
            ON agent_graph_events (run_id, node_id);

CREATE INDEX idx_agent_graph_events_session
            ON agent_graph_events (session_id, ts_ns);

CREATE INDEX idx_agraph_node_prov_kind
            ON agent_graph_node_provenance (kind);

CREATE INDEX idx_artifact_versions_artifact
            ON artifact_versions (artifact_id, version DESC);

CREATE INDEX idx_artifacts_content_hash
                    ON artifacts (content_hash);

CREATE INDEX idx_artifacts_project
                    ON artifacts (project_id, created_at DESC) WHERE project_id IS NOT NULL;

CREATE INDEX idx_artifacts_session
                    ON artifacts (session_id, created_at DESC) WHERE session_id IS NOT NULL;

CREATE INDEX idx_branch_refs_branch
            ON branch_message_refs (branch_id);

CREATE INDEX idx_branches_child
            ON branches (child_session_id);

CREATE INDEX idx_branches_child_lookup ON branches (child_session_id);

CREATE INDEX idx_branches_parent
            ON branches (parent_session_id, status);

CREATE INDEX idx_context_attachments_scope
            ON context_attachments (scope_kind, scope_id, position);

CREATE INDEX idx_corpora_scope
            ON corpora (scope, scope_id);

CREATE INDEX idx_corpus_chunks_corpus
            ON corpus_chunks (corpus_id, file_id, chunk_seq);

CREATE INDEX idx_corpus_files_corpus
            ON corpus_files (corpus_id, path);

CREATE INDEX idx_custom_endpoint_probed_at
		ON custom_endpoint_capabilities(probed_at);

CREATE INDEX idx_events_emitted_at      ON events(emitted_at);

CREATE INDEX idx_events_emitter_event   ON events(emitter_id, event_id);

CREATE INDEX idx_events_kind_event      ON events(kind, event_id);

CREATE INDEX idx_events_session_event   ON events(session_id, event_id);

CREATE INDEX idx_harness_migrations_action
    ON harness_migrations (action);

CREATE INDEX idx_harness_migrations_version
    ON harness_migrations (version);

CREATE INDEX idx_media_artifacts_content_hash
            ON media_artifacts (content_hash);

CREATE INDEX idx_memory_hook_journal_boundary
            ON memory_hook_journal (boundary, ts_ns);

CREATE INDEX idx_memory_hook_journal_run
            ON memory_hook_journal (run_id, ts_ns);

CREATE INDEX idx_memory_hook_journal_session
            ON memory_hook_journal (session_id, ts_ns);

CREATE INDEX idx_projects_name ON projects (name);

CREATE INDEX idx_provider_capabilities_fetched_at
            ON provider_capabilities (fetched_at);

CREATE INDEX idx_schr_chat_run_started
            ON scheduled_chat_run_history (chat_run_id, started_at DESC);

CREATE INDEX idx_session_messages_archived_at
            ON session_messages (archived_at) WHERE archived_at IS NOT NULL;

CREATE INDEX idx_session_messages_compacted_into
            ON session_messages (compacted_into_id);

CREATE INDEX idx_session_messages_continuation_of ON session_messages (continuation_of) WHERE continuation_of IS NOT NULL;

CREATE INDEX idx_session_messages_session_seq
            ON session_messages (session_id, sequence);

CREATE INDEX idx_sessions_last_active_at
            ON sessions (last_active_at);

CREATE INDEX idx_sessions_position
            ON sessions (position);

CREATE INDEX idx_slash_user_model_invokable
		ON slash_commands_user(model_invokable);

CREATE INDEX idx_slash_user_scope
		ON slash_commands_user(scope, project_id);

CREATE INDEX idx_tasks_owner  ON tasks(owner_session_id);

CREATE INDEX idx_tasks_status ON tasks(status);

CREATE INDEX idx_telemetry_logs_trace
            ON telemetry_logs (trace_id) WHERE trace_id IS NOT NULL;

CREATE INDEX idx_telemetry_logs_ts
            ON telemetry_logs (ts_ns);

CREATE INDEX idx_telemetry_metrics_name
            ON telemetry_metrics (name, ts_ns);

CREATE INDEX idx_telemetry_spans_start
            ON telemetry_spans (start_ns);

CREATE INDEX idx_telemetry_spans_trace
            ON telemetry_spans (trace_id);

CREATE INDEX idx_trust_anchors_peer_id
		ON trust_anchors (peer_id, removed);

CREATE INDEX idx_trust_anchors_prevkey_fingerprint
		ON trust_anchors (prevkey_fingerprint);

CREATE INDEX idx_trust_anchors_pubkey_fingerprint
		ON trust_anchors (pubkey_fingerprint);

CREATE INDEX idx_unit_edges_from
        ON unit_edges (from_id, created_at ASC);

CREATE INDEX idx_unit_edges_to
        ON unit_edges (to_id, created_at ASC);

CREATE UNIQUE INDEX idx_unit_sync_state_node
        ON unit_sync_state (node_id);

CREATE INDEX idx_unit_versions_unit
        ON unit_versions (unit_id, version ASC);

CREATE INDEX idx_units_kind
        ON units (kind, created_at DESC);

CREATE INDEX idx_units_scope
        ON units (scope, scope_id, created_at DESC);

CREATE INDEX idx_workflow_runs_cache_completed
            ON workflow_runs_cache (completed_at DESC);

CREATE INDEX idx_workflow_versions_workflow
            ON workflow_versions (workflow_id, version DESC);

CREATE INDEX idx_workflows_updated_at
            ON workflows (updated_at DESC);

CREATE TABLE agent_graph_events (
            run_id        TEXT NOT NULL,
            session_id    TEXT NOT NULL DEFAULT '',
            node_id       TEXT NOT NULL DEFAULT '',
            seq           INTEGER NOT NULL,
            kind          TEXT NOT NULL,
            payload_json  TEXT NOT NULL DEFAULT 'null',
            ts_ns         INTEGER NOT NULL,
            PRIMARY KEY (run_id, seq)
        );

CREATE TABLE agent_graph_node_provenance (
            graph_id                    TEXT NOT NULL,
            node_id                     TEXT NOT NULL,
            kind                        TEXT NOT NULL DEFAULT '',
            manifest_version_at_author  TEXT NOT NULL DEFAULT '',
            fingerprint_at_author       TEXT NOT NULL DEFAULT '',
            PRIMARY KEY (graph_id, node_id)
        );

CREATE TABLE artifact_versions (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            artifact_id  TEXT NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE,
            version      INTEGER NOT NULL,
            content_hash TEXT NOT NULL,
            byte_size    INTEGER NOT NULL,
            mime_type    TEXT NOT NULL DEFAULT '',
            summary      TEXT,
            path         TEXT,
            created_at   INTEGER NOT NULL,
            UNIQUE (artifact_id, version)
        );

CREATE TABLE "artifacts" (
                    id              TEXT PRIMARY KEY,
                    session_id      TEXT NULL REFERENCES sessions(id) ON DELETE SET NULL,
                    project_id      TEXT NULL REFERENCES projects(id) ON DELETE SET NULL,
                    title           TEXT NOT NULL DEFAULT '',
                    mime_type       TEXT NOT NULL,
                    content_hash    TEXT NOT NULL,
                    byte_size       INTEGER NOT NULL,
                    source          TEXT NOT NULL CHECK (source IN ('code_block','tool_output','user_pin','model_output')),
                    source_ref_json TEXT NOT NULL DEFAULT '{}',
                    scope_kind      TEXT NOT NULL DEFAULT 'session' CHECK (scope_kind IN ('session','project','global')),
                    created_at      INTEGER NOT NULL
                );

CREATE TABLE branch_message_refs (
            branch_id       TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
            seq             INTEGER NOT NULL,
            parent_msg_id   TEXT NOT NULL,
            child_msg_id    TEXT NOT NULL DEFAULT '',
            PRIMARY KEY (branch_id, seq)
        );

CREATE TABLE branches (
            id                  TEXT PRIMARY KEY,
            parent_session_id   TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
            child_session_id    TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
            kind                TEXT NOT NULL DEFAULT 'fork',
            status              TEXT NOT NULL DEFAULT 'active',
            model_id            TEXT NOT NULL DEFAULT '',
            provider_id         TEXT NOT NULL DEFAULT '',
            title               TEXT NOT NULL DEFAULT '',
            task_hint           TEXT NOT NULL DEFAULT '',
            created_at          INTEGER NOT NULL,
            updated_at          INTEGER NOT NULL,
            merged_at           INTEGER,
            abandoned_at        INTEGER
        , subagent_branch INTEGER NOT NULL DEFAULT 0, recommendation_id TEXT NOT NULL DEFAULT '', advisor_signals TEXT NOT NULL DEFAULT '[]', parent_message_id TEXT NOT NULL DEFAULT '', branch_title TEXT NOT NULL DEFAULT '', creation_path TEXT NOT NULL DEFAULT 'unknown', parent_session_title TEXT NOT NULL DEFAULT '');

CREATE TABLE context_attachments (
            id              TEXT PRIMARY KEY,
            scope_kind      TEXT NOT NULL CHECK (scope_kind IN ('global','project','session')),
            scope_id        TEXT NOT NULL,
            content_source  TEXT NOT NULL,
            content         TEXT NOT NULL,
            kind            TEXT NOT NULL DEFAULT 'system',
            position        INTEGER NOT NULL DEFAULT 0,
            created_at      INTEGER NOT NULL
        , media_id TEXT NULL
            REFERENCES media_artifacts(id) ON DELETE SET NULL);

CREATE TABLE corpora (
            id          TEXT PRIMARY KEY,
            name        TEXT NOT NULL,
            scope       TEXT NOT NULL CHECK (scope IN ('global','project','session')),
            scope_id    TEXT NOT NULL DEFAULT '',
            tag         TEXT NOT NULL DEFAULT '',
            created_at  INTEGER NOT NULL,
            updated_at  INTEGER NOT NULL
        );

CREATE TABLE corpus_chunks (
            id          TEXT PRIMARY KEY,
            corpus_id   TEXT NOT NULL REFERENCES corpora(id) ON DELETE CASCADE,
            file_id     TEXT NOT NULL REFERENCES corpus_files(id) ON DELETE CASCADE,
            chunk_seq   INTEGER NOT NULL,
            text        TEXT NOT NULL,
            embedding   BLOB NOT NULL,
            line_start  INTEGER NOT NULL,
            line_end    INTEGER NOT NULL,
            created_at  INTEGER NOT NULL
        );

CREATE TABLE corpus_files (
            id            TEXT PRIMARY KEY,
            corpus_id     TEXT NOT NULL REFERENCES corpora(id) ON DELETE CASCADE,
            path          TEXT NOT NULL,
            sha256        TEXT NOT NULL,
            file_size     INTEGER NOT NULL,
            line_count    INTEGER NOT NULL,
            ingested_at   INTEGER NOT NULL
        );

CREATE TABLE cost_threshold_fired (
            year_month TEXT NOT NULL,
            pct        INTEGER NOT NULL,
            fired_at   INTEGER NOT NULL,
            PRIMARY KEY (year_month, pct)
        );

CREATE TABLE custom_endpoint_capabilities (
		endpoint    TEXT PRIMARY KEY,
		probed_at   INTEGER NOT NULL,
		matrix_json TEXT NOT NULL DEFAULT '{}'
	);

CREATE TABLE event_chain_heads (
    session_id        TEXT PRIMARY KEY,
    head_event_id     TEXT NOT NULL,
    head_payload_hash BLOB NOT NULL
);

CREATE TABLE events (
    event_id           TEXT PRIMARY KEY,
    session_id         TEXT,
    emitter_id         TEXT NOT NULL,
    kind               TEXT NOT NULL,
    emitted_at         INTEGER NOT NULL,
    payload            BLOB NOT NULL,
    payload_hash       BLOB NOT NULL,
    prev_hash          BLOB NOT NULL,
    redaction_summary  TEXT NOT NULL
, schema_version INTEGER NOT NULL DEFAULT 1);

CREATE VIRTUAL TABLE events_fts USING fts5(
    payload,
    content='events',
    content_rowid='rowid'
);

CREATE TABLE harness_meta (
    install_id          TEXT NOT NULL PRIMARY KEY,
    created_at          TEXT NOT NULL,
    libsql_version      TEXT NOT NULL DEFAULT '',
    sqlite_version      TEXT NOT NULL DEFAULT '',
    schema_version      INTEGER NOT NULL DEFAULT 0,
    encryption_status   TEXT NOT NULL DEFAULT 'disabled',
    wal_mode            INTEGER NOT NULL DEFAULT 1,
    foreign_keys_on     INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE harness_migrations (
    rowid                       INTEGER PRIMARY KEY AUTOINCREMENT,
    version                     INTEGER NOT NULL,
    id                          TEXT NOT NULL,
    applied_at                  TEXT NOT NULL,
    content_hash                TEXT NOT NULL,
    owning_mission              TEXT NOT NULL,
    action                      TEXT NOT NULL,
    rolled_back_from_version    INTEGER NULL
);

CREATE TABLE media_artifacts (
            id            TEXT PRIMARY KEY,
            content_hash  TEXT NOT NULL,
            media_type    TEXT NOT NULL,
            byte_size     INTEGER NOT NULL,
            original_name TEXT NOT NULL DEFAULT '',
            created_at    INTEGER NOT NULL
        , image_width  INTEGER NOT NULL DEFAULT 0, image_height INTEGER NOT NULL DEFAULT 0, page_count   INTEGER NOT NULL DEFAULT 0);

CREATE TABLE memory_hook_journal (
            id            TEXT PRIMARY KEY,
            run_id        TEXT,
            session_id    TEXT,
            node_id       TEXT,
            boundary      TEXT NOT NULL,
            scope         TEXT NOT NULL,
            scope_id      TEXT,
            chunk_id      TEXT,
            written       INTEGER NOT NULL DEFAULT 0,
            deduped       INTEGER NOT NULL DEFAULT 0,
            skipped       INTEGER NOT NULL DEFAULT 0,
            skip_reason   TEXT NOT NULL DEFAULT '',
            content_hash  TEXT NOT NULL DEFAULT '',
            ts_ns         INTEGER NOT NULL
        );

CREATE VIRTUAL TABLE messages_fts
    USING fts5(
        content,
        content='session_messages',
        content_rowid='rowid',
        tokenize='porter unicode61'
    );

CREATE TABLE projects (
            id          TEXT PRIMARY KEY,
            name        TEXT NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            created_at  INTEGER NOT NULL,
            updated_at  INTEGER NOT NULL
        , autonomy_level INTEGER, autonomy_overrides TEXT);

CREATE TABLE provider_capabilities (
            profile_id                TEXT NOT NULL,
            model_id                  TEXT NOT NULL,
            fetched_at                INTEGER NOT NULL,
            flags_json                TEXT NOT NULL,
            capability_schema_version INTEGER NOT NULL,
            PRIMARY KEY (profile_id, model_id)
        );

CREATE TABLE redaction_rules (
    rule_id      TEXT PRIMARY KEY,
    kind         TEXT NOT NULL CHECK (kind IN ('pattern','field_path','kind_specific')),
    definition   TEXT NOT NULL,
    enabled_at   INTEGER NOT NULL,
    disabled_at  INTEGER
);

CREATE TABLE retention_config (
    version       INTEGER PRIMARY KEY,
    policy        TEXT NOT NULL,
    effective_at  INTEGER NOT NULL
);

CREATE TABLE saved_audit_queries (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    query_json  TEXT NOT NULL,
    created_at  INTEGER NOT NULL,
    user_id     TEXT NOT NULL DEFAULT '',
    UNIQUE(name, user_id)
);

CREATE TABLE scheduled_chat_run_history (
            id              TEXT PRIMARY KEY,
            chat_run_id     TEXT NOT NULL
                REFERENCES scheduled_chat_runs(id) ON DELETE CASCADE,
            session_id      TEXT NOT NULL DEFAULT '',
            status          TEXT NOT NULL DEFAULT 'completed',
            started_at      INTEGER NOT NULL,
            ended_at        INTEGER,
            output_snippet  TEXT NOT NULL DEFAULT '',
            error           TEXT NOT NULL DEFAULT ''
        );

CREATE TABLE scheduled_chat_runs (
            id               TEXT PRIMARY KEY,
            name             TEXT NOT NULL DEFAULT '',
            prompt_template  TEXT NOT NULL DEFAULT '',
            cron             TEXT NOT NULL,
            timezone         TEXT NOT NULL DEFAULT '',
            model            TEXT NOT NULL DEFAULT '',
            output_sink      TEXT NOT NULL DEFAULT 'banner',
            enabled          INTEGER NOT NULL DEFAULT 1,
            created_at       INTEGER NOT NULL,
            updated_at       INTEGER NOT NULL
        );

CREATE TABLE session_messages (
            id          TEXT PRIMARY KEY,
            session_id  TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
            sequence    INTEGER NOT NULL,
            role        TEXT NOT NULL,
            content     TEXT NOT NULL,
            tool_calls  TEXT,
            created_at  INTEGER NOT NULL
        , content_json TEXT NULL, compacted_into_id TEXT NULL, compacted_at INTEGER NULL, archived_at INTEGER NULL, prompt_tokens INTEGER, completion_tokens INTEGER, cost_usd REAL, cost_source TEXT, streaming_failed_at INTEGER, streaming_failure_kind TEXT, streaming_recoverable INTEGER, continuation_of TEXT, knobs_override TEXT, kind TEXT, move_index INTEGER, turn_span_id TEXT, model_tool_args TEXT);

CREATE TABLE sessions (
            id              TEXT PRIMARY KEY,
            name            TEXT NOT NULL,
            created_at      INTEGER NOT NULL,
            updated_at      INTEGER NOT NULL,
            last_active_at  INTEGER NOT NULL,
            position        INTEGER NOT NULL,
            draft           TEXT NOT NULL DEFAULT '',
            scroll_position INTEGER NOT NULL DEFAULT 0,
            archived_at     INTEGER,
            system_prompt   TEXT NOT NULL DEFAULT '',
            context_kind    TEXT NOT NULL DEFAULT 'system',
            project_id      TEXT NULL REFERENCES projects(id) ON DELETE SET NULL
        , auto_titled INTEGER NOT NULL DEFAULT 0, branch_advisor_dismissed INTEGER NOT NULL DEFAULT 0, autonomy_level INTEGER, autonomy_overrides TEXT, kind TEXT NOT NULL DEFAULT 'chat', last_usage_json TEXT, knobs_default TEXT, move_history_mode TEXT);

CREATE TABLE slash_commands_user (
		name             TEXT PRIMARY KEY,
		scope            TEXT NOT NULL,
		project_id       TEXT,
		kind             TEXT NOT NULL,
		description      TEXT NOT NULL DEFAULT '',
		when_to_use      TEXT NOT NULL DEFAULT '',
		does_not_handle  TEXT NOT NULL DEFAULT '',
		model_invokable  INTEGER NOT NULL DEFAULT 0,
		payload_path     TEXT NOT NULL,
		icon             TEXT,
		hidden_from_panel INTEGER NOT NULL DEFAULT 0,
		created_at       INTEGER NOT NULL,
		updated_at       INTEGER NOT NULL
	);

CREATE TABLE stream_checkpoints (
            session_id  TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
            sub_id      TEXT NOT NULL,
            text        TEXT NOT NULL,
            has_tool    INTEGER NOT NULL DEFAULT 0,
            updated_at  INTEGER NOT NULL,
            PRIMARY KEY (session_id, sub_id)
        );

CREATE TABLE tasks (
	  id               TEXT PRIMARY KEY,
	  kind             TEXT NOT NULL,
	  owner_session_id TEXT,
	  cmd              TEXT,
	  description      TEXT,
	  status           TEXT NOT NULL,
	  exit_code        INTEGER,
	  started_at       INTEGER NOT NULL,
	  ended_at         INTEGER
	);

CREATE TABLE telemetry_logs (
            severity        INTEGER NOT NULL,
            body            TEXT NOT NULL,
            attributes_json TEXT NOT NULL DEFAULT '{}',
            trace_id        TEXT,
            span_id         TEXT,
            ts_ns           INTEGER NOT NULL
        );

CREATE TABLE telemetry_metrics (
            name            TEXT NOT NULL,
            kind            TEXT NOT NULL,
            attributes_json TEXT NOT NULL DEFAULT '{}',
            value           REAL NOT NULL,
            ts_ns           INTEGER NOT NULL
        );

CREATE TABLE telemetry_spans (
            trace_id        TEXT NOT NULL,
            span_id         TEXT PRIMARY KEY,
            parent_span_id  TEXT,
            name            TEXT NOT NULL,
            kind            TEXT NOT NULL,
            start_ns        INTEGER NOT NULL,
            end_ns          INTEGER NOT NULL,
            status_code     INTEGER NOT NULL,
            status_message  TEXT NOT NULL DEFAULT '',
            attributes_json TEXT NOT NULL DEFAULT '{}',
            events_json     TEXT NOT NULL DEFAULT '[]'
        );

CREATE TABLE trust_anchors (
		anchor_id           TEXT PRIMARY KEY,
		kind                INTEGER NOT NULL DEFAULT 0,
		org_id              TEXT NOT NULL DEFAULT '',
		peer_id             TEXT NOT NULL DEFAULT '',
		algorithm           TEXT NOT NULL DEFAULT '',
		installed_at        INTEGER NOT NULL,
		installed_by        TEXT NOT NULL DEFAULT '',
		metadata            TEXT NOT NULL DEFAULT '{}',
		pubkey_algorithm    TEXT NOT NULL DEFAULT '',
		pubkey_bytes        BLOB NOT NULL,
		pubkey_fingerprint  TEXT NOT NULL DEFAULT '',
		prevkey_algorithm   TEXT,
		prevkey_bytes       BLOB,
		prevkey_fingerprint TEXT,
		overlap_ends        INTEGER,
		removed             INTEGER NOT NULL DEFAULT 0
	);

CREATE TABLE "unit_edges" (
        id          TEXT PRIMARY KEY,
        from_id     TEXT NOT NULL REFERENCES units(id) ON DELETE CASCADE,
        to_id       TEXT NOT NULL REFERENCES units(id) ON DELETE CASCADE,
        kind        TEXT NOT NULL CHECK (kind IN ('references','derived_from','promoted_from','supersedes','conflicts_with')),
        version     INTEGER NOT NULL DEFAULT 1,
        created_at  INTEGER NOT NULL
    );

CREATE TABLE unit_sync_state (
        unit_id         TEXT PRIMARY KEY REFERENCES units(id) ON DELETE CASCADE,
        node_id         TEXT NOT NULL DEFAULT '',
        synced_version  INTEGER NOT NULL DEFAULT 0,
        classification  TEXT NOT NULL DEFAULT '',
        last_synced     INTEGER NOT NULL
    , synced_server_version INTEGER NOT NULL DEFAULT 0, synced_local_version INTEGER NOT NULL DEFAULT 0);

CREATE TABLE unit_versions (
        id          INTEGER PRIMARY KEY AUTOINCREMENT,
        unit_id     TEXT NOT NULL REFERENCES units(id) ON DELETE CASCADE,
        version     INTEGER NOT NULL,
        body        TEXT NOT NULL DEFAULT '',
        metadata    TEXT NOT NULL DEFAULT '{}',
        created_at  INTEGER NOT NULL,
        UNIQUE (unit_id, version)
    );

CREATE TABLE units (
        id              TEXT PRIMARY KEY,
        kind            TEXT NOT NULL CHECK (kind IN ('root','doc','artifact','snippet','tool_output')),
        scope           TEXT NOT NULL CHECK (scope IN ('global','project','session')),
        scope_id        TEXT NOT NULL DEFAULT '',
        classification  TEXT NOT NULL CHECK (classification IN ('personal','team','org')),
        version         INTEGER NOT NULL DEFAULT 0,
        load_policy     TEXT NOT NULL CHECK (load_policy IN ('always','on_demand')),
        title           TEXT NOT NULL DEFAULT '',
        body            TEXT NOT NULL DEFAULT '',
        metadata        TEXT NOT NULL DEFAULT '{}',
        created_at      INTEGER NOT NULL,
        updated_at      INTEGER NOT NULL
    );

CREATE TABLE workflow_runs_cache (
            workflow_id   TEXT NOT NULL,
            inputs_hash   TEXT NOT NULL,
            output_json   TEXT NOT NULL,
            completed_at  INTEGER NOT NULL,
            PRIMARY KEY (workflow_id, inputs_hash)
        );

CREATE TABLE workflow_schedules (
            workflow_id   TEXT PRIMARY KEY
                REFERENCES workflows(id) ON DELETE CASCADE,
            cron          TEXT NOT NULL,
            timezone      TEXT NOT NULL DEFAULT '',
            enabled       INTEGER NOT NULL DEFAULT 1,
            last_fired_at INTEGER,
            last_run_id   TEXT
        );

CREATE TABLE workflow_versions (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            workflow_id  TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
            version      INTEGER NOT NULL,
            yaml_source  TEXT NOT NULL,
            hash         TEXT NOT NULL,
            created_at   INTEGER NOT NULL,
            UNIQUE (workflow_id, version)
        );

CREATE TABLE workflows (
            id           TEXT PRIMARY KEY,
            name         TEXT NOT NULL DEFAULT '',
            description  TEXT NOT NULL DEFAULT '',
            yaml_source  TEXT NOT NULL,
            version      INTEGER NOT NULL DEFAULT 1,
            hash         TEXT NOT NULL,
            created_at   INTEGER NOT NULL,
            updated_at   INTEGER NOT NULL
        );

CREATE TRIGGER events_ai AFTER INSERT ON events BEGIN
    INSERT INTO events_fts(rowid, payload) VALUES (new.rowid, new.payload);
END;

CREATE TRIGGER events_fts_ad AFTER DELETE ON events BEGIN
    INSERT INTO events_fts(events_fts, rowid, payload) VALUES ('delete', old.rowid, old.payload);
END;

CREATE TRIGGER events_fts_au AFTER UPDATE ON events BEGIN
    INSERT INTO events_fts(events_fts, rowid, payload) VALUES ('delete', old.rowid, old.payload);
    INSERT INTO events_fts(rowid, payload) VALUES (new.rowid, new.payload);
END;

CREATE TRIGGER messages_fts_ad
    AFTER DELETE ON session_messages WHEN old.role <> 'tool' BEGIN
        INSERT INTO messages_fts(messages_fts, rowid, content)
            VALUES ('delete', old.rowid, old.content);
    END;

CREATE TRIGGER messages_fts_ai
    AFTER INSERT ON session_messages WHEN new.role <> 'tool' BEGIN
        INSERT INTO messages_fts(rowid, content)
            VALUES (new.rowid, new.content);
    END;

CREATE TRIGGER messages_fts_au
    AFTER UPDATE ON session_messages BEGIN
        INSERT INTO messages_fts(messages_fts, rowid, content)
            SELECT 'delete', old.rowid, old.content WHERE old.role <> 'tool';
        INSERT INTO messages_fts(rowid, content)
            SELECT new.rowid, new.content WHERE new.role <> 'tool';
    END;

-- === DATA (sorted by table name, rows sorted by primary key) ===

INSERT INTO "artifact_versions" ("id", "artifact_id", "version", "content_hash", "byte_size", "mime_type", "summary", "path", "created_at") VALUES (1, 'seed-artifact-1', 1, 'seedhash1v1', 40, 'text/plain', 'seed v1', '/seed/v1', 1700000000410);
INSERT INTO "artifact_versions" ("id", "artifact_id", "version", "content_hash", "byte_size", "mime_type", "summary", "path", "created_at") VALUES (2, 'seed-artifact-1', 2, 'seedhash1v2', 42, 'text/plain', 'seed v2', '/seed/v2', 1700000000420);

INSERT INTO "artifacts" ("id", "session_id", "project_id", "title", "mime_type", "content_hash", "byte_size", "source", "source_ref_json", "scope_kind", "created_at") VALUES ('seed-artifact-1', 'seed-session-1', NULL, 'Seed Artifact', 'text/plain', 'seedhash1', 42, 'user_pin', '{}', 'session', 1700000000400);

INSERT INTO "branches" ("id", "parent_session_id", "child_session_id", "kind", "status", "model_id", "provider_id", "title", "task_hint", "created_at", "updated_at", "merged_at", "abandoned_at", "subagent_branch", "recommendation_id", "advisor_signals", "parent_message_id", "branch_title", "creation_path", "parent_session_title") VALUES ('seed-branch-1', 'seed-session-1', 'seed-session-2', 'fork', 'active', 'seed-model', 'seed-provider', 'Seed Branch', '', 1700000000500, 1700000000500, NULL, NULL, 0, '', '[]', '', '', 'unknown', '');

INSERT INTO "context_attachments" ("id", "scope_kind", "scope_id", "content_source", "content", "kind", "position", "created_at", "media_id") VALUES ('seed-attach-1', 'session', 'seed-session-1', 'manual', 'seed attachment content', 'system', 0, 1700000001000, NULL);

INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (1, 1, 'storage/0001-harness-meta', '1970-01-01T00:00:00Z', '35e9769cfbd277ec6d14b825b98e98505df1f9c16bc35cf956a49b4bfe06b978', 'storage', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (2, 2, 'storage/0002-harness-migrations-ledger', '1970-01-01T00:00:00Z', '9bdf808f5d99c2fd2fc263ad2200a3b9e92028d7f94015083cfa8c245a42aaeb', 'storage', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (3, 300, 'sessions/0300-init', '1970-01-01T00:00:00Z', '1e44aba155b3b446aa15b9ba41be6444b470b79be341a89fe885d9b86ee8bf90', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (4, 301, 'sessions/0301-context-attachments', '1970-01-01T00:00:00Z', 'ba6b8c990cdf20f2569a831dab2f121627b62041e9539fdfe3215214df9ec48e', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (5, 302, 'sessions/0302-content-json', '1970-01-01T00:00:00Z', 'f3ab13be2442710b82a972503645aed19aba5421a1492baa3b7af6ece83ef4d9', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (6, 303, 'sessions/0303-artifacts', '1970-01-01T00:00:00Z', '295bad99618f36d6a07a66b5dec9136411435f9eb505765929b60a3d00195d1a', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (7, 304, 'sessions/0304-artifacts-promote', '1970-01-01T00:00:00Z', '376a66ebc5241cf39474ec78ca4ed2bdd7fdb2456346484bba1fa49ff0eeb3d1', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (8, 305, 'sessions/0305-telemetry', '1970-01-01T00:00:00Z', '80fac6054b590f9f6f5fe0bef66825e488cc3fbdd502a802569aac6b85602cf8', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (9, 306, 'sessions/0306-branches', '1970-01-01T00:00:00Z', '8c25af20fd1f4b7103a3364feee3183dcb38a9f7d67f6579d00351fe14c23de6', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (10, 307, 'sessions/0307-corpora', '1970-01-01T00:00:00Z', '76d87a51f0d19828e3a3671f95c27d178a8ee8e111ed8ce7b899d6ba7df6cbcc', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (11, 308, 'sessions/0308-memory-hook-journal', '1970-01-01T00:00:00Z', 'd94c052cd3fd889263354210e8c1729f4895ec14f5b92aeec804f099d859b838', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (12, 309, 'sessions/0309-agent-graph-events', '1970-01-01T00:00:00Z', '8f3e18f2a0774b54f650763e5a4bb02a6e5c7b80caa945133a5c7b15d420e30a', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (13, 310, 'sessions/0310-compaction', '1970-01-01T00:00:00Z', '769c56c2469f3370f39274c5a7d0817ef2ed8cf07ef0b7e56e5a0dac11ad1d5f', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (14, 311, 'sessions/0311-auto-titled', '1970-01-01T00:00:00Z', '31b90ce902c29a7e2f54329300dc3c3f5c60707a2f554ef464f0ae8c1d77dc7b', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (15, 312, 'sessions/0312-search-fts5', '1970-01-01T00:00:00Z', '9a389dd10c71efb263657281b62eb21569c8310157118c017591cc8da3f4fb0e', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (16, 313, 'sessions/0313-subagent-metadata', '1970-01-01T00:00:00Z', '23cbf1bf8c278b5fb1a9fecc552e55c48037422e6b2e86455d15837961b22a3c', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (17, 314, 'sessions/0314-session-usage-columns', '1970-01-01T00:00:00Z', '45b62f3da450a08f0342d7325b6587700b65a2e057f399f26437cd59f4a04273', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (18, 315, 'sessions/0315-cost-threshold-fired', '1970-01-01T00:00:00Z', 'bcb997892566f3cf9644b08bb34be87e788ad1b8ed8106f51c2508c2d2f6a4df', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (19, 316, 'sessions/0316-autonomy-columns', '1970-01-01T00:00:00Z', '026551e87be77871358d3e25dc165c632f669ceb2545d1d04d0acd52fd1a684c', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (20, 317, 'sessions/0317-streaming-resume-columns', '1970-01-01T00:00:00Z', 'e89244ed7fafe77cd0921718b59a3d5ba3b4aafbdf4ea5dc71a3d3eb47784665', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (21, 318, 'sessions/0318-kind', '1970-01-01T00:00:00Z', 'ab1b429af5ad3ab5ad6b3bb0355f6983b1b6b376a171429ec7875bb7611fa1d0', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (22, 319, 'sessions/0319-workflows', '1970-01-01T00:00:00Z', 'f25903f7669f5f495abfcc9fcdaa5f12b7144a0bc485c6fd3bd313369b9f547c', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (23, 320, 'sessions/0320-workflow-runs-cache', '1970-01-01T00:00:00Z', 'f41146c1444ad208713f5cfae0456a3b9724bf845b22c3671d5b8bbf328c697e', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (24, 321, 'sessions/0321-workflow-schedules', '1970-01-01T00:00:00Z', '48fccc7c64f19f80d20c9974ad1eae26c8594892ec7f9a992ee523e7f88a9393', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (25, 322, 'sessions/0322-last-usage-json', '1970-01-01T00:00:00Z', '95cc763885275a99bc7203e92b85a645e522449e366cf58a3706f03ad0c3c340', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (26, 323, 'sessions/0323-branch-display-meta', '1970-01-01T00:00:00Z', '58b5dff10fecd67babaed1cdd0fbadcfb4a57907120d2c68da464c9fa803f701', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (27, 324, 'sessions/0324-artifact-versions', '1970-01-01T00:00:00Z', '8a02f2dd0b44139e72f3dfa41cba28cf18f99be2416a63702a9f6742910de341', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (28, 325, 'sessions/0325-scheduled-chat-runs', '1970-01-01T00:00:00Z', '14313d8f5bb6fa3c4fcf525f41f00ef44a5da81ee8c7eb245ef58bc769b46f68', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (29, 326, 'sessions/0326-manifest-provenance', '1970-01-01T00:00:00Z', 'deb31c3e7a852cc4f391d17951f4af470660b29ad1e70ef98e36d859d140cf6f', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (30, 327, 'sessions/0327-source-model-output', '1970-01-01T00:00:00Z', '37b40af11a0d0561bf19403714092a67908e64f0b31ec04e6719e9838e572a5e', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (31, 328, 'sessions/0328-media-artifact-meta', '1970-01-01T00:00:00Z', 'fb78f336a3c6702fcc92b87e8f163416948d4cf21561429e5b1d3ad21c185171', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (32, 329, 'sessions/0329-provider-capabilities', '1970-01-01T00:00:00Z', '88bca5a9b11ce996f8a24c186fafa0b121bca37e96067e7dfd9d399382846353', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (33, 330, 'sessions/0330-knobs', '1970-01-01T00:00:00Z', '3dd64de4e94f28668d9c3d866c10077c8f3b8ffd101320352dbb5a03c5f1ee5b', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (34, 331, 'sessions/0331-custom-endpoint-capabilities', '1970-01-01T00:00:00Z', '14f7ca55e0ee66a12fcda8b09a609d6bedaa89069ccabae0783387868531e82d', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (39, 1000, 'user-slash-commands/1000-slash-commands-user', '1970-01-01T00:00:00Z', '9e54be68c3489a46dfd49cb42fa7a0d6d5c8dd3ad7fff4bafe99c07df580c9ab', 'user-slash-commands', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (40, 1100, 'units/1100-init', '1970-01-01T00:00:00Z', '3c15a451bf4b5489d4c0233aa73f5e8dde138ffbcf7e3404117b7d480d27956e', 'units', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (41, 1101, 'units/1101-sync-state', '1970-01-01T00:00:00Z', 'c6b3d564e78e8148efe3a284a5aabec9bc7c96f21a0afd010391fe8ca8ff90f0', 'units', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (42, 1102, 'units/1102-sync-state-baselines', '1970-01-01T00:00:00Z', '0fdff2250343e07fae5a237dec4c16f28281d9b80c98a2319964a35b564e5f06', 'units', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (43, 1103, 'units/1103-conflict-edge', '1970-01-01T00:00:00Z', 'ac0d96ab0c2839b2a393416eb4f3c5cbf711588d7618f4c1051796f6ef5355cf', 'units', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (44, 332, 'sessions/0332-artifacts-global-scope', '1970-01-01T00:00:00Z', '0c1d72a1227911471c653b2357a2b7362d250c8e66ec4e869b44b2dc326c648e', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (45, 333, 'sessions/0333-transcript-moves', '1970-01-01T00:00:00Z', '03a76f3897b9bd902f2a8d2d5cd16233f63a7ae16234dca7eaeaf689377a0ea3', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (46, 334, 'sessions/0334-move-fidelity-columns', '1970-01-01T00:00:00Z', 'ebb259dae547c592f4c9057a1a5362f253f4cb241a6296da82d912ad963a1ff4', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (47, 335, 'sessions/0335-search-fts-exclude-tool-rows', '1970-01-01T00:00:00Z', 'd80a002a921c17810a75ecfacb84240ffe4dd0f8bfdfd82cf844facc639167ce', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (48, 100, 'event-log/0100-events', '1970-01-01T00:00:00Z', 'c01773eb8487e34e1ad9141675ba2039f22dd8e61c71a3040beb3cbd994ec7ce', 'event-log', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (49, 101, 'event-log/0101-event-chain-heads', '1970-01-01T00:00:00Z', '6f64a024308560ce60cf7352830b1fa69ac31d6f621c135b43250b7c2aed6dbd', 'event-log', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (50, 102, 'event-log/0102-redaction-rules', '1970-01-01T00:00:00Z', '11570661fa66131e209a59136f2c011b48deb1ab2dee752c189bd3962e0094e9', 'event-log', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (51, 103, 'event-log/0103-retention-config', '1970-01-01T00:00:00Z', '42fb7b40e0e92dcccec64921c064a2b6b840c8683bf32f7f88de810455340a54', 'event-log', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (52, 104, 'event-log/0104-schema-version', '1970-01-01T00:00:00Z', '6e82100a83644190bb2c6b3efed38c72e52d8affaa41b8201efd2f67ea56c564', 'event-log', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (53, 105, 'event-log/0105-saved-audit-queries', '1970-01-01T00:00:00Z', 'd3c73c44734bc598e17d718118c3e7d0945d7ec2ae73f4ef57515ecc8765a0fb', 'event-log', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (54, 336, 'sessions/0336-stream-checkpoints', '1970-01-01T00:00:00Z', 'f0a42dbf6c7030a0d178cb8e13dfad1a8bbec3821fe94c172403bc0544a94987', 'sessions', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (55, 700, 'bundle/700-trust-anchors-init', '1970-01-01T00:00:00Z', 'fad2eb1438ee9895ddf35f2a4862f6219a9f5df2ba80a5c4284c5805deff7fe5', 'bundle', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (56, 106, 'event-log/0106-events-fts-sync', '1970-01-01T00:00:00Z', '772ade1d9d05422b63762c48f18a71d1e664aa01a3d894967f6c32f5ff12bd03', 'event-log', 'applied', NULL);
INSERT INTO "harness_migrations" ("rowid", "version", "id", "applied_at", "content_hash", "owning_mission", "action", "rolled_back_from_version") VALUES (57, 1200, 'tasks/1200-tasks-init', '1970-01-01T00:00:00Z', '8a95bb9a47becdba5a8cebdff817f24757e7abc52f83357212c73d7195a9539f', 'tasks', 'applied', NULL);

INSERT INTO "projects" ("id", "name", "description", "created_at", "updated_at", "autonomy_level", "autonomy_overrides") VALUES ('seed-project-1', 'Seed Project', 'synthetic seed project', 1700000000000, 1700000000000, NULL, NULL);

INSERT INTO "retention_config" ("version", "policy", "effective_at") VALUES (1, '{"kind":"keep_forever"}', 0);

INSERT INTO "scheduled_chat_run_history" ("id", "chat_run_id", "session_id", "status", "started_at", "ended_at", "output_snippet", "error") VALUES ('seed-schedrun-hist-1', 'seed-schedrun-1', 'seed-session-1', 'completed', 1700000000900, 1700000000950, 'Hello!', '');

INSERT INTO "scheduled_chat_runs" ("id", "name", "prompt_template", "cron", "timezone", "model", "output_sink", "enabled", "created_at", "updated_at") VALUES ('seed-schedrun-1', 'Seed Scheduled Run', 'Say hello.', '0 9 * * *', 'UTC', 'seed-model', 'banner', 1, 1700000000800, 1700000000800);

INSERT INTO "session_messages" ("id", "session_id", "sequence", "role", "content", "tool_calls", "created_at", "content_json", "compacted_into_id", "compacted_at", "archived_at", "prompt_tokens", "completion_tokens", "cost_usd", "cost_source", "streaming_failed_at", "streaming_failure_kind", "streaming_recoverable", "continuation_of", "knobs_override", "kind", "move_index", "turn_span_id", "model_tool_args") VALUES ('seed-msg-1', 'seed-session-1', 0, 'user', 'What is the kameas upgrade snapshot mechanism?', NULL, 1700000000100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "session_messages" ("id", "session_id", "sequence", "role", "content", "tool_calls", "created_at", "content_json", "compacted_into_id", "compacted_at", "archived_at", "prompt_tokens", "completion_tokens", "cost_usd", "cost_source", "streaming_failed_at", "streaming_failure_kind", "streaming_recoverable", "continuation_of", "knobs_override", "kind", "move_index", "turn_span_id", "model_tool_args") VALUES ('seed-msg-2', 'seed-session-1', 1, 'assistant', 'It replays committed per-tag dumps through production Open.', NULL, 1700000000200, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "session_messages" ("id", "session_id", "sequence", "role", "content", "tool_calls", "created_at", "content_json", "compacted_into_id", "compacted_at", "archived_at", "prompt_tokens", "completion_tokens", "cost_usd", "cost_source", "streaming_failed_at", "streaming_failure_kind", "streaming_recoverable", "continuation_of", "knobs_override", "kind", "move_index", "turn_span_id", "model_tool_args") VALUES ('seed-msg-3', 'seed-session-1', 2, 'user', 'Great, thanks.', NULL, 1700000000300, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO "sessions" ("id", "name", "created_at", "updated_at", "last_active_at", "position", "draft", "scroll_position", "archived_at", "system_prompt", "context_kind", "project_id", "auto_titled", "branch_advisor_dismissed", "autonomy_level", "autonomy_overrides", "kind", "last_usage_json", "knobs_default", "move_history_mode") VALUES ('seed-session-1', 'Seed Session One', 1700000000000, 1700000000000, 1700000000000, 0, '', 0, NULL, 'You are a helpful assistant.', 'system', 'seed-project-1', 0, 0, NULL, NULL, 'chat', NULL, NULL, NULL);
INSERT INTO "sessions" ("id", "name", "created_at", "updated_at", "last_active_at", "position", "draft", "scroll_position", "archived_at", "system_prompt", "context_kind", "project_id", "auto_titled", "branch_advisor_dismissed", "autonomy_level", "autonomy_overrides", "kind", "last_usage_json", "knobs_default", "move_history_mode") VALUES ('seed-session-2', 'Seed Session Two (branch child)', 1700000001000, 1700000001000, 1700000001000, 1, '', 0, NULL, '', 'system', NULL, 0, 0, NULL, NULL, 'chat', NULL, NULL, NULL);

INSERT INTO "slash_commands_user" ("name", "scope", "project_id", "kind", "description", "when_to_use", "does_not_handle", "model_invokable", "payload_path", "icon", "hidden_from_panel", "created_at", "updated_at") VALUES ('seed-cmd', 'user', NULL, 'prompt', 'seed slash command', 'when seeding', 'production traffic', 0, '/seed/cmd.md', NULL, 0, 1700000001100, 1700000001100);

INSERT INTO "unit_edges" ("id", "from_id", "to_id", "kind", "version", "created_at") VALUES ('seed-edge-1', 'seed-unit-1', 'seed-unit-2', 'references', 1, 1700000001400);

INSERT INTO "units" ("id", "kind", "scope", "scope_id", "classification", "version", "load_policy", "title", "body", "metadata", "created_at", "updated_at") VALUES ('seed-unit-1', 'doc', 'session', 'seed-session-1', 'personal', 1, 'always', 'Seed Unit One', 'seed unit body one', '{}', 1700000001200, 1700000001200);
INSERT INTO "units" ("id", "kind", "scope", "scope_id", "classification", "version", "load_policy", "title", "body", "metadata", "created_at", "updated_at") VALUES ('seed-unit-2', 'doc', 'session', 'seed-session-1', 'personal', 1, 'on_demand', 'Seed Unit Two', 'seed unit body two', '{}', 1700000001300, 1700000001300);

INSERT INTO "workflow_runs_cache" ("workflow_id", "inputs_hash", "output_json", "completed_at") VALUES ('seed-workflow-1', 'seedinputshash1', '{"ok":true}', 1700000000700);

INSERT INTO "workflow_versions" ("id", "workflow_id", "version", "yaml_source", "hash", "created_at") VALUES (1, 'seed-workflow-1', 1, 'name: seed\nsteps: []\n', 'seedworkflowhash1', 1700000000600);

INSERT INTO "workflows" ("id", "name", "description", "yaml_source", "version", "hash", "created_at", "updated_at") VALUES ('seed-workflow-1', 'Seed Workflow', 'synthetic seed workflow', 'name: seed\nsteps: []\n', 1, 'seedworkflowhash1', 1700000000600, 1700000000600);

