package docs

import (
	"fmt"
	"html"
	"strings"
	"time"
)

// Self-contained HTML pages (spec 092 FR-015, FR-021).
//
// The export is one file with no external references of any kind. That is
// cheap to guarantee because the body is already in Sanitize's canonical
// form — only data: images, https/mailto links, and inline styles from the
// property allowlist survive — and the page chrome added here is inline.
// The body is sanitized again anyway: the exporter is also the future
// publish payload (FR-021), and a second pass over an idempotent sanitizer
// costs one parse.
//
// The page carries its own restrictive Content-Security-Policy. A file
// opened from disk, served by a customer's own static web server, or
// served by Fleet Sites all get the same posture from the document itself:
// no script, no network fetch, no form submission, no base-URL rewrite.
// That is what lets a knowledge site built from these pages be served by
// infrastructure Kameas does not control (constitution §IX.5 — SaaS to
// self-hosted must work at any time) without trusting that server's
// headers.

// pageCSP is the policy every exported page declares. img-src data: is the
// only fetch-like permission, and the sanitizer already restricts images to
// raster data URIs.
const pageCSP = "default-src 'none'; img-src data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"

// generator names the producer in the export manifest comment.
const generator = "kenaz-harness core/docs"

// pageStyle is the minimal prose stylesheet for exported pages. It is
// deliberately plain: a document's look is the reader's concern, and a
// customer self-hosting the site can restyle it without touching bodies.
const pageStyle = `body{margin:0;background:#fbfaf7;color:#1d1d1b;font:16px/1.6 Georgia,"Times New Roman",serif}` +
	`main{max-width:46rem;margin:0 auto;padding:2.5rem 1.25rem 4rem}` +
	`nav{font:14px/1.4 -apple-system,"Segoe UI",sans-serif;margin-bottom:2rem}` +
	`nav a{color:#5b4b8a}` +
	`h1,h2,h3,h4{line-height:1.25}` +
	`pre{overflow:auto;background:#f1efe9;padding:.75rem;border-radius:4px}` +
	`code{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:.92em}` +
	`table{border-collapse:collapse;width:100%}th,td{border:1px solid #d9d5cb;padding:.35rem .5rem;text-align:left}` +
	`img{max-width:100%;height:auto}` +
	`blockquote{margin-left:0;padding-left:1rem;border-left:3px solid #d9d5cb;color:#4a4a45}` +
	`.meta{font:13px/1.4 -apple-system,"Segoe UI",sans-serif;color:#6b6b63}` +
	`ul.catalog{list-style:none;padding:0}ul.catalog li{padding:.6rem 0;border-bottom:1px solid #e7e3da}`

// documentPage renders doc as a single self-contained HTML page. nav is
// optional generated navigation markup (the knowledge site's back link).
// exportedAt is supplied by the caller so identical inputs produce
// identical bytes.
func documentPage(doc Document, exportedAt time.Time, nav string) ([]byte, error) {
	body, err := Sanitize(doc.Body)
	if err != nil {
		return nil, err
	}
	return []byte(renderPage(doc.Title, manifestComment(doc, exportedAt), nav, body)), nil
}

// manifestComment is the provenance header an exported page carries. It
// names the document by id and version only — never by title, which may be
// sensitive and is already the page <title> for anyone holding the file.
func manifestComment(doc Document, exportedAt time.Time) string {
	return fmt.Sprintf("<!-- generator: %s; document-id: %s; version: %d; content-sha256: %s; exported-at: %s -->",
		generator, commentSafe(doc.ID), doc.Version, commentSafe(doc.ContentSHA256),
		exportedAt.UTC().Format(time.RFC3339))
}

// renderPage assembles a complete page. title is plain text; nav and body
// are trusted markup (nav is generated by this package, body is sanitized).
func renderPage(title, comment, nav, body string) string {
	var b strings.Builder
	b.WriteString("<!doctype html>\n")
	b.WriteString(comment)
	b.WriteString("\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n")
	b.WriteString(`<meta http-equiv="Content-Security-Policy" content="` + pageCSP + `">` + "\n")
	b.WriteString(`<meta name="referrer" content="no-referrer">` + "\n")
	b.WriteString(`<meta name="viewport" content="width=device-width, initial-scale=1">` + "\n")
	b.WriteString("<title>" + html.EscapeString(title) + "</title>\n")
	b.WriteString("<style>" + pageStyle + "</style>\n</head>\n<body>\n<main>\n")
	if nav != "" {
		b.WriteString(nav)
		b.WriteString("\n")
	}
	b.WriteString(body)
	b.WriteString("\n</main>\n</body>\n</html>\n")
	return b.String()
}

// commentSafe keeps a value from terminating the manifest comment. Ids and
// hashes never contain "-->" in practice; this makes it impossible.
func commentSafe(s string) string {
	return strings.ReplaceAll(s, "--", "")
}
