// Code generated by core/fleet/cmd/gen-capability-keys; DO NOT EDIT.
// Source: core/fleet/capability.go AllCapabilities()
//
// To regenerate:
//   go generate ./core/fleet/...

export const CAPABILITY_KEYS = [
  'launcher_updates',
  'iso_distribution',
  'team_graph_sharing',
  'cross_team_graph_isolation',
  'cedar_preset_policies',
  'cedar_custom_policies',
  'opa_preset_policies',
  'opa_custom_rego',
  'attestation_tpm',
  'audit_log_immudb',
  'falco_monitoring',
  'zeek_network_verify',
  'emergency_lockdown',
  'kameas_verify_attestation',
  'personal_fleet_dashboard',
  'team_admin_dashboard',
  'policy_bundle_distribution',
  'isolated_fleet_infra',
  'sso_saml',
  'compliance_docs_soc2_summary',
  'compliance_docs_soc2_full',
  'compliance_docs_custom',
  'quarterly_attestation_reports',
  'sites_hosting',
  'context_sync',
  'team_session_handoff',
  'context_bootstrap',
  'org_graph_sharing',
] as const;

export type Capability = (typeof CAPABILITY_KEYS)[number];
