/**
 * harnessClient — the typed wrapper over `window.go.rpc.Bindings`.
 *
 * This is the ONLY module that knows about the Wails-generated surface.
 * Components and composables consume the nested view-scoped client objects
 * (e.g., `client.sessions.list()`); ESLint forbids `wailsjs/*` imports
 * outside this file (FR-007 / C-001 / plan §4.1).
 *
 * The Wails-generated bindings live under `frontend/wailsjs/go/rpc/Bindings`
 * once `wails generate module` runs against the `Bindings` struct. Until
 * regeneration, `WailsBindings` resolves through the runtime-attached
 * `window.go.rpc.Bindings` object Wails injects at boot. Both paths flow
 * through the same `WailsBindingsLike` interface so swapping in a fake
 * client is purely a TypeScript concern.
 */

import type {
  Session,
  Project,
  Provider,
  AddProviderInput,
  TestResult,
  ModelInfo,
  MCPServer,
  A2ACard,
  Job,
  SecretReference,
  ContextEntry,
  ContextNode,
  Bundle,
  Denial,
  AuditEntry,
  AuditFilter,
  ShellStatus,
  AppInfo,
  Settings,
  Theme,
  Message,
  MessageRole,
  MemoryChunk,
  Hook,
  BuiltinDescriptor,
} from './types';

/**
 * Minimal shape of the runtime-attached bindings. The full surface is
 * generated by Wails; we duck-type only what the client uses so the
 * frontend builds without `wails generate module` having run.
 */
interface WailsBindingsLike {
  ShellStatus(): Promise<ShellStatus>;
  AppInfo(): Promise<AppInfo>;
  LoadRoute(): Promise<string>;
  SaveRoute(route: string): Promise<void>;
  LogRouteChange(from: string, to: string): Promise<void>;
  LoadTheme(): Promise<string>;
  SaveTheme(theme: string): Promise<void>;

  Sessions_List(): Promise<Session[]>;
  Sessions_Get(id: string): Promise<Session>;
  Sessions_Create(name: string): Promise<Session>;
  Sessions_Rename(id: string, name: string): Promise<void>;
  Sessions_Delete(id: string): Promise<void>;
  Sessions_Reorder(ids: string[]): Promise<void>;
  Sessions_StartStream(id: string): Promise<string>;
  Sessions_StopStream(id: string): Promise<void>;
  Sessions_ListMessages(id: string): Promise<Message[]>;
  Sessions_AppendMessage(
    id: string,
    role: MessageRole,
    content: string,
  ): Promise<Message>;
  Sessions_SaveDraft(id: string, draft: string): Promise<void>;
  Sessions_LoadDraft(id: string): Promise<string>;
  Sessions_SetSystemPrompt(
    id: string,
    content: string,
    kind: 'system' | 'user_seed',
  ): Promise<void>;
  Sessions_MoveToProject(id: string, projectID: string): Promise<void>;

  Projects_List(): Promise<Project[]>;
  Projects_Get(id: string): Promise<Project>;
  Projects_Create(name: string, description: string): Promise<Project>;
  Projects_Rename(id: string, name: string): Promise<void>;
  Projects_UpdateDescription(id: string, description: string): Promise<void>;
  Projects_Delete(id: string, deleteSessions: boolean): Promise<void>;
  Projects_AddSession(projectID: string, sessionID: string): Promise<void>;
  Projects_RemoveSession(sessionID: string): Promise<void>;
  Projects_ListSessions(projectID: string): Promise<Session[]>;

  LLM_ListProviders(): Promise<Provider[]>;
  LLM_StartStream(
    profileID: string,
    sessionID: string,
    modelOverride: string,
  ): Promise<string>;
  LLM_StopStream(id: string): Promise<void>;
  LLM_AddProvider(input: AddProviderInput): Promise<void>;
  LLM_UpdateProvider(input: AddProviderInput): Promise<void>;
  LLM_RemoveProvider(id: string): Promise<void>;
  LLM_TestProvider(id: string): Promise<TestResult>;
  LLM_ListModels(kind: string, plaintextApiKey: string): Promise<ModelInfo[]>;

  MCP_ListServers(): Promise<MCPServer[]>;
  MCP_StartStream(id: string): Promise<string>;
  MCP_StopStream(id: string): Promise<void>;

  A2A_ListCards(): Promise<A2ACard[]>;
  A2A_StartStream(): Promise<string>;
  A2A_StopStream(id: string): Promise<void>;

  Workflow_ListJobs(): Promise<Job[]>;
  Workflow_StartStream(): Promise<string>;
  Workflow_StopStream(id: string): Promise<void>;

  Trust_ListSecretReferences(): Promise<SecretReference[]>;
  Trust_GetSecretReference(id: string): Promise<SecretReference>;

  Context_List(): Promise<ContextEntry[]>;
  Context_StartStream(): Promise<string>;
  Context_StopStream(id: string): Promise<void>;

  Contexts_List(): Promise<ContextNode>;
  Contexts_Get(path: string): Promise<string>;
  Contexts_Save(path: string, content: string): Promise<void>;
  Contexts_CreateFolder(path: string): Promise<void>;
  Contexts_Rename(oldPath: string, newPath: string): Promise<void>;
  Contexts_Delete(path: string): Promise<void>;
  Contexts_RecentlyApplied(limit: number): Promise<string[]>;
  Contexts_RootPath(): Promise<string>;

  Bundle_List(): Promise<Bundle[]>;
  Bundle_Get(id: string): Promise<Bundle>;

  Policy_Explain(input: Record<string, unknown>): Promise<Denial>;
  Policy_StartStream(): Promise<string>;
  Policy_StopStream(id: string): Promise<void>;

  Audit_ListEntries(filter: AuditFilter): Promise<AuditEntry[]>;
  Audit_VerifyEntry(id: string): Promise<boolean>;
  Audit_StartStream(filter: AuditFilter): Promise<string>;
  Audit_StopStream(id: string): Promise<void>;

  Settings_Get(): Promise<Settings>;
  Settings_Set(s: Settings): Promise<void>;
  Settings_GetMemory(): Promise<boolean>;
  Settings_SetMemory(enabled: boolean): Promise<void>;

  Memory_ListChunks(): Promise<MemoryChunk[]>;
  Memory_RememberMessage(sessionID: string, messageID: string): Promise<string>;
  Memory_Forget(id: string): Promise<void>;

  Hooks_List(): Promise<Hook[]>;
  Hooks_Get(id: string): Promise<Hook>;
  Hooks_Add(input: Hook): Promise<Hook>;
  Hooks_Update(input: Hook): Promise<void>;
  Hooks_Remove(id: string): Promise<void>;
  Hooks_AvailableBuiltins(): Promise<BuiltinDescriptor[]>;
  Hooks_InstallStarterMemory(): Promise<void>;
  Hooks_RemoveStarterMemory(): Promise<void>;
}

declare global {
  interface Window {
    go?: {
      rpc?: {
        Bindings?: WailsBindingsLike;
      };
    };
    runtime?: {
      EventsOn?: (
        topic: string,
        cb: (payload: unknown) => void,
      ) => () => void;
      EventsOff?: (topic: string) => void;
    };
  }
}

// ── view-scoped client interfaces ──────────────────────────────────────

export interface SessionsClient {
  list(): Promise<Session[]>;
  get(id: string): Promise<Session>;
  create(name: string): Promise<Session>;
  rename(id: string, name: string): Promise<void>;
  delete(id: string): Promise<void>;
  reorder(ids: string[]): Promise<void>;
  startStream(id: string): Promise<string>;
  stopStream(subscriptionId: string): Promise<void>;

  /**
   * listMessages returns the chat-message history for a session in
   * append-order. Pagination lands when long-context replays do; for now
   * the full transcript is returned.
   */
  listMessages(id: string): Promise<Message[]>;
  /**
   * appendMessage commits a single message to the session transcript and
   * returns the canonical Message (with server-assigned id + createdAt).
   * The Go side enforces redaction policy before persistence.
   */
  appendMessage(
    id: string,
    role: MessageRole,
    content: string,
  ): Promise<Message>;
  /** Persist a draft input for the session (debounced caller). */
  saveDraft(id: string, draft: string): Promise<void>;
  /** Load the persisted draft (empty string if none). */
  loadDraft(id: string): Promise<string>;
  /**
   * Persist the per-session starting context (Mission A). kind is
   * 'system' (invisible system prompt prepended on every send) or
   * 'user_seed' (visible — caller is responsible for ALSO appending
   * the content as a user message via appendMessage). The Go side
   * validates kind and rejects unknown values.
   */
  setSystemPrompt(
    id: string,
    content: string,
    kind: 'system' | 'user_seed',
  ): Promise<void>;
  /**
   * moveToProject sets the session's project membership. Empty
   * projectId detaches the session and makes it loose.
   */
  moveToProject(id: string, projectId: string): Promise<void>;
}

/**
 * ProjectsClient — top-level Project entity CRUD + session membership.
 * Projects group related sessions; sessions outside a project are loose.
 */
export interface ProjectsClient {
  list(): Promise<Project[]>;
  get(id: string): Promise<Project>;
  create(name: string, description?: string): Promise<Project>;
  rename(id: string, name: string): Promise<void>;
  updateDescription(id: string, description: string): Promise<void>;
  /**
   * remove deletes the project. When deleteSessions=true, every
   * session attached to the project is deleted as part of the same
   * operation; otherwise sessions become loose.
   */
  remove(id: string, deleteSessions: boolean): Promise<void>;
  addSession(projectId: string, sessionId: string): Promise<void>;
  removeSession(sessionId: string): Promise<void>;
  listSessions(projectId: string): Promise<Session[]>;
}

export interface LLMConnectorClient {
  listProviders(): Promise<Provider[]>;
  /**
   * startStream begins an assistant completion against `profileID` for
   * `sessionID`. modelOverride (optional) selects a non-default model
   * from the profile's authorised set — the backend validates and
   * substitutes it into the request. Returns the subscription id used
   * by `stopStream` and as the correlation key on `llm:stream-chunk`
   * events.
   */
  startStream(
    profileID: string,
    sessionID: string,
    modelOverride?: string,
  ): Promise<string>;
  stopStream(id: string): Promise<void>;
  /**
   * AddProvider persists a personal provider profile. The plaintextApiKey,
   * if supplied, is written to the OS keychain by the backend and zeroed
   * before any further processing. Only the CredentialReference enters
   * providers.json.
   */
  addProvider(input: AddProviderInput): Promise<void>;
  /**
   * UpdateProvider replaces an existing personal provider profile.
   * plaintextApiKey is OPTIONAL — when omitted, the keychain entry
   * is left in place so the user can edit model/region without
   * re-entering their credential.
   */
  updateProvider(input: AddProviderInput): Promise<void>;
  removeProvider(id: string): Promise<void>;
  testProvider(id: string): Promise<TestResult>;
  /**
   * Probe the provider for the set of models the supplied API key is
   * authorized to call. Returns an empty list when the kind has no
   * adapter or no /models endpoint — UI should fall back to manual
   * model entry in that case.
   */
  listModels(kind: string, plaintextApiKey: string): Promise<ModelInfo[]>;
}

export interface MCPClient {
  listServers(): Promise<MCPServer[]>;
  startStream(id: string): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface A2AClient {
  listCards(): Promise<A2ACard[]>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface WorkflowClient {
  listJobs(): Promise<Job[]>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface TrustClient {
  listSecretReferences(): Promise<SecretReference[]>;
  getSecretReference(id: string): Promise<SecretReference>;
}

export interface ContextClient {
  list(): Promise<ContextEntry[]>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

/**
 * ContextsClient — file-tree CRUD for the Context Library (/contexts).
 *
 * The frontend treats the library as a flat content pool: scope (global
 * / project / session) is a separate concern handled by later WPs. Path
 * arguments are slash-separated and relative to the library root; the
 * Go side validates ".." / absolute / symlink-escape before any I/O.
 */
export interface ContextsClient {
  list(): Promise<ContextNode>;
  get(path: string): Promise<string>;
  save(path: string, content: string): Promise<void>;
  createFolder(path: string): Promise<void>;
  rename(oldPath: string, newPath: string): Promise<void>;
  delete(path: string): Promise<void>;
  recentlyApplied(limit: number): Promise<string[]>;
  rootPath(): Promise<string>;
}

export interface BundleClient {
  list(): Promise<Bundle[]>;
  get(id: string): Promise<Bundle>;
}

export interface PolicyClient {
  explain(input: Record<string, unknown>): Promise<Denial>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface AuditClient {
  listEntries(filter: AuditFilter): Promise<AuditEntry[]>;
  verifyEntry(id: string): Promise<boolean>;
  startStream(filter: AuditFilter): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface SettingsClient {
  get(): Promise<Settings>;
  set(s: Settings): Promise<void>;
  loadRoute(): Promise<string>;
  saveRoute(route: string): Promise<void>;
  logRouteChange(from: string, to: string): Promise<void>;
  loadTheme(): Promise<Theme>;
  saveTheme(theme: Theme): Promise<void>;
  /** Read the long-term-memory opt-in flag (default false). */
  getMemory(): Promise<boolean>;
  /** Persist the long-term-memory opt-in flag. */
  setMemory(enabled: boolean): Promise<void>;
}

/**
 * MemoryClient backs the chat-surface "📌 remember this" button + the
 * /memory management view. Privacy: chunks live in the harness's data
 * directory; the only network call is the embedding request when a
 * new pin is staged.
 */
export interface MemoryClient {
  listChunks(): Promise<MemoryChunk[]>;
  rememberMessage(sessionID: string, messageID: string): Promise<string>;
  forget(id: string): Promise<void>;
}

/**
 * HooksClient backs the /hooks management view. Hooks are stored in
 * <DataDir>/hooks.json (mode 0600) and dispatched on the chat
 * pre_send / post_send lifecycle. Memory.retrieve / memory.persist
 * are the v1 preinstalled builtins; the surface ships extension
 * points for `shell` and `mcp` hooks the user configures.
 */
export interface HooksClient {
  list(): Promise<Hook[]>;
  get(id: string): Promise<Hook>;
  add(input: Hook): Promise<Hook>;
  update(input: Hook): Promise<void>;
  remove(id: string): Promise<void>;
  availableBuiltins(): Promise<BuiltinDescriptor[]>;
  /** Auto-install the two preinstalled memory hooks (idempotent). */
  installStarterMemory(): Promise<void>;
  /** Remove the two preinstalled memory hooks (idempotent). */
  removeStarterMemory(): Promise<void>;
}

export interface HarnessClient {
  shellStatus(): Promise<ShellStatus>;
  appInfo(): Promise<AppInfo>;

  sessions: SessionsClient;
  projects: ProjectsClient;
  llm: LLMConnectorClient;
  mcp: MCPClient;
  a2a: A2AClient;
  workflow: WorkflowClient;
  trust: TrustClient;
  context: ContextClient;
  contexts: ContextsClient;
  bundle: BundleClient;
  policy: PolicyClient;
  audit: AuditClient;
  settings: SettingsClient;
  memory: MemoryClient;
  hooks: HooksClient;
}

// ── runtime client ─────────────────────────────────────────────────────

function wailsBindings(): WailsBindingsLike {
  const b = (typeof window !== 'undefined' && window.go?.rpc?.Bindings) || undefined;
  if (!b) {
    throw new Error(
      'window.go.rpc.Bindings is not available. The harness frontend must run inside Wails.',
    );
  }
  return b;
}

export function createHarnessClient(): HarnessClient {
  const b: () => WailsBindingsLike = () => wailsBindings();

  return {
    shellStatus: () => b().ShellStatus(),
    appInfo: () => b().AppInfo(),

    sessions: {
      list: () => b().Sessions_List(),
      get: (id) => b().Sessions_Get(id),
      create: (name) => b().Sessions_Create(name),
      rename: (id, name) => b().Sessions_Rename(id, name),
      delete: (id) => b().Sessions_Delete(id),
      reorder: (ids) => b().Sessions_Reorder(ids),
      startStream: (id) => b().Sessions_StartStream(id),
      stopStream: (id) => b().Sessions_StopStream(id),
      listMessages: (id) => b().Sessions_ListMessages(id),
      appendMessage: (id, role, content) =>
        b().Sessions_AppendMessage(id, role, content),
      saveDraft: (id, draft) => b().Sessions_SaveDraft(id, draft),
      loadDraft: (id) => b().Sessions_LoadDraft(id),
      setSystemPrompt: (id, content, kind) =>
        b().Sessions_SetSystemPrompt(id, content, kind),
      moveToProject: (id, projectId) =>
        b().Sessions_MoveToProject(id, projectId),
    },
    projects: {
      list: () => b().Projects_List(),
      get: (id) => b().Projects_Get(id),
      create: (name, description) =>
        b().Projects_Create(name, description ?? ''),
      rename: (id, name) => b().Projects_Rename(id, name),
      updateDescription: (id, description) =>
        b().Projects_UpdateDescription(id, description),
      remove: (id, deleteSessions) =>
        b().Projects_Delete(id, deleteSessions),
      addSession: (projectId, sessionId) =>
        b().Projects_AddSession(projectId, sessionId),
      removeSession: (sessionId) => b().Projects_RemoveSession(sessionId),
      listSessions: (projectId) => b().Projects_ListSessions(projectId),
    },
    llm: {
      listProviders: () => b().LLM_ListProviders(),
      startStream: (profileID, sessionID, modelOverride) =>
        b().LLM_StartStream(profileID, sessionID, modelOverride ?? ''),
      stopStream: (id) => b().LLM_StopStream(id),
      addProvider: (input) => b().LLM_AddProvider(input),
      updateProvider: (input) => b().LLM_UpdateProvider(input),
      removeProvider: (id) => b().LLM_RemoveProvider(id),
      testProvider: (id) => b().LLM_TestProvider(id),
      listModels: (kind, plaintextApiKey) =>
        b().LLM_ListModels(kind, plaintextApiKey),
    },
    mcp: {
      listServers: () => b().MCP_ListServers(),
      startStream: (id) => b().MCP_StartStream(id),
      stopStream: (id) => b().MCP_StopStream(id),
    },
    a2a: {
      listCards: () => b().A2A_ListCards(),
      startStream: () => b().A2A_StartStream(),
      stopStream: (id) => b().A2A_StopStream(id),
    },
    workflow: {
      listJobs: () => b().Workflow_ListJobs(),
      startStream: () => b().Workflow_StartStream(),
      stopStream: (id) => b().Workflow_StopStream(id),
    },
    trust: {
      listSecretReferences: () => b().Trust_ListSecretReferences(),
      getSecretReference: (id) => b().Trust_GetSecretReference(id),
    },
    context: {
      list: () => b().Context_List(),
      startStream: () => b().Context_StartStream(),
      stopStream: (id) => b().Context_StopStream(id),
    },
    contexts: {
      list: () => b().Contexts_List(),
      get: (path) => b().Contexts_Get(path),
      save: (path, content) => b().Contexts_Save(path, content),
      createFolder: (path) => b().Contexts_CreateFolder(path),
      rename: (oldPath, newPath) => b().Contexts_Rename(oldPath, newPath),
      delete: (path) => b().Contexts_Delete(path),
      recentlyApplied: (limit) => b().Contexts_RecentlyApplied(limit),
      rootPath: () => b().Contexts_RootPath(),
    },
    bundle: {
      list: () => b().Bundle_List(),
      get: (id) => b().Bundle_Get(id),
    },
    policy: {
      explain: (input) => b().Policy_Explain(input),
      startStream: () => b().Policy_StartStream(),
      stopStream: (id) => b().Policy_StopStream(id),
    },
    audit: {
      listEntries: (filter) => b().Audit_ListEntries(filter),
      verifyEntry: (id) => b().Audit_VerifyEntry(id),
      startStream: (filter) => b().Audit_StartStream(filter),
      stopStream: (id) => b().Audit_StopStream(id),
    },
    settings: {
      get: () => b().Settings_Get(),
      set: (s) => b().Settings_Set(s),
      loadRoute: () => b().LoadRoute(),
      saveRoute: (r) => b().SaveRoute(r),
      logRouteChange: (f, t) => b().LogRouteChange(f, t),
      loadTheme: () => b().LoadTheme() as Promise<Theme>,
      saveTheme: (t) => b().SaveTheme(t),
      getMemory: () => b().Settings_GetMemory(),
      setMemory: (enabled) => b().Settings_SetMemory(enabled),
    },
    memory: {
      listChunks: () => b().Memory_ListChunks(),
      rememberMessage: (sessionID, messageID) =>
        b().Memory_RememberMessage(sessionID, messageID),
      forget: (id) => b().Memory_Forget(id),
    },
    hooks: {
      list: () => b().Hooks_List(),
      get: (id) => b().Hooks_Get(id),
      add: (input) => b().Hooks_Add(input),
      update: (input) => b().Hooks_Update(input),
      remove: (id) => b().Hooks_Remove(id),
      availableBuiltins: () => b().Hooks_AvailableBuiltins(),
      installStarterMemory: () => b().Hooks_InstallStarterMemory(),
      removeStarterMemory: () => b().Hooks_RemoveStarterMemory(),
    },
  };
}

// ── fake client for tests ──────────────────────────────────────────────

/**
 * createFakeHarnessClient — a deeply-stubbed client whose every method
 * resolves to safe defaults. Tests pass `seed` to override specific
 * sub-clients. Used by `provideFakeClient` (FR-008, SC-006).
 */
export function createFakeHarnessClient(
  seed: Partial<HarnessClient> = {},
): HarnessClient {
  const noop = async () => undefined as unknown as void;

  const defaults: HarnessClient = {
    shellStatus: async () => ({
      activeProvider: '—',
      trustTier: 'Local',
      harnessBuild: '0.0.0-fake',
      connection: 'ready',
      eventRate: 0,
      policyApplied: true,
      redactionOn: true,
      localFirstOn: true,
    }),
    appInfo: async () => ({
      build: 'fake',
      commit: 'fake',
      buildTime: '',
      goVersion: '',
      platform: 'fake',
      windowSize: { width: 1280, height: 800 },
    }),
    sessions: {
      list: async () => [],
      get: async (id) => ({ id, name: id, createdAt: '', updatedAt: '' }),
      create: async (name) => ({
        id: `fake-${Math.random().toString(36).slice(2, 8)}`,
        name,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }),
      rename: noop,
      delete: noop,
      reorder: noop,
      startStream: async () => 'fake-sub',
      stopStream: noop,
      listMessages: async () => [],
      appendMessage: async (id, role, content) => ({
        id: `fake-msg-${Math.random().toString(36).slice(2, 8)}`,
        sessionId: id,
        role,
        content,
        createdAt: new Date().toISOString(),
      }),
      saveDraft: noop,
      loadDraft: async () => '',
      setSystemPrompt: noop,
      moveToProject: noop,
    },
    projects: {
      list: async () => [],
      get: async (id) => ({
        id,
        name: id,
        description: '',
        createdAt: '',
        updatedAt: '',
      }),
      create: async (name, description) => ({
        id: `fake-proj-${Math.random().toString(36).slice(2, 8)}`,
        name,
        description: description ?? '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }),
      rename: noop,
      updateDescription: noop,
      remove: noop,
      addSession: noop,
      removeSession: noop,
      listSessions: async () => [],
    },
    llm: {
      listProviders: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
      addProvider: noop,
      updateProvider: noop,
      removeProvider: noop,
      testProvider: async () => ({
        success: true,
        latency_ms: 1,
        message: 'fake ok',
      }),
      listModels: async () => [],
    },
    mcp: {
      listServers: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    a2a: {
      listCards: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    workflow: {
      listJobs: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    trust: {
      listSecretReferences: async () => [],
      getSecretReference: async (id) => ({
        id,
        label: id,
        source: 'fake',
        createdAt: '',
      }),
    },
    context: {
      list: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    contexts: {
      list: async () => ({ name: '', path: '', kind: 'folder' as const }),
      get: async () => '',
      save: noop,
      createFolder: noop,
      rename: noop,
      delete: noop,
      recentlyApplied: async () => [],
      rootPath: async () => '/fake/contexts',
    },
    bundle: {
      list: async () => [],
      get: async (id) => ({
        id,
        name: id,
        version: '',
        tier: '',
        artifactCount: 0,
      }),
    },
    policy: {
      explain: async () => ({
        policyId: 'fake-policy',
        clauseId: 'fake-clause',
        violatingInput: '',
        remediation: '',
      }),
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    audit: {
      listEntries: async () => [],
      verifyEntry: async () => true,
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    settings: {
      get: async () => ({
        schemaVersion: 1,
        lastRoute: '/sessions',
        theme: 'system',
        accent: 'default',
        windowSize: { width: 1280, height: 800 },
        memoryEnabled: false,
      }),
      set: noop,
      loadRoute: async () => '/sessions',
      saveRoute: noop,
      logRouteChange: noop,
      loadTheme: async () => 'system' as Theme,
      saveTheme: noop,
      getMemory: async () => false,
      setMemory: noop,
    },
    memory: {
      listChunks: async () => [],
      rememberMessage: async () => 'fake-mem-id',
      forget: noop,
    },
    hooks: {
      list: async () => [],
      get: async (id) => ({
        id,
        name: id,
        event: 'pre_send',
        kind: 'builtin',
        enabled: false,
        match: {},
      }),
      add: async (input) => input,
      update: noop,
      remove: noop,
      availableBuiltins: async () => [],
      installStarterMemory: noop,
      removeStarterMemory: noop,
    },
  };

  return { ...defaults, ...seed };
}
