/**
 * harnessClient — the typed wrapper over `window.go.rpc.Bindings`.
 *
 * This is the ONLY module that knows about the Wails-generated surface.
 * Components and composables consume the nested view-scoped client objects
 * (e.g., `client.sessions.list()`); ESLint forbids `wailsjs/*` imports
 * outside this file (FR-007 / C-001 / plan §4.1).
 *
 * The Wails-generated bindings live under `frontend/wailsjs/go/rpc/Bindings`
 * once `wails generate module` runs against the `Bindings` struct. Until
 * regeneration, `WailsBindings` resolves through the runtime-attached
 * `window.go.rpc.Bindings` object Wails injects at boot. Both paths flow
 * through the same `WailsBindingsLike` interface so swapping in a fake
 * client is purely a TypeScript concern.
 */

import type {
  Session,
  Provider,
  AddProviderInput,
  TestResult,
  MCPServer,
  A2ACard,
  Job,
  SecretReference,
  ContextEntry,
  Bundle,
  Denial,
  AuditEntry,
  AuditFilter,
  ShellStatus,
  AppInfo,
  Settings,
  Theme,
  Message,
  MessageRole,
} from './types';

/**
 * Minimal shape of the runtime-attached bindings. The full surface is
 * generated by Wails; we duck-type only what the client uses so the
 * frontend builds without `wails generate module` having run.
 */
interface WailsBindingsLike {
  ShellStatus(): Promise<ShellStatus>;
  AppInfo(): Promise<AppInfo>;
  LoadRoute(): Promise<string>;
  SaveRoute(route: string): Promise<void>;
  LogRouteChange(from: string, to: string): Promise<void>;
  LoadTheme(): Promise<string>;
  SaveTheme(theme: string): Promise<void>;

  Sessions_List(): Promise<Session[]>;
  Sessions_Get(id: string): Promise<Session>;
  Sessions_Create(name: string): Promise<Session>;
  Sessions_Rename(id: string, name: string): Promise<void>;
  Sessions_Delete(id: string): Promise<void>;
  Sessions_Reorder(ids: string[]): Promise<void>;
  Sessions_StartStream(id: string): Promise<string>;
  Sessions_StopStream(id: string): Promise<void>;
  Sessions_ListMessages(id: string): Promise<Message[]>;
  Sessions_AppendMessage(
    id: string,
    role: MessageRole,
    content: string,
  ): Promise<Message>;
  Sessions_SaveDraft(id: string, draft: string): Promise<void>;
  Sessions_LoadDraft(id: string): Promise<string>;

  LLM_ListProviders(): Promise<Provider[]>;
  LLM_StartStream(profileID: string, sessionID: string): Promise<string>;
  LLM_StopStream(id: string): Promise<void>;
  LLM_AddProvider(input: AddProviderInput): Promise<void>;
  LLM_RemoveProvider(id: string): Promise<void>;
  LLM_TestProvider(id: string): Promise<TestResult>;

  MCP_ListServers(): Promise<MCPServer[]>;
  MCP_StartStream(id: string): Promise<string>;
  MCP_StopStream(id: string): Promise<void>;

  A2A_ListCards(): Promise<A2ACard[]>;
  A2A_StartStream(): Promise<string>;
  A2A_StopStream(id: string): Promise<void>;

  Workflow_ListJobs(): Promise<Job[]>;
  Workflow_StartStream(): Promise<string>;
  Workflow_StopStream(id: string): Promise<void>;

  Trust_ListSecretReferences(): Promise<SecretReference[]>;
  Trust_GetSecretReference(id: string): Promise<SecretReference>;

  Context_List(): Promise<ContextEntry[]>;
  Context_StartStream(): Promise<string>;
  Context_StopStream(id: string): Promise<void>;

  Bundle_List(): Promise<Bundle[]>;
  Bundle_Get(id: string): Promise<Bundle>;

  Policy_Explain(input: Record<string, unknown>): Promise<Denial>;
  Policy_StartStream(): Promise<string>;
  Policy_StopStream(id: string): Promise<void>;

  Audit_ListEntries(filter: AuditFilter): Promise<AuditEntry[]>;
  Audit_VerifyEntry(id: string): Promise<boolean>;
  Audit_StartStream(filter: AuditFilter): Promise<string>;
  Audit_StopStream(id: string): Promise<void>;

  Settings_Get(): Promise<Settings>;
  Settings_Set(s: Settings): Promise<void>;
}

declare global {
  interface Window {
    go?: {
      rpc?: {
        Bindings?: WailsBindingsLike;
      };
    };
    runtime?: {
      EventsOn?: (
        topic: string,
        cb: (payload: unknown) => void,
      ) => () => void;
      EventsOff?: (topic: string) => void;
    };
  }
}

// ── view-scoped client interfaces ──────────────────────────────────────

export interface SessionsClient {
  list(): Promise<Session[]>;
  get(id: string): Promise<Session>;
  create(name: string): Promise<Session>;
  rename(id: string, name: string): Promise<void>;
  delete(id: string): Promise<void>;
  reorder(ids: string[]): Promise<void>;
  startStream(id: string): Promise<string>;
  stopStream(subscriptionId: string): Promise<void>;

  /**
   * listMessages returns the chat-message history for a session in
   * append-order. Pagination lands when long-context replays do; for now
   * the full transcript is returned.
   */
  listMessages(id: string): Promise<Message[]>;
  /**
   * appendMessage commits a single message to the session transcript and
   * returns the canonical Message (with server-assigned id + createdAt).
   * The Go side enforces redaction policy before persistence.
   */
  appendMessage(
    id: string,
    role: MessageRole,
    content: string,
  ): Promise<Message>;
  /** Persist a draft input for the session (debounced caller). */
  saveDraft(id: string, draft: string): Promise<void>;
  /** Load the persisted draft (empty string if none). */
  loadDraft(id: string): Promise<string>;
}

export interface LLMConnectorClient {
  listProviders(): Promise<Provider[]>;
  /**
   * startStream begins an assistant completion against `profileID` for
   * `sessionID`. Returns the subscription id used by `stopStream` and as
   * the correlation key on `llm:stream-chunk` events.
   */
  startStream(profileID: string, sessionID: string): Promise<string>;
  stopStream(id: string): Promise<void>;
  /**
   * AddProvider persists a personal provider profile. The plaintextApiKey,
   * if supplied, is written to the OS keychain by the backend and zeroed
   * before any further processing. Only the CredentialReference enters
   * providers.json.
   */
  addProvider(input: AddProviderInput): Promise<void>;
  removeProvider(id: string): Promise<void>;
  testProvider(id: string): Promise<TestResult>;
}

export interface MCPClient {
  listServers(): Promise<MCPServer[]>;
  startStream(id: string): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface A2AClient {
  listCards(): Promise<A2ACard[]>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface WorkflowClient {
  listJobs(): Promise<Job[]>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface TrustClient {
  listSecretReferences(): Promise<SecretReference[]>;
  getSecretReference(id: string): Promise<SecretReference>;
}

export interface ContextClient {
  list(): Promise<ContextEntry[]>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface BundleClient {
  list(): Promise<Bundle[]>;
  get(id: string): Promise<Bundle>;
}

export interface PolicyClient {
  explain(input: Record<string, unknown>): Promise<Denial>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface AuditClient {
  listEntries(filter: AuditFilter): Promise<AuditEntry[]>;
  verifyEntry(id: string): Promise<boolean>;
  startStream(filter: AuditFilter): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface SettingsClient {
  get(): Promise<Settings>;
  set(s: Settings): Promise<void>;
  loadRoute(): Promise<string>;
  saveRoute(route: string): Promise<void>;
  logRouteChange(from: string, to: string): Promise<void>;
  loadTheme(): Promise<Theme>;
  saveTheme(theme: Theme): Promise<void>;
}

export interface HarnessClient {
  shellStatus(): Promise<ShellStatus>;
  appInfo(): Promise<AppInfo>;

  sessions: SessionsClient;
  llm: LLMConnectorClient;
  mcp: MCPClient;
  a2a: A2AClient;
  workflow: WorkflowClient;
  trust: TrustClient;
  context: ContextClient;
  bundle: BundleClient;
  policy: PolicyClient;
  audit: AuditClient;
  settings: SettingsClient;
}

// ── runtime client ─────────────────────────────────────────────────────

function wailsBindings(): WailsBindingsLike {
  const b = (typeof window !== 'undefined' && window.go?.rpc?.Bindings) || undefined;
  if (!b) {
    throw new Error(
      'window.go.rpc.Bindings is not available. The harness frontend must run inside Wails.',
    );
  }
  return b;
}

export function createHarnessClient(): HarnessClient {
  const b: () => WailsBindingsLike = () => wailsBindings();

  return {
    shellStatus: () => b().ShellStatus(),
    appInfo: () => b().AppInfo(),

    sessions: {
      list: () => b().Sessions_List(),
      get: (id) => b().Sessions_Get(id),
      create: (name) => b().Sessions_Create(name),
      rename: (id, name) => b().Sessions_Rename(id, name),
      delete: (id) => b().Sessions_Delete(id),
      reorder: (ids) => b().Sessions_Reorder(ids),
      startStream: (id) => b().Sessions_StartStream(id),
      stopStream: (id) => b().Sessions_StopStream(id),
      listMessages: (id) => b().Sessions_ListMessages(id),
      appendMessage: (id, role, content) =>
        b().Sessions_AppendMessage(id, role, content),
      saveDraft: (id, draft) => b().Sessions_SaveDraft(id, draft),
      loadDraft: (id) => b().Sessions_LoadDraft(id),
    },
    llm: {
      listProviders: () => b().LLM_ListProviders(),
      startStream: (profileID, sessionID) =>
        b().LLM_StartStream(profileID, sessionID),
      stopStream: (id) => b().LLM_StopStream(id),
      addProvider: (input) => b().LLM_AddProvider(input),
      removeProvider: (id) => b().LLM_RemoveProvider(id),
      testProvider: (id) => b().LLM_TestProvider(id),
    },
    mcp: {
      listServers: () => b().MCP_ListServers(),
      startStream: (id) => b().MCP_StartStream(id),
      stopStream: (id) => b().MCP_StopStream(id),
    },
    a2a: {
      listCards: () => b().A2A_ListCards(),
      startStream: () => b().A2A_StartStream(),
      stopStream: (id) => b().A2A_StopStream(id),
    },
    workflow: {
      listJobs: () => b().Workflow_ListJobs(),
      startStream: () => b().Workflow_StartStream(),
      stopStream: (id) => b().Workflow_StopStream(id),
    },
    trust: {
      listSecretReferences: () => b().Trust_ListSecretReferences(),
      getSecretReference: (id) => b().Trust_GetSecretReference(id),
    },
    context: {
      list: () => b().Context_List(),
      startStream: () => b().Context_StartStream(),
      stopStream: (id) => b().Context_StopStream(id),
    },
    bundle: {
      list: () => b().Bundle_List(),
      get: (id) => b().Bundle_Get(id),
    },
    policy: {
      explain: (input) => b().Policy_Explain(input),
      startStream: () => b().Policy_StartStream(),
      stopStream: (id) => b().Policy_StopStream(id),
    },
    audit: {
      listEntries: (filter) => b().Audit_ListEntries(filter),
      verifyEntry: (id) => b().Audit_VerifyEntry(id),
      startStream: (filter) => b().Audit_StartStream(filter),
      stopStream: (id) => b().Audit_StopStream(id),
    },
    settings: {
      get: () => b().Settings_Get(),
      set: (s) => b().Settings_Set(s),
      loadRoute: () => b().LoadRoute(),
      saveRoute: (r) => b().SaveRoute(r),
      logRouteChange: (f, t) => b().LogRouteChange(f, t),
      loadTheme: () => b().LoadTheme() as Promise<Theme>,
      saveTheme: (t) => b().SaveTheme(t),
    },
  };
}

// ── fake client for tests ──────────────────────────────────────────────

/**
 * createFakeHarnessClient — a deeply-stubbed client whose every method
 * resolves to safe defaults. Tests pass `seed` to override specific
 * sub-clients. Used by `provideFakeClient` (FR-008, SC-006).
 */
export function createFakeHarnessClient(
  seed: Partial<HarnessClient> = {},
): HarnessClient {
  const noop = async () => undefined as unknown as void;

  const defaults: HarnessClient = {
    shellStatus: async () => ({
      activeProvider: '—',
      trustTier: 'Local',
      harnessBuild: '0.0.0-fake',
      connection: 'ready',
      eventRate: 0,
      policyApplied: true,
      redactionOn: true,
      localFirstOn: true,
    }),
    appInfo: async () => ({
      build: 'fake',
      commit: 'fake',
      buildTime: '',
      goVersion: '',
      platform: 'fake',
      windowSize: { width: 1280, height: 800 },
    }),
    sessions: {
      list: async () => [],
      get: async (id) => ({ id, name: id, createdAt: '', updatedAt: '' }),
      create: async (name) => ({
        id: `fake-${Math.random().toString(36).slice(2, 8)}`,
        name,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }),
      rename: noop,
      delete: noop,
      reorder: noop,
      startStream: async () => 'fake-sub',
      stopStream: noop,
      listMessages: async () => [],
      appendMessage: async (id, role, content) => ({
        id: `fake-msg-${Math.random().toString(36).slice(2, 8)}`,
        sessionId: id,
        role,
        content,
        createdAt: new Date().toISOString(),
      }),
      saveDraft: noop,
      loadDraft: async () => '',
    },
    llm: {
      listProviders: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
      addProvider: noop,
      removeProvider: noop,
      testProvider: async () => ({
        success: true,
        latency_ms: 1,
        message: 'fake ok',
      }),
    },
    mcp: {
      listServers: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    a2a: {
      listCards: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    workflow: {
      listJobs: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    trust: {
      listSecretReferences: async () => [],
      getSecretReference: async (id) => ({
        id,
        label: id,
        source: 'fake',
        createdAt: '',
      }),
    },
    context: {
      list: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    bundle: {
      list: async () => [],
      get: async (id) => ({
        id,
        name: id,
        version: '',
        tier: '',
        artifactCount: 0,
      }),
    },
    policy: {
      explain: async () => ({
        policyId: 'fake-policy',
        clauseId: 'fake-clause',
        violatingInput: '',
        remediation: '',
      }),
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    audit: {
      listEntries: async () => [],
      verifyEntry: async () => true,
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    settings: {
      get: async () => ({
        schemaVersion: 1,
        lastRoute: '/sessions',
        theme: 'system',
        accent: 'default',
        windowSize: { width: 1280, height: 800 },
      }),
      set: noop,
      loadRoute: async () => '/sessions',
      saveRoute: noop,
      logRouteChange: noop,
      loadTheme: async () => 'system' as Theme,
      saveTheme: noop,
    },
  };

  return { ...defaults, ...seed };
}
