/**
 * harnessClient — the typed wrapper over `window.go.rpc.Bindings`.
 *
 * This is the ONLY module that knows about the Wails-generated surface.
 * Components and composables consume the nested view-scoped client objects
 * (e.g., `client.sessions.list()`); ESLint forbids `wailsjs/*` imports
 * outside this file (FR-007 / C-001 / plan §4.1).
 *
 * The Wails-generated bindings live under `frontend/wailsjs/go/rpc/Bindings`
 * once `wails generate module` runs against the `Bindings` struct. Until
 * regeneration, `WailsBindings` resolves through the runtime-attached
 * `window.go.rpc.Bindings` object Wails injects at boot. Both paths flow
 * through the same `WailsBindingsLike` interface so swapping in a fake
 * client is purely a TypeScript concern.
 */

import type {
  Session,
  Project,
  Provider,
  AddProviderInput,
  TestResult,
  ModelInfo,
  MCPServer,
  A2ACard,
  Job,
  SecretReference,
  ContextEntry,
  ContextNode,
  Attachment,
  AttachmentAddInput,
  AttachmentScopeKind,
  Bundle,
  ContentBlock,
  Denial,
  AuditEntry,
  AuditFilter,
  ShellStatus,
  AppInfo,
  Settings,
  Theme,
  Message,
  MessageRole,
  MemoryChunk,
  MemoryListFilter,
  MemoryScopeKind,
  MemoryJournalEntry,
  MemoryPruneStats,
  MemoryPrunePreview,
  DialConfig,
  DialDelta,
  DialEffectiveDials,
  DialScope,
  DialScopeKey,
  Hook,
  BuiltinDescriptor,
  ConfirmDecision,
  Recipe,
  RecipeCategory,
  RecipeListing,
  RecipeState,
  RecipeStatus,
  EnvKey,
  ConfigOption,
  ConfigKind,
  Artifact,
  ArtifactFilter,
  ArtifactScope,
  ArtifactWithBytes,
  SlashCommandInfo,
  SlashExecuteResult,
  Corpus,
  CorpusFile,
  CorpusChunk,
  CorpusIngestStatus,
  CorpusIngestOptions,
  CorpusCreateRequest,
  CorpusRetrieveRequest,
  CorpusRetrieveResponse,
} from './types';

/**
 * ShellReadFileResult — wire shape returned by Shell_ReadFile. The
 * binding base64-encodes the file bytes so the frontend can hand
 * them straight to Attachments_AddMedia (image/PDF) or decode for
 * text-snapshot attachments.
 */
export interface ShellReadFileResult {
  dataBase64: string;
  mediaType: string;
}

/**
 * Minimal shape of the runtime-attached bindings. The full surface is
 * generated by Wails; we duck-type only what the client uses so the
 * frontend builds without `wails generate module` having run.
 */
interface WailsBindingsLike {
  ShellStatus(): Promise<ShellStatus>;
  AppInfo(): Promise<AppInfo>;
  LoadRoute(): Promise<string>;
  SaveRoute(route: string): Promise<void>;
  LogRouteChange(from: string, to: string): Promise<void>;
  LoadTheme(): Promise<string>;
  SaveTheme(theme: string): Promise<void>;

  Sessions_List(): Promise<Session[]>;
  Sessions_Get(id: string): Promise<Session>;
  Sessions_Create(name: string): Promise<Session>;
  Sessions_Rename(id: string, name: string): Promise<void>;
  Sessions_Delete(id: string): Promise<void>;
  Sessions_Reorder(ids: string[]): Promise<void>;
  Sessions_StartStream(id: string): Promise<string>;
  Sessions_StopStream(id: string): Promise<void>;
  Sessions_ListMessages(id: string): Promise<Message[]>;
  Sessions_AppendMessage(
    id: string,
    role: MessageRole,
    content: string,
  ): Promise<Message>;
  Sessions_SendMessageWithBlocks(
    id: string,
    contentBlocks: ContentBlock[],
  ): Promise<Message>;
  Sessions_SaveDraft(id: string, draft: string): Promise<void>;
  Sessions_LoadDraft(id: string): Promise<string>;
  Sessions_SetSystemPrompt(
    id: string,
    content: string,
    kind: 'system' | 'user_seed',
  ): Promise<void>;
  Sessions_MoveToProject(id: string, projectID: string): Promise<void>;
  Sessions_SaveAsArtifact(
    sessionID: string,
    messageID: string,
    title: string,
    rangeStart: number,
    rangeEnd: number,
  ): Promise<Artifact>;

  Artifacts_List(filter: ArtifactFilter): Promise<Artifact[]>;
  Artifacts_Get(id: string): Promise<WireArtifactWithBytes>;
  Artifacts_Promote(
    id: string,
    newScopeKind: string,
    newScopeID: string,
  ): Promise<Artifact>;
  Artifacts_Delete(id: string): Promise<void>;

  Projects_List(): Promise<Project[]>;
  Projects_Get(id: string): Promise<Project>;
  Projects_Create(name: string, description: string): Promise<Project>;
  Projects_Rename(id: string, name: string): Promise<void>;
  Projects_UpdateDescription(id: string, description: string): Promise<void>;
  Projects_Delete(id: string, deleteSessions: boolean): Promise<void>;
  Projects_AddSession(projectID: string, sessionID: string): Promise<void>;
  Projects_RemoveSession(sessionID: string): Promise<void>;
  Projects_ListSessions(projectID: string): Promise<Session[]>;

  LLM_ListProviders(): Promise<Provider[]>;
  LLM_StartStream(
    profileID: string,
    sessionID: string,
    modelOverride: string,
  ): Promise<string>;
  LLM_StopStream(id: string): Promise<void>;
  LLM_AddProvider(input: AddProviderInput): Promise<void>;
  LLM_UpdateProvider(input: AddProviderInput): Promise<void>;
  LLM_RemoveProvider(id: string): Promise<void>;
  LLM_TestProvider(id: string): Promise<TestResult>;
  LLM_ListModels(kind: string, plaintextApiKey: string): Promise<ModelInfo[]>;
  LLM_ResolveConfirm(requestID: string, decision: string): Promise<void>;

  MCP_ListServers(): Promise<MCPServer[]>;
  MCP_StartStream(id: string): Promise<string>;
  MCP_StopStream(id: string): Promise<void>;

  A2A_ListCards(): Promise<A2ACard[]>;
  A2A_StartStream(): Promise<string>;
  A2A_StopStream(id: string): Promise<void>;

  Workflow_ListJobs(): Promise<Job[]>;
  Workflow_StartStream(): Promise<string>;
  Workflow_StopStream(id: string): Promise<void>;

  Trust_ListSecretReferences(): Promise<SecretReference[]>;
  Trust_GetSecretReference(id: string): Promise<SecretReference>;

  Context_List(): Promise<ContextEntry[]>;
  Context_StartStream(): Promise<string>;
  Context_StopStream(id: string): Promise<void>;

  Contexts_List(): Promise<ContextNode>;
  Contexts_ListAll(): Promise<ContextNode>;
  Contexts_Get(path: string): Promise<string>;
  Contexts_Save(path: string, content: string): Promise<void>;
  Contexts_CreateFolder(path: string): Promise<void>;
  Contexts_Rename(oldPath: string, newPath: string): Promise<void>;
  Contexts_Delete(path: string): Promise<void>;
  Contexts_RecentlyApplied(limit: number): Promise<string[]>;
  Contexts_RootPath(): Promise<string>;

  Attachments_List(scopeKind: string, scopeID: string): Promise<Attachment[]>;
  Attachments_ListResolved(sessionID: string): Promise<Attachment[]>;
  Attachments_Add(input: AttachmentAddInput): Promise<Attachment>;
  Attachments_AddMedia(input: AttachmentAddMediaInput): Promise<Attachment>;
  Attachments_Remove(id: string): Promise<void>;
  Attachments_Reorder(
    scopeKind: string,
    scopeID: string,
    idsInOrder: string[],
  ): Promise<void>;
  Attachments_Refresh(id: string): Promise<Attachment>;

  Bundle_List(): Promise<Bundle[]>;
  Bundle_Get(id: string): Promise<Bundle>;

  Policy_Explain(input: Record<string, unknown>): Promise<Denial>;
  Policy_StartStream(): Promise<string>;
  Policy_StopStream(id: string): Promise<void>;

  Audit_ListEntries(filter: AuditFilter): Promise<AuditEntry[]>;
  Audit_VerifyEntry(id: string): Promise<boolean>;
  Audit_StartStream(filter: AuditFilter): Promise<string>;
  Audit_StopStream(id: string): Promise<void>;

  Settings_Get(): Promise<Settings>;
  Settings_Set(s: Settings): Promise<void>;
  Settings_GetMemory(): Promise<boolean>;
  Settings_SetMemory(enabled: boolean): Promise<void>;
  Settings_GetConfirmEach(): Promise<boolean>;
  Settings_SetConfirmEach(enabled: boolean): Promise<void>;

  Memory_ListChunks(filter: MemoryListFilter): Promise<MemoryChunk[]>;
  Memory_RememberMessage(
    sessionID: string,
    messageID: string,
    scope: string,
  ): Promise<string>;
  Memory_PromoteScope(
    chunkID: string,
    newScopeKind: string,
    newScopeID: string,
  ): Promise<string>;
  Memory_Forget(id: string): Promise<void>;
  Memory_Pin(id: string, pinned: boolean): Promise<void>;
  Memory_JournalTail(
    scope: string,
    sinceSeq: number,
    limit: number,
  ): Promise<MemoryJournalEntry[]>;
  Memory_PrunePreview(scope: string): Promise<MemoryPrunePreview>;
  Memory_RunPruneNow(scope: string): Promise<MemoryPruneStats>;

  Dials_Get(key: DialScopeKey): Promise<DialConfig>;
  Dials_Set(key: DialScopeKey, cfg: DialConfig): Promise<void>;
  Dials_GetEffective(
    projectID: string,
    sessionID: string,
    graphID: string,
    runID: string,
  ): Promise<DialEffectiveDials>;
  Dials_BumpAndResume(runID: string, delta: DialDelta): Promise<void>;

  Hooks_List(): Promise<Hook[]>;
  Hooks_Get(id: string): Promise<Hook>;
  Hooks_Add(input: Hook): Promise<Hook>;
  Hooks_Update(input: Hook): Promise<void>;
  Hooks_Remove(id: string): Promise<void>;
  Hooks_AvailableBuiltins(): Promise<BuiltinDescriptor[]>;
  Hooks_InstallStarterMemory(): Promise<void>;
  Hooks_RemoveStarterMemory(): Promise<void>;

  Tools_ListRecipes(): Promise<WireRecipeListing[]>;
  Tools_InstallRecipe(
    id: string,
    env: Record<string, string>,
    config: Record<string, unknown>,
  ): Promise<WireRecipeStatus>;
  Tools_UninstallRecipe(id: string): Promise<void>;
  Tools_ForgetRecipeKey(id: string, envName: string): Promise<void>;
  Tools_RecipeStatus(id: string): Promise<WireRecipeStatus>;
  Tools_RecipeConfig(id: string): Promise<Record<string, unknown>>;

  Shell_OpenInOSBrowser(path: string): Promise<void>;
  Shell_PathComplete(partial: string): Promise<string[]>;
  Shell_ReadFile(path: string): Promise<ShellReadFileResult>;

  Slash_Execute(
    sessionID: string,
    raw: string,
  ): Promise<SlashExecuteResult>;
  Slash_List(): Promise<SlashCommandInfo[]>;

  Corpus_ListCorpora(scope: string): Promise<Corpus[]>;
  Corpus_CreateCorpus(req: CorpusCreateRequest): Promise<Corpus>;
  Corpus_GetCorpus(corpusID: string): Promise<Corpus>;
  Corpus_DeleteCorpus(corpusID: string): Promise<void>;
  Corpus_ListFiles(corpusID: string): Promise<CorpusFile[]>;
  Corpus_ListChunks(corpusID: string, fileID: string): Promise<CorpusChunk[]>;
  Corpus_IngestPath(
    corpusID: string,
    path: string,
    opts: CorpusIngestOptions,
  ): Promise<CorpusIngestStatus>;
  Corpus_JobStatus(jobID: string): Promise<CorpusIngestStatus>;
  Corpus_Retrieve(
    corpusID: string,
    req: CorpusRetrieveRequest,
  ): Promise<CorpusRetrieveResponse>;
}

/**
 * AttachmentAddMediaInput — wire shape Attachments_AddMedia accepts.
 * mediaBytesBase64 is the raw base64-encoded payload (no
 * `data:<mt>;base64,` prefix). The Go binding decodes once, validates
 * size + media type, and pipes it through the MediaStore CAS path.
 */
export interface AttachmentAddMediaInput {
  scopeKind: AttachmentScopeKind;
  scopeId?: string;
  mediaBytesBase64: string;
  mediaType: string;
  originalName?: string;
}

// ── Wails wire shapes for recipes (snake_case-tagged Go structs) ───────
//
// The Go-side `core/mcp/recipes.Recipe` and `core/mcp/stdio.RecipeStatus`
// carry snake_case JSON tags that Wails preserves verbatim, while the
// view-layer `RecipeListing` wrapper is camelCase. We translate to the
// camelCase TS surface in `adaptRecipeListing` / `adaptRecipeStatus`.

interface WireEnvKey {
  name: string;
  display: string;
  docs_url?: string;
  required: boolean;
}

interface WireCapabilities {
  tools: boolean;
  resources: boolean;
  prompts: boolean;
  sampling: boolean;
}

interface WireConfigOption {
  name: string;
  display: string;
  kind: string;
  default?: unknown;
  required: boolean;
  description: string;
}

interface WireRecipe {
  id: string;
  display_name: string;
  description: string;
  category: string;
  command?: string[];
  env_keys?: WireEnvKey[];
  capabilities: WireCapabilities;
  docs_url?: string;
  init_timeout_ms?: number;
  ping_period_ms?: number;
  sampling_policy?: { allowed: boolean; default: boolean };
  args_template?: string[];
  config_options?: WireConfigOption[];
}

interface WireRecipeStatus {
  id: string;
  enabled: boolean;
  state: string;
  last_error?: string;
  restart_attempts: number;
  last_restart_at?: string;
  keys_present: boolean;
  pid: number;
  protocol_version?: string;
  server_name?: string;
  server_version?: string;
  tool_count: number;
  resource_count: number;
  prompt_count: number;
  stderr_tail?: string;
  updated_at?: string;
}

/**
 * WireArtifactWithBytes — Wails-generated shape for `Artifacts_Get`.
 * The autogenerated TS calls `bytes` a `number[]`, but the runtime
 * payload is a base64 string (Go-side `[]byte` → JSON base64). We
 * normalise to a `string` in the typed `ArtifactWithBytes` surface.
 */
interface WireArtifactWithBytes {
  artifact: Artifact;
  bytes: unknown;
}

function adaptArtifactBytes(raw: unknown): string {
  if (typeof raw === 'string') return raw;
  // Defensive: the Wails generator sometimes types []byte as number[];
  // if a number array slips through, base64-encode it on the fly.
  if (Array.isArray(raw)) {
    let bin = '';
    for (const n of raw) {
      if (typeof n === 'number') bin += String.fromCharCode(n & 0xff);
    }
    return typeof btoa === 'function' ? btoa(bin) : '';
  }
  return '';
}

interface WireRecipeListing {
  recipe: WireRecipe;
  enabled: boolean;
  status: WireRecipeStatus;
  keysPresent: boolean;
}

const KNOWN_CATEGORIES: readonly RecipeCategory[] = [
  'search',
  'filesystem',
  'memory',
  'fetch',
  'other',
];

function adaptCategory(raw: string): RecipeCategory {
  return (KNOWN_CATEGORIES as readonly string[]).includes(raw)
    ? (raw as RecipeCategory)
    : 'other';
}

const KNOWN_STATES: readonly RecipeState[] = [
  'stopped',
  'starting',
  'running',
  'restarting',
  'failed',
];

function adaptState(raw: string): RecipeState {
  return (KNOWN_STATES as readonly string[]).includes(raw)
    ? (raw as RecipeState)
    : 'stopped';
}

function adaptEnvKey(w: WireEnvKey): EnvKey {
  return {
    name: w.name,
    display: w.display,
    docsUrl: w.docs_url || undefined,
    required: w.required,
  };
}

const KNOWN_CONFIG_KINDS: readonly ConfigKind[] = [
  'directory_list',
  'boolean',
  'string',
];

function adaptConfigKind(raw: string): ConfigKind {
  return (KNOWN_CONFIG_KINDS as readonly string[]).includes(raw)
    ? (raw as ConfigKind)
    : 'string';
}

function adaptConfigOption(w: WireConfigOption): ConfigOption {
  return {
    name: w.name,
    display: w.display,
    kind: adaptConfigKind(w.kind),
    default: w.default,
    required: w.required,
    description: w.description,
  };
}

function adaptRecipe(w: WireRecipe): Recipe {
  const configOptions = w.config_options
    ? w.config_options.map(adaptConfigOption)
    : undefined;
  return {
    id: w.id,
    displayName: w.display_name,
    description: w.description,
    category: adaptCategory(w.category),
    envKeys: (w.env_keys ?? []).map(adaptEnvKey),
    capabilities: w.capabilities,
    docsUrl: w.docs_url || undefined,
    argsTemplate: w.args_template ? [...w.args_template] : undefined,
    configOptions,
  };
}

function adaptRecipeStatus(w: WireRecipeStatus): RecipeStatus {
  return {
    id: w.id,
    enabled: w.enabled,
    state: adaptState(w.state),
    lastError: w.last_error || undefined,
    restartAttempts: w.restart_attempts,
    keysPresent: w.keys_present,
    pid: w.pid,
    protocolVersion: w.protocol_version || undefined,
    serverName: w.server_name || undefined,
    serverVersion: w.server_version || undefined,
    toolCount: w.tool_count,
    resourceCount: w.resource_count,
    promptCount: w.prompt_count,
    stderrTail: w.stderr_tail || undefined,
  };
}

function adaptRecipeListing(w: WireRecipeListing): RecipeListing {
  return {
    recipe: adaptRecipe(w.recipe),
    enabled: w.enabled,
    status: adaptRecipeStatus(w.status),
    keysPresent: w.keysPresent,
  };
}

declare global {
  interface Window {
    go?: {
      rpc?: {
        Bindings?: WailsBindingsLike;
      };
    };
    runtime?: {
      EventsOn?: (
        topic: string,
        cb: (payload: unknown) => void,
      ) => () => void;
      EventsOff?: (topic: string) => void;
    };
  }
}

// ── view-scoped client interfaces ──────────────────────────────────────

export interface SessionsClient {
  list(): Promise<Session[]>;
  get(id: string): Promise<Session>;
  create(name: string): Promise<Session>;
  rename(id: string, name: string): Promise<void>;
  delete(id: string): Promise<void>;
  reorder(ids: string[]): Promise<void>;
  startStream(id: string): Promise<string>;
  stopStream(subscriptionId: string): Promise<void>;

  /**
   * listMessages returns the chat-message history for a session in
   * append-order. Pagination lands when long-context replays do; for now
   * the full transcript is returned.
   */
  listMessages(id: string): Promise<Message[]>;
  /**
   * appendMessage commits a single message to the session transcript and
   * returns the canonical Message (with server-assigned id + createdAt).
   * The Go side enforces redaction policy before persistence.
   */
  appendMessage(
    id: string,
    role: MessageRole,
    content: string,
  ): Promise<Message>;
  /**
   * sendMessageWithBlocks persists a user turn carrying polymorphic
   * content blocks (text + image + document) and returns the stored
   * Message. The LLM stream is NOT triggered — callers must invoke
   * `llm.startStream` afterwards (multimodal-io WP04).
   */
  sendMessageWithBlocks(
    id: string,
    contentBlocks: ContentBlock[],
  ): Promise<Message>;
  /** Persist a draft input for the session (debounced caller). */
  saveDraft(id: string, draft: string): Promise<void>;
  /** Load the persisted draft (empty string if none). */
  loadDraft(id: string): Promise<string>;
  /**
   * Persist the per-session starting context (Mission A). kind is
   * 'system' (invisible system prompt prepended on every send) or
   * 'user_seed' (visible — caller is responsible for ALSO appending
   * the content as a user message via appendMessage). The Go side
   * validates kind and rejects unknown values.
   */
  setSystemPrompt(
    id: string,
    content: string,
    kind: 'system' | 'user_seed',
  ): Promise<void>;
  /**
   * moveToProject sets the session's project membership. Empty
   * projectId detaches the session and makes it loose.
   */
  moveToProject(id: string, projectId: string): Promise<void>;
  /**
   * saveAsArtifact pins a message (or a sub-range thereof) as a
   * `user_pin` artifact. `rangeStart` / `rangeEnd` are byte offsets
   * into the message's content; `(0, 0)` captures the full message.
   * Defaults the range to `(0, 0)` when omitted.
   */
  saveAsArtifact(
    sessionId: string,
    messageId: string,
    title: string,
    rangeStart?: number,
    rangeEnd?: number,
  ): Promise<Artifact>;
}

/**
 * ArtifactsClient — view-scoped surface backing the artifacts table.
 *
 *   - `list({sessionId, projectId, mimeTypePrefix, source, scopeKind})`
 *     returns rows ordered by createdAt DESC. Empty filter returns
 *     every artifact.
 *   - `get(id)` returns metadata + base64-encoded bytes (Wails
 *     serialises Go `[]byte` to base64).
 *   - `promote(id, scopeKind, scopeId)` moves an artifact's scope.
 *     v1 supports `session → project` only; the spec reserves
 *     a future `global` tier.
 *   - `remove(id)` deletes the artifact (refcount-aware: the on-disk
 *     CAS file is removed only when the last reference drops).
 */
export interface ArtifactsClient {
  list(filter?: ArtifactFilter): Promise<Artifact[]>;
  get(id: string): Promise<ArtifactWithBytes>;
  promote(
    id: string,
    scopeKind: ArtifactScope,
    scopeId: string,
  ): Promise<Artifact>;
  remove(id: string): Promise<void>;
}

/**
 * ProjectsClient — top-level Project entity CRUD + session membership.
 * Projects group related sessions; sessions outside a project are loose.
 */
export interface ProjectsClient {
  list(): Promise<Project[]>;
  get(id: string): Promise<Project>;
  create(name: string, description?: string): Promise<Project>;
  rename(id: string, name: string): Promise<void>;
  updateDescription(id: string, description: string): Promise<void>;
  /**
   * remove deletes the project. When deleteSessions=true, every
   * session attached to the project is deleted as part of the same
   * operation; otherwise sessions become loose.
   */
  remove(id: string, deleteSessions: boolean): Promise<void>;
  addSession(projectId: string, sessionId: string): Promise<void>;
  removeSession(sessionId: string): Promise<void>;
  listSessions(projectId: string): Promise<Session[]>;
}

export interface LLMConnectorClient {
  listProviders(): Promise<Provider[]>;
  /**
   * startStream begins an assistant completion against `profileID` for
   * `sessionID`. modelOverride (optional) selects a non-default model
   * from the profile's authorised set — the backend validates and
   * substitutes it into the request. Returns the subscription id used
   * by `stopStream` and as the correlation key on `llm:stream-chunk`
   * events.
   */
  startStream(
    profileID: string,
    sessionID: string,
    modelOverride?: string,
  ): Promise<string>;
  stopStream(id: string): Promise<void>;
  /**
   * AddProvider persists a personal provider profile. The plaintextApiKey,
   * if supplied, is written to the OS keychain by the backend and zeroed
   * before any further processing. Only the CredentialReference enters
   * providers.json.
   */
  addProvider(input: AddProviderInput): Promise<void>;
  /**
   * UpdateProvider replaces an existing personal provider profile.
   * plaintextApiKey is OPTIONAL — when omitted, the keychain entry
   * is left in place so the user can edit model/region without
   * re-entering their credential.
   */
  updateProvider(input: AddProviderInput): Promise<void>;
  removeProvider(id: string): Promise<void>;
  testProvider(id: string): Promise<TestResult>;
  /**
   * Probe the provider for the set of models the supplied API key is
   * authorized to call. Returns an empty list when the kind has no
   * adapter or no /models endpoint — UI should fall back to manual
   * model entry in that case.
   */
  listModels(kind: string, plaintextApiKey: string): Promise<ModelInfo[]>;
  /**
   * Resolve a pending confirm-each tool-call modal (WP05). The frontend
   * calls this with the request id surfaced on the
   * `llm:tool-confirm-request` topic and one of the four canonical
   * decisions. The toolloop goroutine waiting on the request unblocks
   * and dispatches / blocks accordingly.
   */
  resolveConfirm(requestID: string, decision: ConfirmDecision): Promise<void>;
}

export interface MCPClient {
  listServers(): Promise<MCPServer[]>;
  startStream(id: string): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface A2AClient {
  listCards(): Promise<A2ACard[]>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface WorkflowClient {
  listJobs(): Promise<Job[]>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface TrustClient {
  listSecretReferences(): Promise<SecretReference[]>;
  getSecretReference(id: string): Promise<SecretReference>;
}

export interface ContextClient {
  list(): Promise<ContextEntry[]>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

/**
 * ContextsClient — file-tree CRUD for the Context Library (/contexts).
 *
 * The frontend treats the library as a flat content pool: scope (global
 * / project / session) is a separate concern handled by later WPs. Path
 * arguments are slash-separated and relative to the library root; the
 * Go side validates ".." / absolute / symlink-escape before any I/O.
 */
export interface ContextsClient {
  list(): Promise<ContextNode>;
  /**
   * listAll returns the tree with dotfiles included (excluding the
   * chassis-internal .trash and .recent.json metadata). Backs the
   * "Show hidden" toggle in /contexts (WP05).
   */
  listAll(): Promise<ContextNode>;
  get(path: string): Promise<string>;
  save(path: string, content: string): Promise<void>;
  createFolder(path: string): Promise<void>;
  rename(oldPath: string, newPath: string): Promise<void>;
  delete(path: string): Promise<void>;
  recentlyApplied(limit: number): Promise<string[]>;
  rootPath(): Promise<string>;
}

/**
 * AttachmentsClient — scoped context attachments (WP03 backend / WP04 UI).
 *
 * Attachments are durable snapshots of starting context at one of three
 * scopes (`global` / `project` / `session`). The persistence shape lives
 * in core/attachments; the rpc view exposes the typed wire surface
 * mirrored here.
 *
 * `list({scopeKind, scopeId})` returns rows for one scope ordered by
 * position; `listResolved(sessionID)` returns the merged stream in
 * [global..., project..., session...] order, suitable for the chat
 * surface's resolved-context panel.
 *
 * `add` accepts either an inline snapshot (`contentSource: "inline:<sha>"`)
 * or a library reference (`contentSource: "library:<root-rel>"`). The
 * snapshot survives deletion of the underlying library file (FR-202).
 *
 * `refresh(id)` re-reads a `library:<path>` attachment from the Context
 * Library. inline-source attachments are a no-op.
 */
export interface AttachmentsClient {
  list(filter: {
    scopeKind: AttachmentScopeKind | '';
    scopeId?: string;
  }): Promise<Attachment[]>;
  listResolved(sessionID: string): Promise<Attachment[]>;
  add(input: AttachmentAddInput): Promise<Attachment>;
  /**
   * addMedia uploads a base64-encoded image / PDF payload through the
   * MediaStore CAS path (multimodal-io WP02/WP03). The returned
   * Attachment carries `mediaId`, which the chat surface inspects to
   * resolve back to the on-disk binary.
   */
  addMedia(
    scopeKind: AttachmentScopeKind,
    scopeId: string,
    mediaBytesBase64: string,
    mediaType: string,
    originalName: string,
  ): Promise<Attachment>;
  remove(id: string): Promise<void>;
  reorder(
    scopeKind: AttachmentScopeKind,
    scopeId: string,
    idsInOrder: string[],
  ): Promise<void>;
  refresh(id: string): Promise<Attachment>;
}

export interface BundleClient {
  list(): Promise<Bundle[]>;
  get(id: string): Promise<Bundle>;
}

export interface PolicyClient {
  explain(input: Record<string, unknown>): Promise<Denial>;
  startStream(): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface AuditClient {
  listEntries(filter: AuditFilter): Promise<AuditEntry[]>;
  verifyEntry(id: string): Promise<boolean>;
  startStream(filter: AuditFilter): Promise<string>;
  stopStream(id: string): Promise<void>;
}

export interface SettingsClient {
  get(): Promise<Settings>;
  set(s: Settings): Promise<void>;
  loadRoute(): Promise<string>;
  saveRoute(route: string): Promise<void>;
  logRouteChange(from: string, to: string): Promise<void>;
  loadTheme(): Promise<Theme>;
  saveTheme(theme: Theme): Promise<void>;
  /** Read the long-term-memory opt-in flag (default false). */
  getMemory(): Promise<boolean>;
  /** Persist the long-term-memory opt-in flag. */
  setMemory(enabled: boolean): Promise<void>;
  /** Read the WP05 confirm-each modal opt-in flag (default true). */
  getConfirmEach(): Promise<boolean>;
  /** Persist the WP05 confirm-each modal opt-in flag. */
  setConfirmEach(enabled: boolean): Promise<void>;
}

/**
 * MemoryClient backs the chat-surface "📌 remember this" button + the
 * /memory management view. Privacy: chunks live in the harness's data
 * directory; the only network call is the embedding request when a
 * new pin is staged.
 *
 * Scope (WP06): RememberMessage accepts a third arg, one of
 * `'session' | 'project' | 'global'`, defaulting to `'session'` when
 * the caller omits it. PromoteScope moves an existing chunk to a wider
 * scope (move semantics — the original row is deleted and re-inserted
 * with a new ID; UI must refresh after the call).
 */
export interface MemoryClient {
  listChunks(filter?: MemoryListFilter): Promise<MemoryChunk[]>;
  rememberMessage(
    sessionID: string,
    messageID: string,
    scope?: MemoryScopeKind,
  ): Promise<string>;
  promoteScope(
    chunkID: string,
    newScopeKind: MemoryScopeKind,
    newScopeID: string,
  ): Promise<string>;
  forget(id: string): Promise<void>;
  /** Pin / unpin a chunk so it survives the prune sweep (WP15). */
  pin(id: string, pinned: boolean): Promise<void>;
  /** Tail the greedy-memory hook journal — what was captured at each
   * kernel boundary (WP16). */
  journalTail(
    scope: string,
    sinceSeq: number,
    limit: number,
  ): Promise<MemoryJournalEntry[]>;
  /** Compute the would-prune set without mutating the store (WP15). */
  prunePreview(scope: string): Promise<MemoryPrunePreview>;
  /** Apply the prune sweep immediately (WP15). */
  runPruneNow(scope: string): Promise<MemoryPruneStats>;
}

/**
 * DialsClient backs the /dials view + the cap-hit toast (Bundle E
 * WP17). The four methods mirror Dials_Get / Dials_Set /
 * Dials_GetEffective / Dials_BumpAndResume.
 */
export interface DialsClient {
  get(key: DialScopeKey): Promise<DialConfig>;
  set(key: DialScopeKey, cfg: DialConfig): Promise<void>;
  getEffective(
    projectID: string,
    sessionID: string,
    graphID: string,
    runID: string,
  ): Promise<DialEffectiveDials>;
  bumpAndResume(runID: string, delta: DialDelta): Promise<void>;
}

/**
 * HooksClient backs the /hooks management view. Hooks are stored in
 * <DataDir>/hooks.json (mode 0600) and dispatched on the chat
 * pre_send / post_send lifecycle. Memory.retrieve / memory.persist
 * are the v1 preinstalled builtins; the surface ships extension
 * points for `shell` and `mcp` hooks the user configures.
 */
export interface HooksClient {
  list(): Promise<Hook[]>;
  get(id: string): Promise<Hook>;
  add(input: Hook): Promise<Hook>;
  update(input: Hook): Promise<void>;
  remove(id: string): Promise<void>;
  availableBuiltins(): Promise<BuiltinDescriptor[]>;
  /** Auto-install the two preinstalled memory hooks (idempotent). */
  installStarterMemory(): Promise<void>;
  /** Remove the two preinstalled memory hooks (idempotent). */
  removeStarterMemory(): Promise<void>;
}

/**
 * ToolsRecipesClient — view-scoped surface for the shipped MCP recipes
 * catalog. Drives the Tools panel toggles + key-prompt modal.
 *
 *   - `list()` returns every shipped recipe overlaid with its
 *     enabled-state, live status snapshot, and keys-resolvable hint.
 *   - `install(id, env)` enables the recipe, stores any provided keys
 *     in the OS keychain, and spawns the server. The plaintext env
 *     map crosses the Wails boundary once and is zeroed on the Go
 *     side; the frontend caller should not retain it.
 *   - `uninstall(id)` stops the running server (SIGTERM grace) and
 *     removes the recipe from the persisted enabled list. Keychain
 *     entries are NOT deleted — explicit deletion goes through
 *     `forgetKey`.
 *   - `forgetKey(id, envName)` removes one keychain entry.
 *   - `status(id)` returns the live status snapshot for one recipe.
 */
export interface ToolsRecipesClient {
  list(): Promise<RecipeListing[]>;
  /**
   * install enables the recipe, stores any provided env keys in the
   * OS keychain, expands the per-install ConfigOption values
   * (directory_list paths, booleans, strings), and spawns the server.
   * `config` is optional — recipes that declare no ConfigOptions
   * (e.g. Brave Search) accept any value (including undefined / {}).
   */
  install(
    id: string,
    env: Record<string, string>,
    config?: Record<string, unknown>,
  ): Promise<RecipeStatus>;
  uninstall(id: string): Promise<void>;
  forgetKey(id: string, envName: string): Promise<void>;
  status(id: string): Promise<RecipeStatus>;
  /**
   * config returns the persisted per-install ConfigOption map for an
   * enabled recipe (e.g. {allowed_directories: [...]} for the
   * filesystem recipe). Returns an empty object for recipes that are
   * not enabled or have no config.
   */
  config(id: string): Promise<Record<string, unknown>>;
}

export interface ToolsClient {
  recipes: ToolsRecipesClient;
}

/**
 * ShellClient — view-scoped surface for OS-shell affordances.
 *
 *   - openInOSBrowser opens an absolute filesystem path in the OS
 *     file browser via Wails's BrowserOpenURL.
 *   - pathComplete resolves up to 32 path completions for the
 *     supplied partial. Completions whose canonical form lands in
 *     the deny-list are filtered out (multimodal-io WP04 backs the
 *     chat-input @filepath shortcut).
 *   - readFile reads a single file's bytes + MIME type, with deny-
 *     list enforcement and per-kind size caps. The bytes are
 *     base64-encoded on the wire.
 */
export interface ShellClient {
  openInOSBrowser(path: string): Promise<void>;
  pathComplete(partial: string): Promise<string[]>;
  readFile(path: string): Promise<ShellReadFileResult>;
}

/**
 * SlashClient — view-scoped surface for in-chat slash commands.
 *
 *   - list returns the registered visible commands (sorted) so the
 *     autocomplete dropdown can render without a round-trip per
 *     keystroke (single fetch on mount).
 *   - execute parses raw ("/foo arg1 arg2") and dispatches to the
 *     registered handler. Unknown commands and parse errors surface
 *     as SlashExecuteResults with kind="error" — the surface never
 *     crashes the composer.
 */
export interface SlashClient {
  list(): Promise<SlashCommandInfo[]>;
  execute(sessionID: string, raw: string): Promise<SlashExecuteResult>;
}

/**
 * CorpusClient — bulk-ingest knowledge corpora (mission
 * agent-kernel-graph; Bundle C WP10/WP11). Backs the Knowledge view's
 * three surfaces:
 *
 *   - listCorpora / createCorpus / deleteCorpus drive the corpus list.
 *   - ingestPath kicks off a background job; jobStatus polls progress.
 *   - listFiles / listChunks render the per-corpus detail view.
 *   - retrieve runs cosine top-K with an enforced token-budget cap.
 *
 * The Go side persists chunk text + embeddings under
 * `<DataDir>/corpora/<id>/`; only the text crosses the Wails boundary.
 */
export interface CorpusClient {
  listCorpora(scope: string): Promise<Corpus[]>;
  createCorpus(req: CorpusCreateRequest): Promise<Corpus>;
  getCorpus(corpusID: string): Promise<Corpus>;
  deleteCorpus(corpusID: string): Promise<void>;
  listFiles(corpusID: string): Promise<CorpusFile[]>;
  listChunks(corpusID: string, fileID: string): Promise<CorpusChunk[]>;
  ingestPath(
    corpusID: string,
    path: string,
    opts: CorpusIngestOptions,
  ): Promise<CorpusIngestStatus>;
  jobStatus(jobID: string): Promise<CorpusIngestStatus>;
  retrieve(
    corpusID: string,
    req: CorpusRetrieveRequest,
  ): Promise<CorpusRetrieveResponse>;
}

export interface HarnessClient {
  shellStatus(): Promise<ShellStatus>;
  appInfo(): Promise<AppInfo>;

  sessions: SessionsClient;
  projects: ProjectsClient;
  llm: LLMConnectorClient;
  mcp: MCPClient;
  a2a: A2AClient;
  workflow: WorkflowClient;
  trust: TrustClient;
  context: ContextClient;
  contexts: ContextsClient;
  attachments: AttachmentsClient;
  bundle: BundleClient;
  policy: PolicyClient;
  audit: AuditClient;
  settings: SettingsClient;
  memory: MemoryClient;
  hooks: HooksClient;
  tools: ToolsClient;
  shell: ShellClient;
  slash: SlashClient;
  artifacts: ArtifactsClient;
  corpus: CorpusClient;
  dials: DialsClient;
}

// ── runtime client ─────────────────────────────────────────────────────

function wailsBindings(): WailsBindingsLike {
  const b = (typeof window !== 'undefined' && window.go?.rpc?.Bindings) || undefined;
  if (!b) {
    throw new Error(
      'window.go.rpc.Bindings is not available. The harness frontend must run inside Wails.',
    );
  }
  return b;
}

export function createHarnessClient(): HarnessClient {
  const b: () => WailsBindingsLike = () => wailsBindings();

  return {
    shellStatus: () => b().ShellStatus(),
    appInfo: () => b().AppInfo(),

    sessions: {
      list: () => b().Sessions_List(),
      get: (id) => b().Sessions_Get(id),
      create: (name) => b().Sessions_Create(name),
      rename: (id, name) => b().Sessions_Rename(id, name),
      delete: (id) => b().Sessions_Delete(id),
      reorder: (ids) => b().Sessions_Reorder(ids),
      startStream: (id) => b().Sessions_StartStream(id),
      stopStream: (id) => b().Sessions_StopStream(id),
      listMessages: (id) => b().Sessions_ListMessages(id),
      appendMessage: (id, role, content) =>
        b().Sessions_AppendMessage(id, role, content),
      sendMessageWithBlocks: (id, contentBlocks) =>
        b().Sessions_SendMessageWithBlocks(id, contentBlocks),
      saveDraft: (id, draft) => b().Sessions_SaveDraft(id, draft),
      loadDraft: (id) => b().Sessions_LoadDraft(id),
      setSystemPrompt: (id, content, kind) =>
        b().Sessions_SetSystemPrompt(id, content, kind),
      moveToProject: (id, projectId) =>
        b().Sessions_MoveToProject(id, projectId),
      saveAsArtifact: (sessionId, messageId, title, rangeStart, rangeEnd) =>
        b().Sessions_SaveAsArtifact(
          sessionId,
          messageId,
          title,
          rangeStart ?? 0,
          rangeEnd ?? 0,
        ),
    },
    artifacts: {
      list: (filter) => b().Artifacts_List(filter ?? {}),
      get: async (id) => {
        const wire = await b().Artifacts_Get(id);
        return {
          artifact: wire.artifact,
          bytes: adaptArtifactBytes(wire.bytes),
        };
      },
      promote: (id, scopeKind, scopeId) =>
        b().Artifacts_Promote(id, scopeKind, scopeId),
      remove: (id) => b().Artifacts_Delete(id),
    },
    projects: {
      list: () => b().Projects_List(),
      get: (id) => b().Projects_Get(id),
      create: (name, description) =>
        b().Projects_Create(name, description ?? ''),
      rename: (id, name) => b().Projects_Rename(id, name),
      updateDescription: (id, description) =>
        b().Projects_UpdateDescription(id, description),
      remove: (id, deleteSessions) =>
        b().Projects_Delete(id, deleteSessions),
      addSession: (projectId, sessionId) =>
        b().Projects_AddSession(projectId, sessionId),
      removeSession: (sessionId) => b().Projects_RemoveSession(sessionId),
      listSessions: (projectId) => b().Projects_ListSessions(projectId),
    },
    llm: {
      listProviders: () => b().LLM_ListProviders(),
      startStream: (profileID, sessionID, modelOverride) =>
        b().LLM_StartStream(profileID, sessionID, modelOverride ?? ''),
      stopStream: (id) => b().LLM_StopStream(id),
      addProvider: (input) => b().LLM_AddProvider(input),
      updateProvider: (input) => b().LLM_UpdateProvider(input),
      removeProvider: (id) => b().LLM_RemoveProvider(id),
      testProvider: (id) => b().LLM_TestProvider(id),
      listModels: (kind, plaintextApiKey) =>
        b().LLM_ListModels(kind, plaintextApiKey),
      resolveConfirm: (requestID, decision) =>
        b().LLM_ResolveConfirm(requestID, decision),
    },
    mcp: {
      listServers: () => b().MCP_ListServers(),
      startStream: (id) => b().MCP_StartStream(id),
      stopStream: (id) => b().MCP_StopStream(id),
    },
    a2a: {
      listCards: () => b().A2A_ListCards(),
      startStream: () => b().A2A_StartStream(),
      stopStream: (id) => b().A2A_StopStream(id),
    },
    workflow: {
      listJobs: () => b().Workflow_ListJobs(),
      startStream: () => b().Workflow_StartStream(),
      stopStream: (id) => b().Workflow_StopStream(id),
    },
    trust: {
      listSecretReferences: () => b().Trust_ListSecretReferences(),
      getSecretReference: (id) => b().Trust_GetSecretReference(id),
    },
    context: {
      list: () => b().Context_List(),
      startStream: () => b().Context_StartStream(),
      stopStream: (id) => b().Context_StopStream(id),
    },
    contexts: {
      list: () => b().Contexts_List(),
      listAll: () => b().Contexts_ListAll(),
      get: (path) => b().Contexts_Get(path),
      save: (path, content) => b().Contexts_Save(path, content),
      createFolder: (path) => b().Contexts_CreateFolder(path),
      rename: (oldPath, newPath) => b().Contexts_Rename(oldPath, newPath),
      delete: (path) => b().Contexts_Delete(path),
      recentlyApplied: (limit) => b().Contexts_RecentlyApplied(limit),
      rootPath: () => b().Contexts_RootPath(),
    },
    attachments: {
      list: ({ scopeKind, scopeId }) =>
        b().Attachments_List(scopeKind, scopeId ?? ''),
      listResolved: (sessionID) => b().Attachments_ListResolved(sessionID),
      add: (input) => b().Attachments_Add(input),
      addMedia: (scopeKind, scopeId, mediaBytesBase64, mediaType, originalName) =>
        b().Attachments_AddMedia({
          scopeKind,
          scopeId,
          mediaBytesBase64,
          mediaType,
          originalName,
        }),
      remove: (id) => b().Attachments_Remove(id),
      reorder: (scopeKind, scopeId, idsInOrder) =>
        b().Attachments_Reorder(scopeKind, scopeId, idsInOrder),
      refresh: (id) => b().Attachments_Refresh(id),
    },
    bundle: {
      list: () => b().Bundle_List(),
      get: (id) => b().Bundle_Get(id),
    },
    policy: {
      explain: (input) => b().Policy_Explain(input),
      startStream: () => b().Policy_StartStream(),
      stopStream: (id) => b().Policy_StopStream(id),
    },
    audit: {
      listEntries: (filter) => b().Audit_ListEntries(filter),
      verifyEntry: (id) => b().Audit_VerifyEntry(id),
      startStream: (filter) => b().Audit_StartStream(filter),
      stopStream: (id) => b().Audit_StopStream(id),
    },
    settings: {
      get: () => b().Settings_Get(),
      set: (s) => b().Settings_Set(s),
      loadRoute: () => b().LoadRoute(),
      saveRoute: (r) => b().SaveRoute(r),
      logRouteChange: (f, t) => b().LogRouteChange(f, t),
      loadTheme: () => b().LoadTheme() as Promise<Theme>,
      saveTheme: (t) => b().SaveTheme(t),
      getMemory: () => b().Settings_GetMemory(),
      setMemory: (enabled) => b().Settings_SetMemory(enabled),
      getConfirmEach: () => b().Settings_GetConfirmEach(),
      setConfirmEach: (enabled) => b().Settings_SetConfirmEach(enabled),
    },
    memory: {
      listChunks: (filter) => b().Memory_ListChunks(filter ?? {}),
      rememberMessage: (sessionID, messageID, scope) =>
        b().Memory_RememberMessage(sessionID, messageID, scope ?? 'session'),
      promoteScope: (chunkID, newScopeKind, newScopeID) =>
        b().Memory_PromoteScope(chunkID, newScopeKind, newScopeID),
      forget: (id) => b().Memory_Forget(id),
      pin: (id, pinned) => b().Memory_Pin(id, pinned),
      journalTail: (scope, sinceSeq, limit) =>
        b().Memory_JournalTail(scope, sinceSeq, limit),
      prunePreview: (scope) => b().Memory_PrunePreview(scope),
      runPruneNow: (scope) => b().Memory_RunPruneNow(scope),
    },
    dials: {
      get: (key) => b().Dials_Get(key),
      set: (key, cfg) => b().Dials_Set(key, cfg),
      getEffective: (projectID, sessionID, graphID, runID) =>
        b().Dials_GetEffective(projectID, sessionID, graphID, runID),
      bumpAndResume: (runID, delta) =>
        b().Dials_BumpAndResume(runID, delta),
    },
    hooks: {
      list: () => b().Hooks_List(),
      get: (id) => b().Hooks_Get(id),
      add: (input) => b().Hooks_Add(input),
      update: (input) => b().Hooks_Update(input),
      remove: (id) => b().Hooks_Remove(id),
      availableBuiltins: () => b().Hooks_AvailableBuiltins(),
      installStarterMemory: () => b().Hooks_InstallStarterMemory(),
      removeStarterMemory: () => b().Hooks_RemoveStarterMemory(),
    },
    tools: {
      recipes: {
        list: async () =>
          (await b().Tools_ListRecipes()).map(adaptRecipeListing),
        install: async (id, env, config) =>
          adaptRecipeStatus(
            await b().Tools_InstallRecipe(id, env, config ?? {}),
          ),
        uninstall: (id) => b().Tools_UninstallRecipe(id),
        forgetKey: (id, envName) => b().Tools_ForgetRecipeKey(id, envName),
        status: async (id) =>
          adaptRecipeStatus(await b().Tools_RecipeStatus(id)),
        config: (id) => b().Tools_RecipeConfig(id),
      },
    },
    shell: {
      openInOSBrowser: (path) => b().Shell_OpenInOSBrowser(path),
      pathComplete: (partial) => b().Shell_PathComplete(partial),
      readFile: (path) => b().Shell_ReadFile(path),
    },
    slash: {
      list: () => b().Slash_List(),
      execute: (sessionID, raw) => b().Slash_Execute(sessionID, raw),
    },
    corpus: {
      listCorpora: (scope) => b().Corpus_ListCorpora(scope),
      createCorpus: (req) => b().Corpus_CreateCorpus(req),
      getCorpus: (id) => b().Corpus_GetCorpus(id),
      deleteCorpus: (id) => b().Corpus_DeleteCorpus(id),
      listFiles: (id) => b().Corpus_ListFiles(id),
      listChunks: (id, fileID) => b().Corpus_ListChunks(id, fileID),
      ingestPath: (id, path, opts) => b().Corpus_IngestPath(id, path, opts),
      jobStatus: (jobID) => b().Corpus_JobStatus(jobID),
      retrieve: (id, req) => b().Corpus_Retrieve(id, req),
    },
  };
}

// ── fake client for tests ──────────────────────────────────────────────

/**
 * createFakeHarnessClient — a deeply-stubbed client whose every method
 * resolves to safe defaults. Tests pass `seed` to override specific
 * sub-clients. Used by `provideFakeClient` (FR-008, SC-006).
 */
export function createFakeHarnessClient(
  seed: Partial<HarnessClient> = {},
): HarnessClient {
  const noop = async () => undefined as unknown as void;

  const defaults: HarnessClient = {
    shellStatus: async () => ({
      activeProvider: '—',
      trustTier: 'Local',
      harnessBuild: '0.0.0-fake',
      connection: 'ready',
      eventRate: 0,
      policyApplied: true,
      redactionOn: true,
      localFirstOn: true,
    }),
    appInfo: async () => ({
      build: 'fake',
      commit: 'fake',
      buildTime: '',
      goVersion: '',
      platform: 'fake',
      windowSize: { width: 1280, height: 800 },
    }),
    sessions: {
      list: async () => [],
      get: async (id) => ({ id, name: id, createdAt: '', updatedAt: '' }),
      create: async (name) => ({
        id: `fake-${Math.random().toString(36).slice(2, 8)}`,
        name,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }),
      rename: noop,
      delete: noop,
      reorder: noop,
      startStream: async () => 'fake-sub',
      stopStream: noop,
      listMessages: async () => [],
      appendMessage: async (id, role, content) => ({
        id: `fake-msg-${Math.random().toString(36).slice(2, 8)}`,
        sessionId: id,
        role,
        content,
        createdAt: new Date().toISOString(),
      }),
      sendMessageWithBlocks: async (id, contentBlocks) => {
        const text =
          contentBlocks
            .filter((b) => b.type === 'text')
            .map((b) => b.text ?? '')
            .join('\n') ?? '';
        return {
          id: `fake-msg-${Math.random().toString(36).slice(2, 8)}`,
          sessionId: id,
          role: 'user' as MessageRole,
          content: text,
          contentBlocks,
          createdAt: new Date().toISOString(),
        };
      },
      saveDraft: noop,
      loadDraft: async () => '',
      setSystemPrompt: noop,
      moveToProject: noop,
      saveAsArtifact: async (sessionId, messageId, title) => ({
        id: `fake-art-${Math.random().toString(36).slice(2, 8)}`,
        sessionId,
        title,
        mimeType: 'text/plain',
        contentHash: 'fake-hash',
        byteSize: 0,
        source: 'user_pin',
        sourceRef: { messageId },
        scopeKind: 'session',
        createdAt: new Date().toISOString(),
      }),
    },
    projects: {
      list: async () => [],
      get: async (id) => ({
        id,
        name: id,
        description: '',
        createdAt: '',
        updatedAt: '',
      }),
      create: async (name, description) => ({
        id: `fake-proj-${Math.random().toString(36).slice(2, 8)}`,
        name,
        description: description ?? '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }),
      rename: noop,
      updateDescription: noop,
      remove: noop,
      addSession: noop,
      removeSession: noop,
      listSessions: async () => [],
    },
    llm: {
      listProviders: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
      addProvider: noop,
      updateProvider: noop,
      removeProvider: noop,
      testProvider: async () => ({
        success: true,
        latency_ms: 1,
        message: 'fake ok',
      }),
      listModels: async () => [],
      resolveConfirm: noop,
    },
    mcp: {
      listServers: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    a2a: {
      listCards: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    workflow: {
      listJobs: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    trust: {
      listSecretReferences: async () => [],
      getSecretReference: async (id) => ({
        id,
        label: id,
        source: 'fake',
        createdAt: '',
      }),
    },
    context: {
      list: async () => [],
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    contexts: {
      list: async () => ({ name: '', path: '', kind: 'folder' as const }),
      listAll: async () => ({ name: '', path: '', kind: 'folder' as const }),
      get: async () => '',
      save: noop,
      createFolder: noop,
      rename: noop,
      delete: noop,
      recentlyApplied: async () => [],
      rootPath: async () => '/fake/contexts',
    },
    attachments: {
      list: async () => [],
      listResolved: async () => [],
      add: async (input) => ({
        id: `fake-att-${Math.random().toString(36).slice(2, 8)}`,
        scopeKind: input.scopeKind,
        scopeId: input.scopeId,
        contentSource: input.contentSource,
        content: input.content,
        kind: input.kind ?? 'system',
        position: input.position ?? 0,
        createdAt: new Date().toISOString(),
      }),
      addMedia: async (scopeKind, scopeId, _mediaBytesBase64, mediaType, originalName) => ({
        id: `fake-media-${Math.random().toString(36).slice(2, 8)}`,
        scopeKind,
        scopeId,
        contentSource: `media:fake-${mediaType}`,
        content: originalName,
        kind: 'system' as const,
        position: 0,
        createdAt: new Date().toISOString(),
      }),
      remove: noop,
      reorder: noop,
      refresh: async (id) => ({
        id,
        scopeKind: 'session',
        scopeId: '',
        contentSource: 'inline:fake',
        content: '',
        kind: 'system',
        position: 0,
        createdAt: new Date().toISOString(),
      }),
    },
    bundle: {
      list: async () => [],
      get: async (id) => ({
        id,
        name: id,
        version: '',
        tier: '',
        artifactCount: 0,
      }),
    },
    policy: {
      explain: async () => ({
        policyId: 'fake-policy',
        clauseId: 'fake-clause',
        violatingInput: '',
        remediation: '',
      }),
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    audit: {
      listEntries: async () => [],
      verifyEntry: async () => true,
      startStream: async () => 'fake-sub',
      stopStream: noop,
    },
    settings: {
      get: async () => ({
        schemaVersion: 1,
        lastRoute: '/sessions',
        theme: 'system',
        accent: 'default',
        windowSize: { width: 1280, height: 800 },
        memoryEnabled: false,
        confirmEachDisabled: false,
      }),
      set: noop,
      loadRoute: async () => '/sessions',
      saveRoute: noop,
      logRouteChange: noop,
      loadTheme: async () => 'system' as Theme,
      saveTheme: noop,
      getMemory: async () => false,
      setMemory: noop,
      getConfirmEach: async () => true,
      setConfirmEach: noop,
    },
    memory: {
      listChunks: async () => [],
      rememberMessage: async () => 'fake-mem-id',
      promoteScope: async () => 'fake-mem-id',
      forget: noop,
      pin: noop,
      journalTail: async () => [],
      prunePreview: async () => ({
        verdicts: [],
        stats: {
          startedAt: new Date().toISOString(),
          durationMs: 0,
          kept: 0,
          dropped: 0,
          collapsed: 0,
          pinned: 0,
        },
      }),
      runPruneNow: async () => ({
        startedAt: new Date().toISOString(),
        durationMs: 0,
        kept: 0,
        dropped: 0,
        collapsed: 0,
        pinned: 0,
      }),
    },
    dials: {
      get: async () => ({}),
      set: noop,
      getEffective: async () => ({
        maxTokensPerRun: { value: 0, from: 'global' },
        maxWallclockSeconds: { value: 0, from: 'global' },
        maxLLMCalls: { value: 0, from: 'global' },
        maxToolCalls: { value: 0, from: 'global' },
        maxCostUSD: { value: 0, from: 'global' },
        planVerbosity: { value: 'normal', from: 'global' },
        askThreshold: { value: 0.4, from: 'global' },
        reflectFrequency: { value: 1, from: 'global' },
        compactionAggressiveness: { value: 0.5, from: 'global' },
        reviewIterationsCap: { value: 3, from: 'global' },
        memoryHooksEnabled: { value: true, from: 'global' },
        memoryPruneIntervalSeconds: { value: 86400, from: 'global' },
      }),
      bumpAndResume: noop,
    },
    hooks: {
      list: async () => [],
      get: async (id) => ({
        id,
        name: id,
        event: 'pre_send',
        kind: 'builtin',
        enabled: false,
        match: {},
      }),
      add: async (input) => input,
      update: noop,
      remove: noop,
      availableBuiltins: async () => [],
      installStarterMemory: noop,
      removeStarterMemory: noop,
    },
    tools: {
      recipes: {
        list: async () => [],
        install: async (id) => ({
          id,
          enabled: true,
          state: 'starting',
          restartAttempts: 0,
          keysPresent: true,
          pid: 0,
          toolCount: 0,
          resourceCount: 0,
          promptCount: 0,
        }),
        uninstall: noop,
        forgetKey: noop,
        status: async (id) => ({
          id,
          enabled: false,
          state: 'stopped',
          restartAttempts: 0,
          keysPresent: false,
          pid: 0,
          toolCount: 0,
          resourceCount: 0,
          promptCount: 0,
        }),
        config: async () => ({}),
      },
    },
    shell: {
      openInOSBrowser: noop,
      pathComplete: async () => [],
      readFile: async () => ({ dataBase64: '', mediaType: '' }),
    },
    slash: {
      list: async () => [
        { name: 'help', description: 'List available slash commands.', comingSoon: false },
        { name: 'clear', description: 'Insert a divider in the current chat (history preserved).', comingSoon: false },
        { name: 'model', description: 'Switch the active model — e.g. /model gpt-4o', comingSoon: false },
        { name: 'memorize', description: 'Pin text to long-term memory (coming soon).', comingSoon: true },
        { name: 'recall', description: 'Recall memory chunks matching a query (coming soon).', comingSoon: true },
        { name: 'forget', description: 'Forget a memory chunk by id (coming soon).', comingSoon: true },
        { name: 'branch', description: 'Branch the conversation onto a smaller or larger model (coming soon).', comingSoon: true },
      ],
      execute: async (_sessionID, raw) => ({
        text: `fake slash result for ${raw}`,
        kind: 'info' as const,
      }),
    },
    artifacts: {
      list: async () => [],
      get: async (id) => ({
        artifact: {
          id,
          sessionId: '',
          title: id,
          mimeType: 'text/plain',
          contentHash: 'fake-hash',
          byteSize: 0,
          source: 'user_pin',
          sourceRef: { messageId: '' },
          scopeKind: 'session',
          createdAt: new Date().toISOString(),
        },
        bytes: '',
      }),
      promote: async (id, scopeKind) => ({
        id,
        sessionId: '',
        title: id,
        mimeType: 'text/plain',
        contentHash: 'fake-hash',
        byteSize: 0,
        source: 'user_pin',
        sourceRef: { messageId: '' },
        scopeKind,
        createdAt: new Date().toISOString(),
      }),
      remove: noop,
    },
    corpus: {
      listCorpora: async () => [],
      createCorpus: async (req) => ({
        id: 'fake-corpus',
        name: req.name,
        scope: req.scope,
        scopeId: req.scopeId,
        tag: req.tag,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }),
      getCorpus: async (id) => ({
        id,
        name: 'fake',
        scope: 'global',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }),
      deleteCorpus: noop,
      listFiles: async () => [],
      listChunks: async () => [],
      ingestPath: async (corpusId, path) => ({
        jobId: 'fake-job',
        corpusId,
        state: 'completed',
        path,
        filesTotal: 0,
        filesDone: 0,
        filesSkip: 0,
        chunksTotal: 0,
        startedAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }),
      jobStatus: async (jobId) => ({
        jobId,
        corpusId: 'fake',
        state: 'completed',
        path: '',
        filesTotal: 0,
        filesDone: 0,
        filesSkip: 0,
        chunksTotal: 0,
        startedAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      }),
      retrieve: async () => ({ results: [], dropped: 0 }),
    },
  };

  return { ...defaults, ...seed };
}
