// Code generated by core/serve/cmd/gen-served-topics; DO NOT EDIT.
// Source: core/serve/wsstream.go passthroughTopics (via serve.PassthroughTopics())
//
// This is the single source of truth for which bus topics core/serve
// forwards to a served-mode (workbench) client verbatim. See
// core/serve/wsstream.go's PassthroughTopics() doc comment for the full
// history (findings #63 / #62 — this file used to be a hand-maintained
// copy that drifted).
//
// To regenerate:
//   go generate ./core/serve/...

export const SERVED_STREAM_TOPICS = [
  'llm:stream-chunk',
  'llm:stream-closed',
  'llm:fallback-attempted',
  'session.usage.updated',
  'cost.threshold.crossed',
  'bash:permission-pending',
  'cred:permission-pending',
  'fs:permission-pending',
  'tool:permission-pending',
  'elicit:pending',
  'chat:overflow-recovery',
  'tool:confirm-pending',
  'storage.migration.drift-detected',
  'mcp:health-changed',
  'contextbootstrap:progress',
  'elicit:deferred',
  'elicit:deferred:answered',
  'fleet:lockdown:changed',
  'fleet:session:expired',
] as const;
